ROOT=../../..

DIR=CommExample/Client

include $(ROOT)/mak/config.mak

EXTRA_INCLUDES = $(SYS_INCLUDES) $(ACE_INCLUDES)
LIBRARIES = $(ACE_LIB)

SOURCES = Comm.cpp ACEComm.cpp CommClient.cpp

PROGRAM = CommClient

include $(ROOT)/mak/program.mak
