ROOT = ../../../../..
DIR = Pegasus/Common/tests/Resolve
include $(ROOT)/mak/config.mak
include ../libraries.mak

PROGRAM = TestResolve
SOURCES = Resolve.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)

poststarttests:

