ROOT = $(PEGASUS_ROOT)

DIR = Providers/sample/RT_Indication/RT_IndicationConsumer

include $(ROOT)/mak/config.mak

LIBRARY = RT_IndicationConsumer

LIBRARIES = \
	 pegcommon 
	
SOURCES = \
   RT_IndicationConsumerMain.cpp \
   RT_IndicationConsumer.cpp 

include $(ROOT)/mak/library.mak

tests:
