# This is a recurse make file to make ONE OF the repository implementations.
# Note that as of the current Pegasus, you may only make one repository
# because they all have the same dll name and therefore, the last make
# becomes the repository implementation.
ROOT=../../..

include $(ROOT)/mak/config.mak

TEST_DIRS = \


DIRS = \
    genericfile
    

#    genericfile\tests
    

include $(ROOT)/mak/recurse.mak
