ROOT = ../../../../..

DIR = Pegasus/Config/tests/ConfigFileHandler

include $(ROOT)/mak/config.mak

include ../libraries.mak

PROGRAM = TestConfigFileHanler
SOURCES = ConfigFileHandler.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)
