ROOT = ../../../../..
DIR = Pegasus/Repository/NameSpaceManager
include $(ROOT)/mak/config.mak
include ../libraries.mak

PROGRAM = NameSpaceManager
SOURCES = NameSpaceManager.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)
