ROOT = ../../../..
include ../../libraries.mak

DIR = Providers/generic/OperatingSystemProvider

include $(ROOT)/mak/config.mak

LIBRARY = OperatingSystemProvider

LIBRARIES = \
	pegcommon \
	pegprovider

SOURCES = \
	OperatingSystem.cpp \
	OperatingSystemProvider.cpp \
	OperatingSystemProviderMain.cpp

include $(ROOT)/mak/library.mak
