#pragma locale ("en_US")

// physical provider
instance of PG_ProviderModule
{
    Name = "OperatingSystemProvider (MODULE)";
    Vendor = "Pegasus";
    InterfaceType = "PG_DefaultC++";
    InterfaceVersion = "2.0.0";
    Location = "OperatingSystemProvider";
};

// logical provider
instance of PG_Provider
{
    Name = "OperatingSystemProvider (PROVIDER)";
    ProviderModuleName = "OperatingSystemProvider (MODULE)";
};

// logical provider capabilities
instance of PG_ProviderCapabilities
{
    ProviderModuleName = "OperatingSystemProvider (MODULE)";
    ProviderName = "OperatingSystemProvider (PROVIDER)";
    CapabilityID = "OperatingSystemProvider";
    ClassName = "Pegasus_OperatingSystem";
    Namespaces = { "root/cimv2" };
    ProviderType = { 2 };
    //SupportedProperties = {};
    //SupportedMethods = {};
};

// association of module and provider
//instance of PG_ProviderModuleElements
//{
//};

// association of provider and capabilities
//instance of PG_ProviderCapababilitiesElements
//{
//};

