#pragma classflags("forceupdate")
#pragma namespace("\\\\.\\root\\cimv2")

[dynamic,
provider("IBMPSG|UMServices|WMIProvider"),
framework_module("OperatingSystemProvider")]
class Pegasus_OperatingSystem	: CIM_OperatingSystem
{
	
	string CSCreationClassName;
	string CSName;
	string CreationClassName;
	string Name;
	uint16 OSType;
	string OtherTypeDescription;
	string Version;
	datetime LastBootUpTime;
	datetime LocalDateTime;
	sint16 CurrentTimeZone;
	uint32 NumberOfLicensedUsers;
	uint32 NumberOfUsers;
	uint32 NumberOfProcesses;
	uint32 MaxNumberOfProcesses;
	uint64 TotalSwapSpaceSize;
	uint64 TotalVirtualMemorySize;
	uint64 FreeVirtualMemory;
	uint64 FreePhysicalMemory;
	uint64 TotalVisibleMemorySize;
	uint64 SizeStoredInPagingFiles;
	uint64 FreeSpaceInPagingFiles;
	uint64 MaxProcessMemorySize;
	boolean Distributed;
};