ROOT = ../../../../..
DIR = Pegasus/Common/tests/Abstract
include $(ROOT)/mak/config.mak
include ../libraries.mak

PROGRAM = Abstract
SOURCES = Abstract.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)
