ROOT = ../../../../..
DIR = Pegasus/Common/tests/StrToInstName
include $(ROOT)/mak/config.mak
include ../libraries.mak

LOCAL_DEFINES = -DPEGASUS_INTERNALONLY

PROGRAM = TestStrToInstName
SOURCES = StrToInstName.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)

poststarttests:

