ROOT = ../../../../..
DIR = Pegasus/Common/tests/StrToInstName
include $(ROOT)/mak/config.mak
include ../libraries.mak

PROGRAM = TestStrToInstName
SOURCES = StrToInstName.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)
