# Wbemexec test associated w/EnumerateClassNames
#

ROOT = ../../../..
include $(ROOT)/mak/config.mak
include $(ROOT)/test/config.mak

XMLSCRIPTS = CreateInstance53000 CreateInstance54000 CreateInstance55000 EnumerateInstanceNames55000 DeleteInstance55000 DeleteInstance54000 DeleteInstance53000

clean:
	$(RM) $(XMLRESPONSES)


tests: $(XMLRESPONSES)

