ROOT = ../../../../..
DIR = Pegasus/_cimom/tests/MessageQueueService
include $(ROOT)/mak/config.mak
include ../libraries.mak

PROGRAM = MessageQueueService
SOURCES = MessageQueueService.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)
