ROOT = ../../../../..
DIR = Pegasus/_cimom/tests/MessageQueueService
include $(ROOT)/mak/config.mak
#include ../libraries.mak

PROGRAM = MessageQueueService
SOURCES = MessageQueueService.cpp

LIBRARIES = _cimom pegcommon
include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)
