ROOT = ../../../../..
DIR = Pegasus/DynListener/tests/TestDynListener
include $(ROOT)/mak/config.mak
include ../libraries.mak

LOCAL_DEFINES = -DPEGASUS_INTERNALONLY -DPEGASUS_CONSUMER_INTERNAL

PROGRAM = TestDynListener
SOURCES = TestListener.cpp

include $(ROOT)/mak/program.mak

tests:

poststarttests:

run:

