ROOT = ../../../../..
DIR = Pegasus/Server/IndicationService/tests/HandlerTable
include $(ROOT)/mak/config.mak
include ../libraries.mak

EXTRA_INCLUDES = $(SYS_INCLUDES)

PROGRAM = HandlerTable

SOURCES = HandlerTable.cpp

include $(ROOT)/mak/program.mak

tests:
	HandlerTable

poststarttests:
