ROOT = ../../../../..
DIR = Pegasus/Common/tests/ParamValue
include $(ROOT)/mak/config.mak
include ../libraries.mak

LOCAL_DEFINES = -DPEGASUS_INTERNALONLY

PROGRAM = TestParamValue

SOURCES = ParamValue.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)

poststarttests:

