ROOT = ../../../..
include ../../libraries.mak

DIR = Providers/generic/ShutdownProvider

include $(ROOT)/mak/config.mak

LIBRARY = ShutdownProvider

LIBRARIES = \
	 pegcommon \
	 pegprovider \
	 pegprovider2 \
	 pegrepository \
	 pegserver
	
SOURCES = \
   ShutdownProvider.cpp

include $(ROOT)/mak/library.mak

tests:
