ROOT = ../../..

DIR = Providers/statistic

include $(ROOT)/mak/config.mak

LIBRARY = IBM_CIMOMStatDataProvider

LIBRARIES = \
	pegcommon \
	pegprovider

SOURCES = \
	IBM_CIMOMStatDataProvider.cpp \
	IBM_CIMOMStatDataProviderMain.cpp

include $(ROOT)/mak/library.mak
