ROOT = ../../../../..
DIR = Pegasus/Common/tests/Queue
include $(ROOT)/mak/config.mak
include ../libraries.mak

PROGRAM = TestQueue
SOURCES = Queue.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)

poststarttests:

