ROOT = ../../../../..
DIR = Pegasus/Common/tests/XmlPrint
include $(ROOT)/mak/config.mak
include ../libraries.mak

PROGRAM = TestXmlPrint

SOURCES = XmlPrint.cpp

include $(ROOT)/mak/program.mak

tests:

poststarttests:
