ROOT = ../../../../../..

DIR = Pegasus/Security/Authentication/tests/LocalAuthenticationHandler

LOCAL_DEFINES = -DPEGASUS_COMMON_INTERNAL 

include $(ROOT)/mak/config.mak

include ../libraries.mak


PROGRAM = LocalAuthenticationHandler

SOURCES = LocalAuthenticationHandler.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)
