ROOT = ../../../../../..

DIR = Pegasus/Security/Authentication/tests/LocalAuthenticationHandler

include $(ROOT)/mak/config.mak

include ../libraries.mak

PROGRAM = TestLocalAuthenticationHandler

SOURCES = LocalAuthenticationHandler.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)
