ROOT = ../../../../..

include libraries.mak

DIR = Pegasus/Server/tests/DisplayConsumer

include $(ROOT)/mak/config.mak

LOCAL_DEFINES = -DPEGASUS_PROVIDER_INTERNAL

SOURCES = DisplayConsumer.cpp

LIBRARY = DisplayConsumer
 
include $(ROOT)/mak/library.mak

tests:
