ROOT = ../../../..

include $(ROOT)/mak/config.mak
include $(ROOT)/test/config.mak

XMLSCRIPTS = EnumerateInstanceNames50000 EnumerateInstanceNames50001 EnumerateInstanceNames50002

include $(ROOT)/test/configend.mak
