ROOT = ../../../../..
DIR = Pegasus/Common/tests/WebServer
include $(ROOT)/mak/config.mak
include ../libraries.mak

PROGRAM = WebServer
SOURCES = WebServer.cpp

include $(ROOT)/mak/program.mak

tests:
