ROOT=../..

include $(ROOT)/mak/config.mak

DIRS = \
    Common \
    Config \
    Repository \
    getoopt \
    Compiler \
    Compiler/load \
    Compiler/cmdline \
    Client \
    ExportClient \
    Provider \
    Provider2 \
    ExportServer \
    Security/UserManager \
    Security/Authentication \
    WQL \
    Subscription \
    Server \
    Handler/CIMxmlIndicationHandler \
    Handler/sendmailIndicationHandler \
    Handler/snmpIndicationHandler \
    Common/tests \
    Config/tests \
    Repository/tests \
    Server/tests \
    ExportServer/tests \
    Client/tests \
    Compiler/tests

#    Subscription/tests \

include $(ROOT)/mak/recurse.mak
