ROOT = $(PEGASUS_ROOT)
DIR = Executor/Executor/tests/TestStrlcpy

include $(ROOT)/mak/config.mak

PROGRAM = TestStrlcpy
SOURCES = TestStrlcpy.c
EXTRA_INCLUDES += -I../../..

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)

poststarttests:
