ROOT = ../../../..

include ../libraries.mak

DIR = Pegasus/Handler/CIMxmlIndicationHandler

include $(ROOT)/mak/config.mak

LOCAL_DEFINES = -DPEGASUS_HANDLER_INTERNAL -DPEGASUS_INTERNALONLY

SOURCES = CIMxmlIndicationHandler.cpp

LIBRARY = CIMxmlIndicationHandler
 
include $(ROOT)/mak/library.mak

tests:
