ROOT = ../../../../..
DIR = Pegasus/Common/tests/Match
include $(ROOT)/mak/config.mak
include ../libraries.mak

LOCAL_DEFINES = -DPEGASUS_INTERNALONLY

PROGRAM = TestMatch
SOURCES = Match.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)
