ROOT = ../../..

DIR = Pegasus/Provider

include $(ROOT)/mak/config.mak

INCLUDES = -I..

LOCAL_DEFINES = -DPEGASUS_PROVIDER_INTERNAL

LIBRARIES = pegcommon

LIBRARY = pegprovider

SOURCES = \
    ProviderHandle.cpp \
    CIMProviderHandle.cpp \
    CIMProvider.cpp

include $(ROOT)/mak/library.mak
