ROOT = $(PEGASUS_ROOT)

DIR = Clients/Cimpls
include $(ROOT)/mak/config.mak


LIBRARIES = pegclient pegcommon
PROGRAM = cimpls
SOURCES = Cimpls.cpp

include $(ROOT)/mak/program.mak

tests:

poststarttests:
