ROOT = $(PEGASUS_ROOT)

DIR = Clients/Cimpls
include $(ROOT)/mak/config.mak


LIBRARIES = \
    pegcliutils \
    pegclient \
    peggetoopt \
    pegconfig \
    pegcommon

PROGRAM = cimpls
SOURCES = Cimpls.cpp

include $(ROOT)/mak/program.mak

tests:

poststarttests:
