ROOT = ../../..

DIR = Pegasus/suballoc

include $(ROOT)/mak/config.mak

LOCAL_DEFINES = -DPEGASUS_SUBALLOC_INTERNAL 

LIBRARY = peg_suballoc

#LIBRARIES = \
#    pegcommon

SOURCES = \
	suballoc.cpp
include $(ROOT)/mak/library.mak
