ROOT = ../../../../..
DIR = Pegasus/Common/tests/MessageQueueService
include $(ROOT)/mak/config.mak
include ../libraries.mak

PROGRAM = MessageQueueService
SOURCES = MessageQueueServicet.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)

poststarttests:

