
ROOT = ../../../..
include $(ROOT)/mak/config.mak
include $(ROOT)/test/config.mak

XMLSCRIPTS = CreateInstance53000 CreateInstance53001 CreateInstance53002 CreateInstance53003 CreateInstance53004 CreateInstance53005 CreateInstance53006 CreateInstance53007 CreateInstance53008 CreateInstance53009 CreateInstance53010 CreateInstance53011 CreateInstance53012 CreateInstance53013 CreateInstance53014 CreateInstance53015 

clean:
	$(RM) $(XMLRESPONSES)


tests: $(XMLRESPONSES)
