
ROOT = ../../../..
include $(ROOT)/mak/config.mak
include $(ROOT)/test/config.mak

XMLSCRIPTS = CreateInstance53000 CreateInstance53001 CreateInstance53002 CreateInstance53003 CreateInstance53004 CreateInstance53005 CreateInstance53006 CreateInstance53007 CreateInstance53008 CreateInstance53009 CreateInstance53010 CreateInstance53011 CreateInstance53012 CreateInstance53013 CreateInstance53014 CreateInstance53015 CreateInstance53016 CreateInstance53017 CreateInstance53018 CreateInstance53019 CreateInstance53020 CreateInstance53021 CreateInstance53022 CreateInstance53023 CreateInstance53024 CreateInstance53025 CreateInstance53026 CreateInstance53027 CreateInstance53028 CreateInstance53029 CreateInstance53030 CreateInstance53031 CreateInstance53032 CreateInstance53033 CreateInstance53034 CreateInstance53035

clean:
	$(RM) $(XMLRESPONSES)


tests: $(XMLRESPONSES)
