ROOT = ../../../../..
DIR = Pegasus/Common/tests/Compare
include $(ROOT)/mak/config.mak
include ../libraries.mak

PROGRAM = Compare
SOURCES = Compare.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)
