ROOT = ../../../../..
DIR = Pegasus/Listener/tests/TestListener
include $(ROOT)/mak/config.mak
include ../libraries.mak

PROGRAM = TestListener
SOURCES = TestListener.cpp

include $(ROOT)/mak/program.mak

tests:

run:
	$(PROGRAM)
