ROOT = ../../../../../..
DIR = Pegasus/Security/Authentication/tests/LocalAuthUtils

LOCAL_DEFINES = -DPEGASUS_COMMON_INTERNAL 

include $(ROOT)/mak/config.mak
include ../libraries.mak


PROGRAM = LocalAuthUtilsTest
SOURCES = LocalAuthUtilsTest.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)
