include $(PEGASUS_ROOT)/mak/config.mak

DIR = Providers/TestProviders/ProcessIndicationProvider

LIBRARY = ProcessIndicationProvider

LIBRARIES = \
	pegcommon \
	pegprovider
	
SOURCES = \
	ProcessIndicationProviderMain.cpp \
	ProcessIndicationProvider.cpp

include $(PEGASUS_ROOT)/mak/dynamic-library.mak
install:
