include $(PEGASUS_ROOT)/mak/config.mak

DIR = Providers/TestProviders/ProcessIndicationProvider

LIBRARY = ProcessIndicationProvider

LIBRARIES = \
    pegprovider \
    pegclient \
    pegcommon
	
SOURCES = \
	ProcessIndicationProviderMain.cpp \
	ProcessIndicationProvider.cpp

include $(PEGASUS_ROOT)/mak/dynamic-library.mak
install:
