ROOT = $(PEGASUS_ROOT)

DIR = Providers/AssociationTest/AssociationTestProvider

include $(ROOT)/mak/config.mak

LIBRARY = AssociationTestProvider

LIBRARIES = \
	pegprovider \
	pegcommon
	
SOURCES = \
	AssociationTestProviderMain.cpp \
	AssociationTestProvider.cpp

include $(ROOT)/mak/library.mak

tests:
