ROOT = ../../../../..
DIR = Pegasus/Common/tests/Parameter
include $(ROOT)/mak/config.mak
include ../libraries.mak

PROGRAM = Parameter
SOURCES = Parameter.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)
