ROOT = $(PEGASUS_ROOT)

DIR = Clients/Cimop
include $(ROOT)/mak/config.mak


LIBRARIES = \
    pegcliutils \
    pegclient \
    peggetoopt \
    pegcommon

PROGRAM = cimop
SOURCES = Cimop.cpp

include $(ROOT)/mak/program.mak

tests:

poststarttests:
install:
