ROOT = $(PEGASUS_ROOT)

DIR = Clients/Cimop
include $(ROOT)/mak/config.mak


LIBRARIES = pegclient pegcommon
PROGRAM = cimop
SOURCES = Cimop.cpp

include $(ROOT)/mak/program.mak

tests:

poststarttests:
