ROOT = ../../../../..
DIR = Pegasus/Client/tests/EnumInstNames
include $(ROOT)/mak/config.mak
include ../libraries.mak

EXTRA_INCLUDES = $(SYS_INCLUDES)

PROGRAM = EnumInstNames

SOURCES = EnumInstNames.cpp

include $(ROOT)/mak/program.mak

tests:
