ROOT = ../../../..

include $(ROOT)/mak/config.mak

DIRS = 	ClientServer \
	ProviderTable \
	MyProvider \
	LoadProcessClass \
	HandlerTable \
	SendMailIndicationDispatcher \
	XmlIndicationDispatcher

include $(ROOT)/mak/recurse.mak
