ROOT = ../../../..

include $(ROOT)/mak/config.mak

DIRS = 	ProviderTable \
	MyProvider \
	LoadProcessClass \
	SendMailIndicationDispatcher \
	XmlIndicationDispatcher

# Removed while queuing rework is being completed.
#	HandlerTable \

include $(ROOT)/mak/recurse.mak
