ROOT = ../../../..

include $(ROOT)/mak/config.mak

DIRS = 	ProviderTable \
	MyProvider \
	LoadProcessClass \
	SendMailIndicationDispatcher \
	XmlIndicationDispatcher \
        DisplayConsumer

include $(ROOT)/mak/recurse.mak
