// ===================================================================
// Title:       Master MOF
// Filename:    CIM_Schema26.mof
// Version:     2.6.1
// Release:     0
// Date:        8/02/2001
// Description: This is overall Schema 
// ===================================================================
// Author     : DMTF Technical Committee
// ===================================================================
// Copyright "2001" Distributed Management Task Force, Inc. (DMTF).
// All rights reserved.  
// DMTF is a not-for-profit association of industry members dedicated 
// to promoting enterprise and systems management and interoperability. 
// DMTF specifications and documents may be reproduced for uses
// consistent with this purpose by members and non-members, 
// provided that correct attribution is given. 
// As DMTF specifications may be revised from time to time, 
// the particular version and release cited should always be noted.
// ===================================================================
// includes
// ===================================================================
#pragma include ("CIM_Core26.mof")
#pragma include ("CIM_Events26.mof")
#pragma include ("CIM_User26.mof")
#pragma include ("CIM_Policy26.mof")
#pragma include ("CIM_Application26.mof")
#pragma include ("CIM_System26.mof")
#pragma include ("CIM_Device26.mof")
#pragma include ("CIM_Physical26.mof")
#pragma include ("CIM_Network26.mof")
#pragma include ("CIM_Metrics26.mof")
#pragma include ("CIM_Support26.mof")
#pragma include ("CIM_Interop26.mof")





