// ==================================================================
// Title:       System MOF Specification Additions_2 for 2.6
// Filename:    CIM_System26_Add2.MOF
// Version:     2.6
// Date:        06/12/2001
// Release:     Preliminary
// Description: The object classes below are new to the version stated 
//              above and are being evaluated in premliminary release 
//              status.  These additions are specific to the area of
//              a UNIX environment.
// ===================================================================
// Copyright "2001" Distributed Management Task Force, Inc. (DMTF).
// All rights reserved.  
// DMTF is a not-for-profit association of industry members dedicated 
// to promoting enterprise and systems management and interoperability. 
// DMTF specifications and documents may be reproduced for uses
// consistent with this purpose by members and non-members, 
// provided that correct attribution is given. 
// As DMTF specifications may be revised from time to time, 
// the particular version and release cited should always be noted.
//
// UNIX is a registered trademark of the Open Group.
// ===================================================================
// Author: DMTF System and Devices Working Group
// ===================================================================
//  - CR608, Initial Unix Environment Model
// ===================================================================

// ===================================================================
//  CIM_UnixLocalFileSystem
// ===================================================================
   [Description (
     "A class derived from LocalFileSystem that represents the Unix "
     "environment view of a file store controlled by a ComputerSystem "
     "through local means (e.g., direct device driver access). In "
     "this case, the file store is managed directly by the "
     "ComputerSystem without the need for another computer to act "
     "as a file server. This definition does not breakdown in the " 
     "case of a Clustered File System. In this scenario, the " 
     "FileSystem is a LocalFileSystem, weak to the Cluster.") ]
class CIM_UnixLocalFileSystem : CIM_LocalFileSystem {
      [Description (
        "The number of free inodes present in the file system.  "
        "This value is only valid if TotalSlots is non-zero."),
       MappingStrings{"MIF.DMTF|Host File System|001.12"} ]
   uint64 FreeSlots;
      [Description (
        "The total number of inodes available in the file system.  "
        "A value of zero for TotalSlots indicates that this file "
        "system does not have a preset limit."),
       MappingStrings{"MIF.DMTF|Host File System|001.11"} ]
   uint64  TotalSlots;
      [Description (
        "The reserve data capacity of the file system in bytes."),
       MappingStrings{"MIF.DMTF|Host File System|001.15"},
       Units("Bytes") ]
   uint64 ReservedCapacity;
};


// ===================================================================
//  CIM_UnixProcess
// ===================================================================
   [Description (
     "Each instance of the CIM_UnixProcess class represents a single "
     "instance of a running program. A user of the Operating System "
     "will typically see a Process as an application or task. Within "
     "an OperatingSystem, a Process is defined by a workspace of "
     "memory resources and environmental settings that are allocated "
     "to it. On a multitasking System, this workspace prevents "
     "intrusion of resources by other Processes. Additionally, a "
     "Process can execute as multiple Threads, all which run within "
     "the same workspace.") ]
class CIM_UnixProcess : CIM_Process {
      [Description (
        "The parent process ID of this executing process."),
       MappingStrings{"MIF.DMTF|Process Information|001.2"} ]
   string ParentProcessID;
      [Description (
        "The Real User ID of this currently executing process."),
       MappingStrings{"MIF.DMTF|Process Information|001.4"} ]
   uint64 RealUserID = 0;
      [Description (
        "The Group ID of this currently executing process."),
       MappingStrings{"MIF.DMTF|Process Information|001.2"} ]
   uint64 ProcessGroupID = 0;
      [Description (
        "The ID of a group of processes under the control of a session "
        "leader.") ]
   uint64 ProcessSessionID = 0;
      [Description (
        "The TTY currently associated with this process."),
       MappingStrings{"MIF.DMTF|Process Information|001.5"} ]
   string ProcessTTY;
      [Description (
        "The executing process' command path."),
       MappingStrings{"MIF.DMTF|Process Information|001.7"} ]
   string ModulePath;
      [Description (
        "The operating system parameters provided to the executing "
        "process."),
       MappingStrings{"MIF.DMTF|Process Information|001.8"} ]
   string Parameters[];
      [Description (
        "The process's 'nice' value.  Used to compute its priority."),
       MappingStrings{"MIF.DMTF|Process Information|001.11"} ]
   uint32 ProcessNiceValue = 0;
      [Description (
        "The percentage of a CPU's time this process is consuming."),
       MappingStrings{"MIF.DMTF|Process Information|001.12"} ]
   uint32 ProcessCPUTime = 0;
      [Description (
        "The number of Kbytes of real text space used by the process."),
       MappingStrings{"MIF.DMTF|Process Information|001.15"},
       Units("KBytes") ]
   uint64 ProcessRealText = 0;
      [Description (
        "The number of Kbytes real data space used by the process."),
       MappingStrings{"MIF.DMTF|Process Information|001.16"},
       Units("KBytes") ]
   uint64 ProcessRealData = 0;
      [Description (
        "The number of Kbytes real stack space used by the process."),
       MappingStrings{"MIF.DMTF|Process Information|001.17"},
       Units("KBytes") ]
   uint64 ProcessRealStack = 0;
      [Description (
        "The number of Kbytes of virtual text space used by the "
        "process."),
       MappingStrings{"MIF.DMTF|Process Information|001.18"},
       Units("KBytes") ]
   uint64 ProcessVirtualText = 0;
      [Description (
        "The number of Kbytes of virtual data space used by the "
        "process."),
       MappingStrings{"MIF.DMTF|Process Information|001.19"},
       Units("KBytes") ]
   uint64 ProcessVirtualData = 0;
      [Description (
        "The number of Kbytes of virtual stack space used by the "
        "process."),
       MappingStrings{"MIF.DMTF|Process Information|001.20"},
       Units("KBytes") ]
   uint64 ProcessVirtualStack = 0;
      [Description (
        "The number of Kbytes of virtual shared memory used by the "
        "process."),
       MappingStrings{"MIF.DMTF|Process Information|001.22"},
       Units("KBytes") ]
   uint64 ProcessVirtualMemoryMappedFileSize   = 0;
      [Description (
        "The number of Kbytes of virtual space used for memory mapped "
        "files by the process."),
       MappingStrings{"MIF.DMTF|Process Information|001.21"},
       Units("KBytes") ]
   uint64 ProcessVirtualSharedMemory = 0;
      [Description (
        "A description of the event this process is currently sleeping "
        "for.  The precise nature of this string is implementation defined, "
        "but is typically the address of a system data structure that "
        "will be modified when the event occurs.  This string only has "
        "meaning when the ExecutionState is \"Blocked\" or "
        " \"SuspendedBlocked\".") ]
   string ProcessWaitingForEvent;
      [Description (
        "CPU time of terminated child processes in clock ticks")]
   uint64 CpuTimeDeadChildren;
      [Description (
        "System time of terminated child processes in clock ticks")]
   uint64 SystemTimeDeadChildren;
};


// ===================================================================
// CIM_UnixThread
// ===================================================================
class CIM_UnixThread : CIM_Thread {
      [Description (
        "Indicates the thread's scheduling policy."),
       Values{"SCHED_FIFO", "SCHED_RR", "SCHED_OTHER"} ]
   uint16 SchedPolicy;
      [Description (
        "Indicates the size of the guard area for a created thread's "
        "stack.") ]
   string GuardSize;
      [Description (
        "Indicates the creation state of the thread."),
       Values{"PTHREAD_CREATE_DETACHED", "PTHREAD_CREATE_JOINABLE"} ]
   uint16 DetachState;
      [Description (
        "Indicates how the scheduling attributes are to be set"),
       Values{"PTHREAD_INHERIT_SCHED", "PTHREAD_EXPLICIT_SCHED"} ]
   uint16 InheritSched;
      [Description (
        "Indicates the contention scope of the thread"),
       Values{"PTHREAD_SCOPE_SYSTEM", "PTHREAD_SCOPE_PROCESS"} ]
   uint16 ContentionScope;
      [Description (
        "Indicates the size of storage to be used for the thread's "
        "stack.") ]
   string StackSize;
      [Description (
        "Indicates the thread's concurrency level.") ]
   uint64 ConcurrencyLevel;
      [Description (
        "Indicates the thread's cancelability state"),
       Values{"PTHREAD_CANCEL_ENABLE", "PTHREAD_CANCEL_DISABLE"} ]
   uint16 CancelState;
      [Description (
        "Indicates the thread's cancelability type"),
       Values{"PTHREAD_CANCEL_DEFERRED", "PTHREAD_CANCEL_ASYNCHRONOUS"} ]
   uint16 CancelType;
};


// ===================================================================
//  CIM_UnixFile
// ===================================================================
   [Association, Aggregation, Description (
     "Properities that are associated with various sub-classes "
     "of LogicalFile in a Unix environment.  This "
     "class should have a FileIdentity relationship to the "
     "appropriate sub-class of Logical File.")]
class CIM_UnixFile : CIM_LogicalElement {
      [Description ("An Identifer that uniquely describes the owner "
        "of this file.")] 
   string  Uid;
      [Description ("An identifier that describes the group that "
        "owns this file.") ] 
   string  Gid;
      [Description ("Indicates restricted deletion for directories, "
        "or possible implementation defined properties for executable "
        "files") ] 
   boolean SaveText;
      [Description ("Count of the number of names this file has." ) ] 
   string LinkCount;
      [Description ("File Inode number, as printed by \"ls -i\"") ] 
   string FileInodeNumber;
      [Description ("Tells if the associated file has setuid "
        "permissions.") ]
   boolean SetUid;
      [Description ("Tells if the associated file has setgid "
        "permissions.") ]
   boolean SetGid;
      [Description ("The time that the Inode was last modified.")]
   datetime  LastModifiedInode;
      [Description ("Minimum number of bits needed to represent, as a "
        "signed integer value, the maximum size of a regular file "
        "allowed in the specified directory. Minimum Acceptable "
        "Value: 32 pathconf returns this variable when "
        "_PC_FILESIZEBITS is passed to it.") ]
   uint64 FileSizeBits; 
      [Description ("Maximum number of links to a single file.  "
        "Minimum Acceptable Value: _POSIX_LINK_MAX(8).  "
        "pathconf returns this variable when _PC_LINK_MAX is passed "
        "to it.") ]
   uint64 LinkMax;  
      [Description ("Maximum number of bytes in a filename (not "
        "including terminating null). Minimum Acceptable Value: "
        "_POSIX_NAME_MAX(14) pathconf returns this variable when "
        "_PC_NAME_MAX is passed to it.") ]
   uint64 NameMax; 
      [Description ("Maximum number of bytes in a pathname, including "
        "the terminating null character.  Minimum Acceptable Value: "
        "_POSIX_PATH_MAX(255) pathconf returns this variable when "
        "_PC_PATH_MAX is passed to it.") ]
   uint64 PathMax;  
      [Description ("The use of chown() is restricted to a process "
        "with appropriate privileges, and to changing the group ID of "
        "a file only to the effective group ID of the process or to "
        "one of its supplementary group IDs. It is defined if a value "
        "other than -1 is returned. pathconf returns this variable when "
        "_PC_CHOWN_RESTRICTED is passed to it.") ]
   uint64 PosixChownRestricted; 
      [Description ("Pathname components longer than {NAME_MAX} "
        "generate an error.  Defined if a value other than -1 is "
        "returned.  pathconf returns this variable when _PC_NO_TRUNC "
        "is passed to it.") ]
   uint64 PosixNoTrunc;  
      [Description ("If any of the following three constants are not "
        "defined in the header <unistd.h>, the value varies depending "
        "on the file to which it is applied. If any of the following "
        "constants are defined to have value -1 in the header <unistd.h>, "
        "the implementation will not provide the option on any file; "
        "if any are defined to have a value other than -1 in the header "
        "<unistd.h>, the implementation will provide the option on all "
        "applicable files. All of the following three constants, "
        "whether defined in <unistd.h> or not, may be queried with "
        "respect to a specific file using the pathconf() or fpathconf() "
        "functions. Asynchronous input or output operations may be "
        "performed for the associated file. pathconf returns this "
        "variable when _PC_ASYNC_IO is passed to it.") ]
   uint64 PosixAsyncIo; 
      [Description ("Prioritized input or output operations may be "
       "performed for the associated file. Also see description for "
       "_POSIX_ASYNC_IO.  pathconf returns this variable when "
       "_PC_PRIO_IO is passed to it.") ]
   uint64 PosixPrioIo; 
      [Description ("Synchronised input or output operations may be "
        "performed for the associated file. Also see description for "
        "_POSIX_ASYNC_IO. pathconf returns this variable when "
        "_PC_SYNC_IO is passed to it.") ]
   uint64 PosixSyncIo; 
};


// ===================================================================
//  CIM_FileIdentity
// ===================================================================
   [Association, Description (
     "CIM_FileIdentity is an association indicating that a UnixFile "
     "is describing additional aspects of a Logical File.")]
class CIM_FileIdentity : CIM_LogicalIdentity {
      [Override ("SystemElement"), Description (
        "The Logical File.")]
   CIM_LogicalFile ref SystemElement;
      [Override ("SameElement"), Description (
        "SameElement represents the additional aspects of the "
        "Unix/Linux Logical file.") ]
   CIM_UnixFile ref SameElement;
};


// ===================================================================
//  CIM_UnixDeviceFile
// ===================================================================
   [Description (
     "DeviceFile is a special type of LogicalFile that represents "
     "a Device. This convention is useful for some operating systems "
     "that manage devices using a byte stream I/O model. The Logical"
     "Device that is associated with this file is specified using "
     "the DeviceAccessedByFile relationship.") ]
class CIM_UnixDeviceFile : CIM_DeviceFile {
      [Description ("The type of device file"),
       Values {"Block", "Character", "Other"} ] 
   uint16 Type = 0;
      [Description ("Additional information for type \"Other\"") ] 
   string OtherTypeDescription = "";
      [Description ("The device Identifier: this is the st_rdev field "
        "in the stat structure")] 
   string DeviceId = "";
      [Description ("Additional information provided by the driver "
        "this may be null if no info is available, or a "
        "general description of the device is available, e.g. "
        "\"Non-rewind tape streamer\"") ] 
   string DeviceDescription = "";
      [Description ("The Device's Major Id.")]
   string DeviceMajor;
      [Description ("The Device's Minor Id.")]
   string DeviceMinor;
};


// ===================================================================
//   CIM_NamedPipe
// ===================================================================
   [Description (
     "NamedPipe is a special type of LogicalFile that represents "
     "a pipe. This convention is useful for some operating systems "
     "that manage interprocess communication. ") ]
class CIM_NamedPipe : CIM_LogicalFile {
};


// ===================================================================
//   CIM_UnixSymlink
// ===================================================================
   [Description (
     "UnixSymLink is a special type of LogicalFile that represents "
     "a Symbolic Link. This convention is useful for some operating "
     "systems that want to represent a single file in multiple "
     "places or a single file that is represented via multiple "
     "names.")]
class CIM_UnixSymlink : CIM_LogicalFile {
      [Description ("The target of the symbolic link") ]
   string SymLinkTarget;
};


// ===================================================================
//   CIM_UnixSysconf
// ===================================================================
// Expand on description to be UnixSettings and/or sub classes of...
   [Description (
     "UnixSysConf is used to collect a set of subclasses of Unix"
     "Settings.  Use the SettingContext aggregation to place the "
     "individual settings into the Configuration.") ]
class CIM_UnixSysConf : CIM_Configuration {
};


// ===================================================================
//   CIM_UnixSetting
// ===================================================================
   [Abstract, Description (
     "The UnixSetting class is the base class for the various types "
     "of settings which are associated with a unix system configuration")]
class CIM_UnixSetting : CIM_Setting {
      [Key, MaxLen (256), Description (
        "CreationClassName indicates the name of the class or the "
        "subclass used in the creation of an instance. When used "
        "with the other key properties of this class, this property "
        "allows all instances of this class and its subclasses to "
        "be uniquely identified.") ]
   string CreationClassName;
      [Key, Override ("SettingID"), 
       Description ("The inherited SettingID serves as part of the "
        "key for a CIM_UnixSetting instance.") ] 
    string SettingID;
};


// ===================================================================
//    CIM_UnixSettingContext
// ===================================================================
   [Association, Aggregation, Description (
     "This relationship associates a Unix settings with the Unix "
     "configuration object.") ]
class CIM_UnixSettingContext : CIM_SettingContext {
      [Override ("Context"), Aggregate, Description (
        "The Unix Configuration object that aggregates the Setting.") ]
   CIM_UnixSysConf REF Context;
      [Override ("Setting"), Description ("An aggregated Unix "
       "Setting.") ]
   CIM_UnixSetting REF Setting;
};


// ===================================================================
//   CIM_UnixMiscSetting
// ===================================================================
   [Description (
     "Miscellaneous configuration settings")]
class CIM_UnixMiscSetting : CIM_UnixSetting {
      [Description ("Maximum length of argument to the exec functions "
        "including environment data. Minimum Acceptable Value: "
        "_POSIX_ARG_MAX(4096).  sysconf returns this variable when "
        "_SC_ARG_MAX is passed to it.")]
   uint64 ArgMax; 
      [Description ("Maximum number of simultaneous processes per "
        "real user ID.  Minimum Acceptable Value: 25.  sysconf returns "
        "this variable when _SC_CHILD_MAX is passed to it.")]
   uint64 ChildMax; 
      [Description ("Number of clock ticks per second returned by the "
        "times() function.  sysconf returns this variable when "
        "_SC_CLK_TCK is passed to it.")]
   uint64 ClkTck; 
      [Description ("Maximum number of weights that can be assigned "
        "to an entry of the LC_COLLATE order keyword in the locale "
        "definition file; see the XBD specification, Locale. Minimum "
        "Acceptable Value: _POSIX2_COLL_WEIGHTS_MAX(2).  sysconf "
        "returns this variable when _SC_COLL_WEIGHTS_MAX is passed "
        "to it.")]
   uint64 CollWeightsMax; 
      [Description ("The maximum length, in bytes, of a utility's "
        "input line (either standard input or another file), when the "
        "utility is described as processing text files. The length "
        "includes room for the trailing newline. Minimum Acceptable "
        "Value: _POSIX2_LINE_MAX(2048) sysconf returns this variable "
        "when _SC_LINE_MAX is passed to it.")]
   uint64 LineMax; 
      [Description ("Maximum number of repeated occurrences of a "
        "regular expression permitted when using the interval "
        "notation {m,n}; see the XBD specification, Regular Expressions. "
        "Minimum Acceptable Value: POSIX2_RE_DUP_MAX(255) sysconf "
        "returns this variable when _SC_RE_DUP_MAX is passed to it.")]
   uint64 ReDupMax; 
      [Description ("Maximum number of bytes supported for the name "
        "of a time zone (not of the TZ variable). Minimum Acceptable "
        "Value: _POSIX_TZNAME_MAX(3) sysconf returns this variable "
        "when _SC_TZNAME_MAX is passed to it.")]
   uint64 TZNameMax; 
      [Description ("Maximum number of significant bytes in a password "
        "(not including terminating null). (LEGACY) Minimum Acceptable "
        "Value: 8 sysconf returns this variable when _SC_PASS_MAX is "
        "passed to it.")]
   uint64 PassMax;     
      [Description ("Maximum number of functions that may be registered "
        "with atexit(). Minimum Acceptable Value: 32 sysconf returns this "
        "variable when _SC_ATEXIT_MAX is passed to it.")]
   uint64 AtexitMax; 
      [Description ("Size in bytes of a page. Minimum Acceptable Value: "
        "1 sysconf returns this variable when _SC_PAGESIZE is passed "
        "to it.")]
   uint64 PageSize; 
      [Description ("Same as PAGESIZE. If either PAGESIZE or PAGE_SIZE "
        "is defined, the other will be defined with the same value.  "
        "sysconf returns this variable when _SC_PAGE_SIZE is passed "
        "to it.")]
   uint64 PAGE_SIZE; 
      [Description ("Maximum number of timer expiration overruns. "
        "Minimum Acceptable Value: _POSIX_DELAYTIMER_MAX(32) sysconf "
        "returns this variable when _SC_DELAYTIMER_MAX is passed to it.")]
   uint64 DelayTimerMax; 
      [Description ("The maximum number of message priorities "
        "supported by the implementation. Minimum Acceptable Value: "
        "_POSIX_MQ_PRIO_MAX(32) sysconf returns this variable when "
        "_SC_MQ_PRIO_MAX is passed to it.")]
   uint64 MqPrioMax; 
      [Description ("Maximum number of realtime signals reserved for "
        "application use in this implementation. Minimum Acceptable "
        "Value: _POSIX_RTSIG_MAX(8) sysconf returns this variable "
        "when _SC_RTSIG_MAX is passed to it.")]
   uint64 RtsigMax; 
      [Description ("The maximum value a semaphore may have.  Minimum "
        "Acceptable Value: _POSIX_SEM_VALUE_MAX(32767) sysconf returns "
        "this variable when _SC_SEM_VALUE_MAX is passed to it.")]
   uint64 SemValueMax; 
      [Description ("Maximum size of group entry buffer.  sysconf "
        "returns this variable when _SC_GETGR_R_SIZE_MAX is passed "
        "to it.")]
   uint64 NssBufLenGroup; 
      [Description ("Maximum size of password entry buffer.  sysconf "
        "returns this variable when _SC_GETPW_R_SIZE_MAX is passed "
        "to it.")]
   uint64 NssBufLenPassWd; 
      [Description ("Maximum length of a login name. Minimum "
        "Acceptable Value: _POSIX_LOGIN_NAME_MAX(9) sysconf returns "
        "this variable when _SC_LOGIN_NAME_MAX is passed to it.")]
   uint64 LoginNameMax; 
      [Description ("Maximum length of terminal device name. Minimum "
        "Acceptable Value: _POSIX_TTY_NAME_MAX(9) sysconf returns this "
        "variable when _SC_TTY_NAME_MAX is passed to it.")]
   uint64 TtyNameMax; 
};


// ===================================================================
//   CIM_UnixProcessSetting
// ===================================================================
   [Description (
     "Per process configuration settings")]
class CIM_UnixProcessSetting : CIM_UnixSetting {
      [Description ("Maximum number of simultaneous supplementary "
        "group IDs per process. Minimum Acceptable Value: 8 "
        "sysconf returns this variable when _SC_NGROUPS_MAX is "
        "passed to it.") ]
   uint64 NGroupsMax;  
      [Description ("The number of streams that one process can have "
        "open at one time. If defined, it has the same value as "
        "{FOPEN_MAX} (see <stdio.h>). Minimum Acceptable Value: "
        "_POSIX_STREAM_MAX(8) sysconf returns this variable when "
        "_SC_STREAM_MAX is passed to it.") ]
   uint64 StreamMax; 
      [Description ("Maximum number of files that one process can "
        "have open at any one time. Minimum Acceptable Value: 20 "
        "sysconf returns this variable when _SC_OPEN_MAX is passed "
        "to it.") ]
   uint64 OpenMax; 
      [Description ("Maximum number of iovec structures that one "
        "process has available for use with readv() or writev(). "
        "Minimum Acceptable Value: _XOPEN_IOV_MAX(16) sysconf returns "
        "this variable when _SC_IOV_MAX is passed to it.") ]
   uint64 IovMax; 
      [Description ("The maximum number of open message queue "
        "descriptors a process may hold. Minimum Acceptable Value: "
        "_POSIX_MQ_OPEN_MAX(8) sysconf returns this variable when "
        "_SC_MQ_OPEN_MAX is passed to it.") ]
   uint64 MqOpenMax; 
      [Description ("Maximum number of semaphores that a process may "
        "have.  Minimum Acceptable Value: _POSIX_SEM_NSEMS_MAX(256) "
        "sysconf returns this variable when _SC_SEM_NSEMS_MAX is passed "
        "to it.") ]
   uint64 SemNsemsMax; 
      [Description ("Maximum number of queued signals that a process "
        "may send and have pending at the receiver(s) at any time. "
        "Minimum Acceptable Value: _POSIX_SIGQUEUE_MAX(32) sysconf "
        "returns this variable when _SC_SIGQUEUE_MAX is passed to it.") ]
   uint64 SegqueueMax; 
      [Description ("Maximum number of timers per-process supported "
        "by the implementation.  Minimum Acceptable Value: "
        "_POSIX_TIMER_MAX(32) sysconf returns this variable when "
        "_SC_TIMER_MAX is passed to it.") ]
   uint64 TimerMax; 
      [Description ("Maximum number of data keys that can be created "
        "by a process.  Minimum Acceptable Value: "
        "_POSIX_THREAD_KEYS_MAX(128) sysconf returns this variable when "
        "_SC_THREAD_KEYS_MAX is passed to it.") ]
   uint64 PthreadKeysMax; 
      [Description ("Maximum number of threads that that can be "
        "created per process.  Minimum Acceptable Value: "
        "_POSIX_THREAD_THREADS_MAX(64) sysconf returns this variable "
        "when _SC_THREAD_THREADS_MAX is passed to it.") ]
   uint64 PthreadThreadsMax; 
};


// ===================================================================
//   CIM_UnixAppSetting
// ===================================================================
   [Description (
     "Application specific configuration settings.")]
class CIM_UnixAppSetting : CIM_UnixSetting {
      [Description ("Maximum base values allowed by the bc utility.  "
        "Minimum Acceptable Value: _POSIX2_BC_BASE_MAX(99). sysconf "
        "returns this variable when _SC_BASE_MAX is passed to it.") ]
   uint64 BcBaseMax; 
      [Description ("Maximum number of elements permitted in an array "
        "by the bc utility.  Minimum Acceptable Value: "
        "_POSIX2_BC_DIM_MAX(2048). sysconf returns this variable when "
        "_SC_BC_DIM_MAX is passed to it.") ]
   uint64 BcDimMax; 
      [Description ("Maximum scale value allowed by the bc utility.  "
        "Minimum Acceptable Value: _POSIX2_BC_SCALE_MAX(99). sysconf "
        "returns this variable when _SC_BC_SCALE_MAX is passed to it.") ]
   uint64 BcScaleMax;
      [Description ("Maximum length of a string constant accepted by "
        "the bc utility. Minimum Acceptable Value: "
        "_POSIX2_BC_STRING_MAX(1000). sysconf returns this variable "
        "when _SC_BC_STRING_MAX is passed to it.") ]
   uint64 BcStringMax; 
      [Description ("Maximum number of expressions that can be nested "
        "within parentheses by the expr utility. Minimum Acceptable "
        "Value: _POSIX2_EXPR_NEST_MAX(32) sysconf returns this variable "
        "when _SC_EXPR_NEST_MAX is passed to it.") ]
   uint64 ExprNestMax; 
};


// ===================================================================
//   CIM_UnixThreadSetting
// ===================================================================
   [Description (
     "Thread specific configuration settings")]
class CIM_UnixThreadSetting : CIM_UnixSetting {
      [Description ("Maximum number of attempts made to destroy a "
        "thread's thread-specific data values on thread exit. Minimum "
        "Acceptable Value: _POSIX_THREAD_DESTRUCTOR_ITERATIONS(4) "
        "sysconf returns this variable when _SC_THREAD_DESTRUCTOR_"
        "ITERATION is passed to it.") ]
   uint64 PthreadDestructorIterations; 
      [Description ("Minimum size in bytes of thread stack storage. "
        "Minimum Acceptable Value: 0 sysconf returns this variable "
        "when _SC_THREAD_STACK_MIN is passed to it.") ]
   uint64 PthreadStackMin; 
};


// ===================================================================
//   CIM_UnixIoIpcSetting
// ===================================================================
   [Description (
     "IO and IPC specific configuration settings.")]
class CIM_UnixIoIpcSetting : CIM_UnixSetting {
      [Description ("Maximum number of I/O operations in a single "
        "list I/O call supported by the implementation. Minimum "
        "Acceptable Value: _POSIX_AIO_LISTIO_MAX(2) sysconf returns "
        "this variable when _SC_AIO_LISTIO_MAX is passed to it.") ]
   uint64 AioListioMax; 
      [Description ("Maximum number of outstanding asynchronous I/O "
        "operations supported by the implementation. Minimum Acceptable "
        "Value: _POSIX_AIO_MAX(1) sysconf returns this variable when "
        "_SC_AIO_MAX is passed to it.") ]
   uint64 AioMax; 
      [Description ("Maximum amount by which a process can decrease "
        "its asynchronous I/O priority level from its own scheduling "
        "priority.  sysconf returns this variable when _SC_AIO_PRIO_"
        "DELTA_MAX is passed to it.") ]
   uint64 AioPrioDeltaMax; 
      [Description ("Maximum number of bytes in a terminal canonical "
        "input queue.  Minimum Acceptable Value: _POSIX_MAX_CANON(255).  "
        "pathconf returns this variable when _PC_MAX_CANON is passed "
        "to it.") ]
   uint64 MaxCanon; 
      [Description ("Minimum number of bytes for which space will be "
        "available in a terminal input queue; therefore, the maximum "
        "number of bytes a portable application may require to be typed "
        "as input before reading them. Minimum Acceptable Value: "
        "_POSIX_MAX_INPUT(255). pathconf returns this variable when "
        "_PC_MAX_INPUT is passed to it.") ]
   uint64 MaxInput; 
      [Description ("Maximum number of bytes that is guaranteed to be "
        "atomic when writing to a pipe. Minimum Acceptable Value: "
        "_POSIX_PIPE_BUF(512) pathconf returns this variable when "
        "_PC_PIPE_BUF is passed to it.") ]
   uint64 PipeBuf; 
      [Description ("Terminal special characters defined in <termios.h> "
        "can be disabled using this character value. Defined if a "
        "value other than -1 is returned. pathconf returns this "
        "variable when _PC_VDISABLE is passed to it.") ]
   uint64 PosixVdisable; 
};


// ===================================================================
//   CIM_UnixFeatureSetting
// ===================================================================
   [Description (
     "Configuration settings indicating extent of support for various "
     "features.")]
class CIM_UnixFeatureSetting : CIM_UnixSetting {
      [Description ("Implementation supports the C Language Development "
        "Utilities option.  A value of -1 indicates that the "
        "implementation will never provide the feature and any other "
        "value indicates that the implementation will always provide "
        "the feature. sysconf returns this variable when _SC_2_C_DEV "
        "is passed to it.") ]
   uint64 Posix2CDev; 
      [Description ("Integer value indicating version of the ISO "
        "POSIX-2 standard (C language binding).  sysconf returns this "
        "variable when _SC_2_C_VERSION is passed to it.") ]
   uint64 Posix2CVersion; 
      [Description ("Implementation supports at least one terminal "
        "type. A value of -1 indicates that the implementation will "
        "never provide the feature and any other value indicates that "
        "the implementation will always provide the feature.  "
        "sysconf returns this variable when _SC_2_CHAR_TERM is passed "
        "to it.") ]
   uint64 Posix2CharTerm; 
      [Description ("Implementation supports the FORTRAN Development "
        "Utilities option. A value of -1 indicates that the "
        "implementation will never provide the feature and any other "
        "value indicates that the implementation will always provide "
        "the feature.  sysconf returns this variable when _SC_2_FORT_DEV "
        "is passed to it.") ]
   uint64 Posix2FortDev; 
      [Description ("Implementation supports the FORTRAN Run-time "
        "Utilities option.  A value of -1 indicates that the "
        "implementation will never provide the feature and any other "
        "value indicates that the implementation will always provide "
        "the feature. sysconf returns this variable when _SC_2_FORT_RUN "
        "is passed to it.") ]
   uint64 Posix2FortRun; 
      [Description ("Implementation supports the creation of locales "
        "by the localedef utility. A value of -1 indicates that the "
        "implementation will never provide the feature and any other "
        "value indicates that the implementation will always provide "
        "the feature.  sysconf returns this variable when _SC_2_LOCALDEF "
        "is passed to it.") ]
   uint64 Posix2LocalDef; 
      [Description ("Implementation supports the Software Development "
        "Utilities option. A value of -1 indicates that the implementation "
        "will never provide the feature and any other value indicates "
        "that the implementation will always provide the feature.  "
        "sysconf returns this variable when _SC_2_SW_DEV is passed "
        "to it.") ]
   uint64 Posix2SwDev; 
      [Description ("The implementation supports the User Portability "
        "Utilities option. A value of -1 indicates that the implementation "
        "will never provide the feature and any other value indicates "
        "that the implementation will always provide the feature.  "
        "sysconf returns this variable when _SC_2_UPE is passed "
        "to it.") ]
   uint64 Posix2Upe; 
      [Description ("Integer value indicating version of the ISO "
        "POSIX-2 standard (Commands).  sysconf returns this variable "
        "when _SC_2_VERSION is passed to it.") ]
   uint64 Posix2Version; 
      [Description ("If defined with a value other than -1, the system "
        "supports job control sysconf returns this variable when "
        "_SC_JOB_CONTROL is passed to it.") ]
   uint64 PosixJobControl; 
      [Description ("If defined with a value other than -1, each "
        "process has a saved set-user-ID and a saved set-group-ID.  "
        "sysconf returns this variable when _SC_SAVED_IDS is passed "
        "to it.") ]
   uint64 PosixSavedIds; 
      [Description ("Integer value indicating version of the ISO "
      "POSIX-1 standard (C language binding).  sysconf returns this "
      "variable when _SC_VERSION is passed to it.") ]
   uint64 PosixVersion; 
      [Description ("The implementation supports the X/Open Encryption "
        "Feature Group. A value of -1 indicates that the implementation "
        "will never provide the feature and any other value indicates "
        "that the implementation will always provide the feature.  "
        "sysconf returns this variable when _SC_XOPEN_CRYPT is passed "
        "to it.") ]
   uint64 XopenCrypt; 
      [Description ("The implementation supports the Issue 4, Version 2 "
        "Enhanced Internationalisation Feature Group. This is always "
        "set to a value other than -1. A value of -1 indicates that "
        "the implementation will never provide the feature and any "
        "other value indicates that the implementation will always "
        "provide the feature.  sysconf returns this variable when "
        "_SC_XOPEN_ENH_I18N is passed to it.") ]
   uint64 XopenEnhI18n; 
      [Description ("The implementation supports the Issue 4, Version 2 "
        "Shared Memory Feature Group. This is always set to a value "
        "other than -1. A value of -1 indicates that the implementation "
        "will never provide the feature and any other value indicates "
        "that the implementation will always provide the feature.  "
        "sysconf returns this variable when _SC_XOPEN_SHM is passed "
        "to it.") ]
   uint64 XopenShm; 
      [Description ("Integer value indicating version of the X/Open "
        "Portability Guide to which the implementation conforms.  "
        "sysconf returns this variable when _SC_XOPEN_VERSION is passed "
        "to it.") ]
   uint64 XopenVersion; 
      [Description ("_XOPEN_XCU_VERSION is defined as an integer value "
        "indicating the version of the XCU specification to which the "
        "implementation conforms. If the value is -1, no commands and "
        "utilities are provided on the implementation. If the value is "
        "greater than or equal to 4, the functionality associated with the "
        "following symbols is also supported Posix2C_BIND, "
        "Posix2C_VERSION, Posix2CHAR_TERM, Posix2LOCALEDEF, "
        "Posix2UPE, Posix2VERSION, sysconf returns this variable "
        "when _SC_XOPEN_XCU_VERSION is passed to it.") ]
   uint64 XopenXcuVersion; 
      [Description ("The implementation supports the User Portability "
        "Utilities option. A value of -1 indicates that the "
        "implementation will never provide the feature and any other "
        "value indicates that the implementation will always provide "
        "the feature.  sysconf returns this variable when "
        "_SC_XOPEN_REALTIME is passed to it.") ]
   uint64 XopenRealtime; 
      [Description ("The implementation supports the X/Open Realtime "
        "Threads Feature Group. A value of -1 indicates that the "
        "implementation will never provide the feature and any other "
        "value indicates that the implementation will always provide "
        "the feature.  sysconf returns this variable when "
        "_SC_XOPEN_REALTIME_THERADS is passed to it.") ]
   uint64 XopenRealtimeThreads; 
      [Description ("The implementation supports the Legacy Feature "
        "Group. A value of -1 indicates that the implementation will "
        "never provide the feature and any other value indicates that "
        "the implementation will always provide the feature. sysconf "
        "returns this variable when _SC_XOPEN_LEGACY is passed to it.") ]
   uint64 XopenLegacy; 
      [Description ("The implementation supports X/Open CAE Specification, "
        "January 1997, System Interfaces and Headers, Issue 5 (ISBN: "
        "1-85912-181-0, C606).  A value of -1 indicates that the "
        "implementation will never provide the feature and any other "
        "value indicates that the implementation will always provide "
        "the feature.sysconf returns this variable when _SC_XOPEN_UNIX "
        "is passed to it.") ]
   uint64 XopenUnix; 
      [Description ("Implementation provides a C-language compilation "
        "environment with 32-bit int, long, pointer and off_t types. "
        "A value of -1 indicates that the implementation will never "
        "provide the feature and any other value indicates that the "
        "implementation will always provide the feature.  sysconf "
        "returns this variable when _SC_XBS5_ILP32_OFF32 is passed "
        "to it.") ]
   uint64 XopenXbs5Ilp32Off32; 
      [Description ("Implementation provides a C-language compilation "
        "environment with 32-bit int, long and pointer types and an "
        "off_t type using at least 64bits. A value of -1 indicates "
        "that the implementation will never provide the feature and "
        "any other value indicates that the implementation will always "
        "provide the feature.sysconf returns this variable when "
        "_SC_XBS5_ILP32_OFFBIG is passed to it.") ]
   uint64 XopenXbs5Ilp32OffBig;
      [Description ("Implementation provides a C-language compilation "
        "environment with 32-bit int and 64-bit long, pointer and off_t "
        "types. A value of -1 indicates that the implementation will "
        "never provide the feature and any other value indicates that "
        "the implementation will always provide the feature.  sysconf "
        "returns this variable when _SC_XBS5_LP64_OFF64 is passed to it.") ]
   uint64 XopenXbs5Lp64Off64; 
      [Description ("Implementation provides a C-language compilation "
        "environment with an int type using at least 32 bits and long, "
        "pointer and off_t types using at least 64 bits. A value of -1 "
        "indicates that the implementation will never provide the feature "
        "and any other value indicates that the implementation will "
        "always provide the feature.sysconf returns this variable when "
        "_SC_XBS5_LPBIG_OFF64 is passed to it.") ]
   uint64 XopenXbs5IlbigOffbig; 
      [Description ("Implementation supports the Asynchronous Input "
        "and Output option. This symbolic constant is defined (to an "
        "unspecified value) only if _XOPEN_REALTIME is defined to have "
        "a value other than -1.  sysconf returns this variable when "
        "_SC_ASYNCHRONOUS_IO is passed to it.") ]
   uint64 PosixAsynchronousIo; 
      [Description ("Implementation supports the File Synchronisation "
        "option.This constant is always defined. sysconf returns this "
        "variable when _SC_FSYNC is passed to it.") ]
   uint64 PosixFsync; 
      [Description ("Implementation supports the Memory Mapped Files "
        "option. This constant is always defined. sysconf returns this "
        "variable when _SC_MAPPED_FILES is passed to it.") ]
   uint64 PosixMappedFiles; 
      [Description ("Implementation supports the Process Memory "
        "Locking option. This symbolic constant is defined (to an "
        "unspecified value) only  if _XOPEN_REALTIME is defined to "
        "have a value other than -1. sysconf returns this variable "
        "when _SC_MEMLOCK is passed to it.") ]
   uint64 PosixMemlock; 
      [Description ("Implementation supports the Range Memory Locking "
        "option. This symbolic constant is defined (to an unspecified "
        "value) only  if _XOPEN_REALTIME is defined to have a value "
        "other than -1. sysconf returns this variable when _SC_MEMLOCK_"
        "RANGE is passed to it.") ]
   uint64 PosixMemlockRange; 
      [Description ("Implementation supports the Memory Protection "
        "option.  This constant is always defined. sysconf returns this "
        "variable when _SC_MEMORY_PROTECTION is passed to it.") ]
   uint64 PosixMemoryProtection; 
      [Description ("Implementation supports the Message Passing "
        "option.  This symbolic constant is defined (to an unspecified "
        "value) only  if _XOPEN_REALTIME is defined to have a value other "
        "than -1. sysconf returns this variable when _SC_MESSAGE_PASSING "
        "is passed to it.") ]
   uint64 PosixMessagePassing; 
      [Description ("Implementation supports the Prioritized "
        "Input and Output  option. It is defined if and only if the "
        "option is supported sysconf returns this variable when "
        "_SC_PRIORITIZED_IO is passed to it.") ]
   uint64 PosixPrioritizedIo; 
      [Description ("Implementation supports the Prioritized Input "
        "and Output  option. This symbolic constant is defined (to "
        "an unspecified value) only  if _XOPEN_REALTIME_THREADS is "
        "defined to have a value other than -1. sysconf returns this "
        "variable when _SC_PRIORITY_SCHEDULING  is passed to it.") ]
   uint64 PosixPriorityScheduling; 
      [Description ("Implementation supports the Realtime Signals "
        "Extension  option. This symbolic constant is defined to an "
        "unspecified value only  if _XOPEN_REALTIME is defined to have "
        "a value other than -1. sysconf returns this variable when "
        "_SC_REALTIME_SIGNALS is passed to it.") ]
   uint64 PosixRealtimeSignals; 
      [Description ("Implementation supports the Semaphores option.  "
        "This symbolic constant is defined to an unspecified value "
        "only if _XOPEN_REALTIME is defined to have a value other "
        "than -1. sysconf returns this variable when _SC_SEMAPHORES "
        "is passed to it.") ]
   uint64 PosixSemaphores; 
      [Description ("Implementation supports the Shared Memory Objects "
        "option. This symbolic constant is defined to an unspecified "
        "value only  if _XOPEN_REALTIME is defined to have a value "
        "other than -1. sysconf returns this variable when _SC_SHARED_"
        "MEMORY_OBJECTS is passed to it.") ]
   uint64 PosixSharedMemoryObjects; 
      [Description ("Implementation supports the Synchronised Input "
        "and Output  option. This symbolic constant is defined to an "
        "unspecified value only  if _XOPEN_REALTIME is defined to have "
        "a value other than -1. sysconf returns this variable when "
        "_SC_SYNCHRONIZED_IO is passed to it.") ]
   uint64 PosixSynchronizedIo; 
      [Description ("Implementation supports the Timers option.  This "
        "symbolic constant is defined to an unspecified value only "
        "if _XOPEN_REALTIME is defined to have a value other than -1. "
        "sysconf returns this variable when _SC_TIMERS is passed to it.") ]
   uint64 PosixTimers; 
      [Description ("The implementation supports the threads option. "
        "This constant is always defined to an unspecified value to "
        "indicate that this  functionality from the POSIX Threads "
        "Extension is always present on  XSI-conformant systems "
        "sysconf returns this variable when _SC_THREADS is passed "
        "to it.") ]
   uint64 PosixThreads; 
      [Description ("The implementation supports the thread stack "
        "address attribute option. This constant is always defined to "
        "an unspecified value to indicate that this functionality from "
        "the POSIX Threads Extension is always present  on XSI-"
        "conformant systems sysconf returns this variable when "
        "_SC_THREAD_ATTR_STACKADDR is passed to it.") ]
   uint64 PosixThreadAttrStackAddr;
      [Description ("The implementation supports the thread stack size "
        "attribute  option. This constant is always defined to an "
        "unspecified value to indicate that this functionality from the "
        "POSIX Threads Extension is always present  on XSI-conformant "
        "systems sysconf returns this variable when _SC_THREAD_ATTR_"
        "STACKSIZE is passed to it.") ]
   uint64 PosixThreadAttrStackSize; 
      [Description ("The implementation supports the thread execution "
        "scheduling  option. This symbolic constant is defined (to an "
        "unspecified value) only  if _XOPEN_REALTIME_THREADS is defined "
        "to have a value other than -1. sysconf returns this variable "
        "when _SC_THREAD_PRIORITY_SCHEDULING is passed to it.") ]
   uint64 PosixThreadPriorityScheduling; 
      [Description ("The implementation supports the priority "
        "inheritance option.  This symbolic constant is defined (to an "
        "unspecified value) only  if _XOPEN_REALTIME_THREADS is defined "
        "to have a value other than -1. sysconf returns this variable "
        "when _SC_THREAD_PRIO_INHERIT is passed to it.") ]
   uint64 PosixThreadPrioInherit;
      [Description ("The implementation supports the priority protection "
        "option.  This symbolic constant is defined (to an unspecified "
        "value) only  if _XOPEN_REALTIME_THREADS is defined to have a "
        "value other than -1. sysconf returns this variable when "
        "_SC_THREAD_PRIO_PROTECT is passed to it.") ]
   uint64 PosixThreadPrioProtect; 
      [Description ("The implementation supports the process-shared "
        "synchronisation option. This constant is always defined to an "
        "unspecified value to indicate that this functionality from the "
        "POSIX Threads Extension is always present  on XSI-conformant "
        "systems sysconf returns this variable when _SC_THREAD_PROCESS_"
        "SHARED is passed to it.") ]
   uint64 PosixThreadProcessShared; 
      [Description ("The implementation supports the thread-safe "
        "functions option.  This constant is always defined to an "
        "unspecified value to indicate that  This functionality from "
        "the POSIX Threads Extension is always present on  XSI-"
        "conformant systems sysconf returns this variable when "
        "_SC_THREAD_SAFE_FUNCTIONS is passed to it.") ]
   uint64 PosixThreadSaveFunctions; 
};
