ROOT = ../../../..

DIR = Providers/sample/LocalizedProvider

include $(ROOT)/mak/config.mak

LIBRARY = SampleLocalizedProvider

LIBRARIES = \
	pegcommon \
	pegprovider
	
SOURCES = \
	LocalizedProviderMain.cpp \
	LocalizedProvider.cpp

include $(ROOT)/mak/library.mak

tests:



