ROOT = ../../../../..
DIR = Pegasus/Common/tests/Stack
include $(ROOT)/mak/config.mak
include ../libraries.mak

LOCAL_DEFINES = -DPEGASUS_INTERNALONLY

PROGRAM = TestStack
SOURCES = Stack.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)

poststarttests:

