ROOT = ../../../../..
DIR = Pegasus/Common/tests/Stack
include $(ROOT)/mak/config.mak
include ../libraries.mak

PROGRAM = TestStack
SOURCES = Stack.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)
