ROOT = $(PEGASUS_ROOT)

DIR = Pegasus/ProviderManager2/CMPI/samples

include $(ROOT)/mak/config.mak

LIBRARY = CMPISampleClass
	
SOURCES = \
   CMPISampleClass.c

include $(ROOT)/mak/library.mak

tests: