
ROOT = ../../../..

include $(ROOT)/mak/config.mak
include $(ROOT)/test/config.mak

XMLSCRIPTS = References45000 References45001 References45002 References45003 References45004 References45005

include $(ROOT)/test/configend.mak
