
ROOT = ../../../..
include $(ROOT)/mak/config.mak
include $(ROOT)/test/config.mak

XMLSCRIPTS = DeleteQualifier39000 DeleteQualifier39001 DeleteQualifier39002 DeleteQualifier39003

clean:
	$(RM) $(XMLRESPONSES)


tests: $(XMLRESPONSES)
