
ROOT = ../../../..
include $(ROOT)/mak/config.mak
include $(ROOT)/test/config.mak

XMLSCRIPTS = DeleteQualifier39000 DeleteQualifier39001 DeleteQualifier39003

ifndef SECURITY_ENABLED
XMLSCRIPTS += \
           DeleteQualifier39002
endif

include $(ROOT)/test/configend.mak
