ROOT = ${PEGASUS_HOME}
include $(ROOT)/mak/config.mak
include $(ROOT)/src/Pegasus/Client/tests/libraries.mak

PROGRAM = testExecQuery

SOURCES = TestExecQuery.cpp

include $(ROOT)/mak/program.mak

tests:

poststarttests:
	$(PROGRAM)
