#define yy_create_buffer CQL__create_buffer
#define yy_delete_buffer CQL__delete_buffer
#define yy_scan_buffer CQL__scan_buffer
#define yy_scan_string CQL__scan_string
#define yy_scan_bytes CQL__scan_bytes
#define yy_flex_debug CQL__flex_debug
#define yy_init_buffer CQL__init_buffer
#define yy_flush_buffer CQL__flush_buffer
#define yy_load_buffer_state CQL__load_buffer_state
#define yy_switch_to_buffer CQL__switch_to_buffer
#define yyin CQL_in
#define yyleng CQL_leng
#define yylex CQL_lex
#define yyout CQL_out
#define yyrestart CQL_restart
#define yytext CQL_text
#define yywrap CQL_wrap

/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /cvs/MSB/pegasus/src/Pegasus/CQL/CQLLEX.cpp,v 1.4 2004/12/08 19:54:56 humberto Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 60
#define YY_END_OF_BUFFER 61
static yyconst short int yy_accept[171] =
    {   0,
        0,    0,   61,   59,   57,   58,   59,   42,   59,   46,
       47,   36,   38,   40,   39,   43,   37,   31,   30,   30,
       59,   53,   50,   55,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   44,   45,   49,
       59,   57,   51,    0,   35,   34,    0,    0,    0,   31,
       30,   30,    0,   31,   29,   29,   41,   33,   56,   56,
        0,   56,   28,   56,   30,   30,   24,   52,   54,   56,
       56,    5,    7,   56,   56,   56,   56,   56,   56,   12,
       13,   56,   56,   56,   23,   56,   56,   56,   56,   48,
        0,    0,   35,   34,    0,    0,   28,    0,   30,   30,

       32,    0,    0,   27,    0,   29,   29,    0,   26,   26,
       24,   22,    4,    6,   56,   56,   56,   56,   56,   56,
       14,   56,   21,   56,   56,   56,   56,   56,   56,   26,
        0,   25,    0,   33,   26,   26,    8,   56,   56,   56,
       56,    2,   15,   20,   56,   56,   56,   18,   56,   26,
        0,   32,   25,   56,   10,   19,   11,   16,   56,   56,
        3,   56,   56,    1,   56,   56,    9,   56,   17,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    1,    5,    1,    1,    1,    6,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       17,   17,   17,   17,   17,   17,   17,   18,    1,   19,
       20,   21,    1,    1,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   28,   31,   32,   33,   34,   35,   28,
       28,   36,   37,   38,   39,   40,   41,   42,   43,   28,
       44,   45,   46,    1,   47,    1,   22,   23,   24,   25,

       26,   27,   28,   29,   30,   28,   31,   32,   33,   34,
       35,   28,   28,   36,   37,   38,   39,   40,   41,   42,
       43,   28,    1,   48,    1,    1,    1,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,

       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49
    } ;

static yyconst int yy_meta[50] =
    {   0,
        1,    1,    1,    1,    2,    3,    4,    4,    1,    1,
        1,    2,    5,    1,    6,    6,    6,    5,    1,    1,
        1,    6,    6,    6,    6,    6,    6,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    2,    1,    2,    7,    1,    5
    } ;

static yyconst short int yy_base[180] =
    {   0,
        0,    0,  138,  528,  125,  528,  102,  528,   47,  528,
      528,  528,   43,  528,   48,   53,  528,   58,   67,   63,
       96,   88,  528,   82,   78,   62,   69,   83,   70,   89,
       84,   94,   95,   99,  115,  106,  110,  528,  528,  111,
       50,   95,  528,  147,   71,  528,   69,  153,   72,  149,
      154,  163,  158,  170,  184,  189,  528,  193,  173,  198,
       49,  147,  183,  209,    0,  180,    0,  528,  528,  193,
      203,  205,  204,  210,  211,  217,  218,  222,  226,  228,
      235,  233,  237,  244,  243,  245,  252,  251,  261,  528,
      247,  260,  528,  267,  284,  293,  528,    0,  298,  303,

      307,  312,  321,  528,    0,  326,  331,  340,  343,    0,
        0,  257,  259,  317,  337,  338,  343,  344,  348,  350,
      352,  362,  356,  360,  369,  368,  374,  375,  379,    0,
      407,    0,  287,  315,    0,    0,  370,  384,  391,  401,
      392,  399,  403,  405,  407,  411,  422,  413,  423,    0,
      347,  436,    0,  421,  427,  428,  429,  433,  441,  435,
      437,  452,  447,  445,  453,  459,  446,  458,  460,  528,
      497,  500,  507,  514,  520,   56,   51,   46,   45
    } ;

static yyconst short int yy_def[180] =
    {   0,
      170,    1,  170,  170,  170,  170,  170,  170,  171,  170,
      170,  170,  170,  170,  170,  170,  170,  172,  172,   19,
      170,  170,  170,  170,   19,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,  170,  170,   25,
      170,  170,  170,  171,  173,  170,  174,  171,  170,  170,
      170,  170,  170,  170,  170,  170,  170,  170,   19,   19,
      170,   25,   25,   19,   19,   19,  175,  170,  170,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,  170,
      173,  173,  170,  173,  170,  170,  170,  176,  170,  170,

      170,  170,  170,  170,  177,  170,  170,  170,   64,  109,
      175,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,  178,
      170,  179,  170,  170,  109,  109,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,  178,
      170,  170,  179,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,    0,
      170,  170,  170,  170,  170,  170,  170,  170,  170
    } ;

static yyconst short int yy_nxt[578] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   27,   27,   31,
       27,   32,   27,   33,   34,   27,   35,   36,   27,   27,
       37,   27,   27,   38,    4,   39,   40,   41,   27,   45,
      153,  150,   46,   47,   47,   49,  132,   50,   51,   52,
       53,  130,   54,   55,   56,   57,   67,   58,   58,   58,
       49,   93,   59,   59,   60,   61,   46,   66,   66,   49,
       63,   65,   65,   66,   61,   62,   58,   58,   58,   63,
      170,   48,   70,   70,   70,   62,   42,   90,   62,   64,

       62,   69,   62,   62,   73,   62,   62,   68,   74,   76,
       77,   71,   75,   67,   72,   92,   62,   80,   78,   62,
       81,   43,   62,   82,   79,   62,   42,   62,   62,   83,
       62,   62,   62,   84,   85,   62,   86,  170,   89,   62,
       87,   88,   62,   62,   62,  170,   62,   62,   62,   45,
      170,   62,   46,   47,   47,   45,  170,  170,   94,   47,
       47,   49,  170,   95,   95,   96,   49,  170,   99,   99,
      100,   97,  101,  101,  101,   49,   97,  100,  100,  100,
       62,  170,   53,   62,  102,  102,  103,   59,   59,   60,
       98,   48,  104,  170,   66,   66,   53,   48,  106,  106,

      107,   53,   62,  107,  107,  107,  104,   58,   58,   58,
      170,  105,   60,   60,   60,  170,   62,  170,  108,   62,
       62,  170,  170,  109,  109,  109,   62,  112,  114,   62,
      110,  110,  110,  110,  110,  110,   62,   62,   62,   62,
       62,   62,  117,   62,   62,  113,  115,  116,  170,  118,
       62,   62,   46,   62,   62,   62,  121,  119,   62,   62,
      120,   62,   62,  122,   62,   94,   62,  125,   62,   62,
       62,   62,   46,   62,  123,  124,   62,   62,   62,   62,
       62,   62,  126,  127,   62,   62,  129,   62,   62,  128,
       62,   92,   62,   62,   62,   62,   49,   62,   95,   95,

       96,  134,  134,  134,   92,   49,   97,   96,   96,   96,
       49,   92,   99,   99,  100,   49,  170,  100,  100,  100,
       97,  101,  101,  101,   53,  170,  102,  102,  103,  134,
      134,  134,  131,   53,  104,  103,  103,  103,   53,  170,
      106,  106,  107,   53,  170,  107,  107,  107,  104,  133,
       62,  133,  170,   62,  134,  134,  134,  135,  135,  135,
      137,  152,  152,  152,  136,  136,  136,  136,  136,  136,
       62,   62,  170,   62,   62,  138,   62,   62,  139,   62,
      140,   62,  142,   62,  141,   62,   62,  143,   62,   62,
      170,  144,   62,   62,  145,   62,   62,  146,   62,  147,

      148,   62,   62,   62,   62,   62,   62,   62,   62,  170,
       62,   62,   62,  154,  149,   62,  151,   62,  151,  170,
       62,  152,  152,  152,   62,   62,  156,   62,   62,  157,
      170,  170,   62,  155,   62,   62,   62,   62,   62,   62,
       62,   62,  158,   62,   62,  160,   62,  159,  161,   62,
      152,  152,  152,  170,  162,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,  163,   62,   62,
       62,   62,  164,   62,   62,  165,  166,   62,   62,   62,
       62,   62,   62,   62,  168,   62,   62,  170,   62,   62,
      167,   62,   62,   62,  169,   62,   62,   44,   44,   44,

       44,   44,   44,   44,   62,   62,   62,   91,   91,   91,
      170,   91,   91,   91,   47,   47,  170,   47,   47,   47,
       47,  111,  111,  170,  170,  111,  111,    3,  170,  170,
      170,  170,  170,  170,  170,  170,  170,  170,  170,  170,
      170,  170,  170,  170,  170,  170,  170,  170,  170,  170,
      170,  170,  170,  170,  170,  170,  170,  170,  170,  170,
      170,  170,  170,  170,  170,  170,  170,  170,  170,  170,
      170,  170,  170,  170,  170,  170,  170
    } ;

static yyconst short int yy_chk[578] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    9,
      179,  178,    9,    9,    9,   13,  177,   13,   13,   13,
       15,  176,   15,   15,   15,   16,   61,   16,   16,   16,
       18,   47,   18,   18,   18,   18,   45,   20,   20,   19,
       18,   19,   19,   19,   19,   20,   49,   49,   49,   19,
       25,    9,   25,   25,   25,   26,   42,   41,   26,   18,

       25,   24,   27,   29,   26,   27,   29,   22,   28,   29,
       30,   25,   28,   21,   25,   45,   28,   31,   30,   28,
       31,    7,   30,   32,   30,   30,    5,   32,   33,   33,
       32,   33,   34,   33,   34,   34,   35,    3,   37,   36,
       35,   36,   36,   37,   40,    0,   37,   40,   35,   44,
        0,   35,   44,   44,   44,   48,    0,    0,   48,   48,
       48,   50,    0,   50,   50,   50,   51,    0,   51,   51,
       51,   50,   53,   53,   53,   52,   51,   52,   52,   52,
       62,    0,   54,   62,   54,   54,   54,   59,   59,   59,
       50,   44,   54,    0,   66,   66,   55,   48,   55,   55,

       55,   56,   66,   56,   56,   56,   55,   58,   58,   58,
        0,   54,   60,   60,   60,    0,   63,    0,   58,   63,
       60,   64,    0,   64,   64,   64,   70,   71,   72,   70,
       64,   64,   64,   64,   64,   64,   71,   73,   72,   71,
       73,   72,   76,   74,   75,   71,   74,   75,    0,   77,
       76,   77,   91,   76,   77,   78,   81,   78,   78,   79,
       79,   80,   79,   82,   80,   92,   82,   85,   81,   82,
       83,   81,   94,   83,   83,   84,   85,   84,   86,   85,
       84,   86,   86,   87,   88,   87,   89,   88,   87,   88,
      112,   91,  113,  112,   89,  113,   95,   89,   95,   95,

       95,  133,  133,  133,   92,   96,   95,   96,   96,   96,
       99,   94,   99,   99,   99,  100,    0,  100,  100,  100,
       99,  101,  101,  101,  102,    0,  102,  102,  102,  134,
      134,  134,  101,  103,  102,  103,  103,  103,  106,    0,
      106,  106,  106,  107,    0,  107,  107,  107,  106,  108,
      114,  108,    0,  114,  108,  108,  108,  109,  109,  109,
      115,  151,  151,  151,  109,  109,  109,  109,  109,  109,
      115,  116,    0,  115,  116,  116,  117,  118,  117,  117,
      118,  119,  120,  120,  119,  121,  120,  122,  121,  123,
        0,  124,  123,  124,  125,  122,  124,  126,  122,  127,

      128,  126,  125,  137,  126,  125,  137,  127,  128,    0,
      127,  128,  129,  138,  129,  129,  131,  138,  131,    0,
      138,  131,  131,  131,  139,  141,  140,  139,  141,  141,
        0,    0,  142,  139,  140,  142,  143,  140,  144,  143,
      145,  144,  145,  145,  146,  147,  148,  146,  149,  148,
      152,  152,  152,    0,  154,  147,  149,  154,  147,  149,
      155,  156,  157,  155,  156,  157,  158,  159,  160,  158,
      161,  160,  160,  161,  159,  162,  163,  159,  164,  167,
      163,  164,  167,  163,  166,  162,  165,    0,  162,  165,
      165,  168,  166,  169,  168,  166,  169,  171,  171,  171,

      171,  171,  171,  171,  172,  172,  172,  173,  173,  173,
        0,  173,  173,  173,  174,  174,    0,  174,  174,  174,
      174,  175,  175,    0,    0,  175,  175,  170,  170,  170,
      170,  170,  170,  170,  170,  170,  170,  170,  170,  170,
      170,  170,  170,  170,  170,  170,  170,  170,  170,  170,
      170,  170,  170,  170,  170,  170,  170,  170,  170,  170,
      170,  170,  170,  170,  170,  170,  170,  170,  170,  170,
      170,  170,  170,  170,  170,  170,  170
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "CQL.l"
#define INITIAL 0
#define YY_NEVER_INTERACTIVE 1
#line 3 "CQL.l"
extern int CQLInput(char* buffer, int& numRead, int numRequested);
extern int CQL_error(const char*);

#ifdef CQLINPUT
#define YY_INPUT(BUF, NREAD, NREQUESTED) CQLInput(BUF, NREAD, NREQUESTED)
#endif

#ifdef CQL_DEBUG_LEXER
#define DEBUG_LEX 1
#else
#define DEBUG_LEX 0
#endif

#include <Pegasus/Common/Config.h>
#include "CQLParserState.h"
#include <stdlib.h>
#include <stdio.h>
#include <cstring>
#include "CQLObjects.h"
#include "CQLYACC.h"
PEGASUS_NAMESPACE_BEGIN
                                                                                
extern CQLParserState* globalParserState;
                                                                                
PEGASUS_NAMESPACE_END
char msg_[100];
void printf__(char * msg){
        if(DEBUG_LEX == 1)
                printf("%s\n",msg);
}

int lineno;

#line 597 "lex.CQL_.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 74 "CQL.l"


#line 751 "lex.CQL_.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 171 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 528 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 76 "CQL.l"
{

    sprintf(msg_,"LEX: %s [SELECT] ", yytext);
    printf__(msg_);
    globalParserState->currentTokenPos+=yyleng;    
    globalParserState->tokenCount++;
    return SELECT;
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 85 "CQL.l"
{

    sprintf(msg_,"LEX: %s [FROM] ", yytext);
    printf__(msg_);
    globalParserState->currentTokenPos+=yyleng;
    globalParserState->tokenCount++;
    return FROM;
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 94 "CQL.l"
{

    sprintf(msg_,"LEX: %s [WHERE] ", yytext);
    printf__(msg_);
    globalParserState->currentTokenPos+=yyleng;
    globalParserState->tokenCount++;
    return WHERE;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 103 "CQL.l"
{

    sprintf(msg_,"LEX: %s [ANY] ", yytext);
    printf__(msg_);
    globalParserState->currentTokenPos+=yyleng;
    globalParserState->tokenCount++;
    return ANY;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 112 "CQL.l"
{
    sprintf(msg_,"LEX: %s [AS] ", yytext);
    printf__(msg_);
    globalParserState->currentTokenPos+=yyleng;
    globalParserState->tokenCount++;
    return AS;
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 120 "CQL.l"
{
    sprintf(msg_,"LEX: %s [ASC] ", yytext);
    printf__(msg_);
    globalParserState->currentTokenPos+=yyleng;
    globalParserState->tokenCount++;
    return ASC;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 128 "CQL.l"
{
    sprintf(msg_,"LEX: %s [BY] ", yytext);
    printf__(msg_);
    globalParserState->currentTokenPos+=yyleng;
    globalParserState->tokenCount++;
    return BY;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 136 "CQL.l"
{
    sprintf(msg_,"LEX: %s [DESC] ", yytext);
    printf__(msg_);
    globalParserState->currentTokenPos+=yyleng;
    globalParserState->tokenCount++;
    return DESC;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 145 "CQL.l"
{
    sprintf(msg_,"LEX: %s [DISTINCT] ", yytext);
    printf__(msg_);
    globalParserState->currentTokenPos+=yyleng;
    globalParserState->tokenCount++;
    return DISTINCT;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 153 "CQL.l"
{
    sprintf(msg_,"LEX: %s [EVERY] ", yytext);
    printf__(msg_);
    globalParserState->currentTokenPos+=yyleng;
    globalParserState->tokenCount++;
    return EVERY;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 161 "CQL.l"
{
    sprintf(msg_,"LEX: %s [FIRST] ", yytext);
    printf__(msg_);
    globalParserState->currentTokenPos+=yyleng;
    globalParserState->tokenCount++;
    return FIRST;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 169 "CQL.l"
{
    sprintf(msg_,"LEX: %s [IN] ", yytext);
    printf__(msg_);
    globalParserState->currentTokenPos+=yyleng;
    globalParserState->tokenCount++;
    return IN;
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 177 "CQL.l"
{
    sprintf(msg_,"LEX: %s [IS] ", yytext);
    printf__(msg_);
    globalParserState->currentTokenPos+=yyleng;
    globalParserState->tokenCount++;
    return IS;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 185 "CQL.l"
{
    sprintf(msg_,"LEX: %s [ISA] ", yytext);
    printf__(msg_);
    globalParserState->currentTokenPos+=yyleng;
    globalParserState->tokenCount++;
    return _ISA;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 193 "CQL.l"
{
    sprintf(msg_,"LEX: %s [LIKE] ", yytext);
    printf__(msg_);
    globalParserState->currentTokenPos+=yyleng;
    globalParserState->tokenCount++;
    return _LIKE;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 201 "CQL.l"
{
    sprintf(msg_,"LEX: %s [ORDER] ", yytext);
    printf__(msg_);
    globalParserState->currentTokenPos+=yyleng;
    globalParserState->tokenCount++;
    return ORDER;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 209 "CQL.l"
{
    sprintf(msg_,"LEX: %s [SATISFIES] ", yytext);
    printf__(msg_);
    globalParserState->currentTokenPos+=yyleng;
    globalParserState->tokenCount++;
    return SATISFIES;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 217 "CQL.l"
{
    sprintf(msg_,"LEX: %s [_TRUE] ", yytext);
    printf__(msg_);
    globalParserState->currentTokenPos+=yyleng;
    globalParserState->tokenCount++;
    return _TRUE;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 225 "CQL.l"
{
    sprintf(msg_,"LEX: %s [_FALSE] ", yytext);
    printf__(msg_);
    globalParserState->currentTokenPos+=yyleng;
    globalParserState->tokenCount++;
    return _FALSE;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 233 "CQL.l"
{
    sprintf(msg_,"LEX: %s [_NULL] ", yytext);
    printf__(msg_);
    globalParserState->currentTokenPos+=yyleng;
    globalParserState->tokenCount++;
    return _NULL;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 241 "CQL.l"
{
    sprintf(msg_,"LEX: %s [NOT] ", yytext);
    printf__(msg_);
    globalParserState->currentTokenPos+=yyleng;
    globalParserState->tokenCount++;
    return NOT;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 249 "CQL.l"
{
    sprintf(msg_,"LEX: %s [AND] ", yytext);
    printf__(msg_);
    globalParserState->currentTokenPos+=yyleng;
    globalParserState->tokenCount++;
    return _AND;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 257 "CQL.l"
{
    sprintf(msg_,"LEX: %s [OR] ", yytext);
    printf__(msg_);
    globalParserState->currentTokenPos+=yyleng;
    globalParserState->tokenCount++;
    return _OR;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 265 "CQL.l"
{
    globalParserState->currentTokenPos+=yyleng;
    globalParserState->tokenCount++;
	 /* remove any single quotes surrounding embedded literals */
	 const char* string = yytext;
	 String s(yytext);
	 Uint32 index = 1;
	 index = s.find("'");
	 if(index != PEG_NOT_FOUND){
	 	s.remove(index,1);
		s.remove(s.size()-1,1);
	 
		CString cstr = s.getCString();
	 	string = (const char*)cstr;
	 }
	 
    size_t n = strlen(string);
    if(CQL_lval.strValue)
        delete [] CQL_lval.strValue;
    CQL_lval.strValue = new char[n+1];
    memcpy(CQL_lval.strValue, string, n);
    CQL_lval.strValue[n] = '\0';
    sprintf(msg_,"LEX: %s [SCOPED_PROPERTY] ", CQL_lval.strValue);
    printf__(msg_);

    return SCOPED_PROPERTY;
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 293 "CQL.l"
{
    sprintf(msg_,"LEX: %s [NEGATIVE_HEXADECIMAL] ", yytext);
    printf__(msg_);
    globalParserState->currentTokenPos+=yyleng;
    globalParserState->tokenCount++;
    /* copy the hex value */
    {
        size_t n = strlen(yytext);
	if(CQL_lval.strValue)
		delete [] CQL_lval.strValue;
        CQL_lval.strValue = new char[n + 1];
        memcpy(CQL_lval.strValue, yytext, n);
        CQL_lval.strValue[n] = '\0';
    }
    return NEGATIVE_HEXADECIMAL;
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 310 "CQL.l"
{
    sprintf(msg_,"LEX: %s [HEXADECIMAL] ", yytext);
    printf__(msg_);
    globalParserState->currentTokenPos+=yyleng;
    globalParserState->tokenCount++;
    /* copy the hex value */
    {
        size_t n = strlen(yytext);
        if(CQL_lval.strValue)
                delete [] CQL_lval.strValue;
        CQL_lval.strValue = new char[n + 1];
        memcpy(CQL_lval.strValue, yytext, n);
        CQL_lval.strValue[n] = '\0';
    }
    return HEXADECIMAL;
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 327 "CQL.l"
{
    sprintf(msg_,"LEX: %s [NEGATIVE_BINARY] ", yytext);
    printf__(msg_);
    globalParserState->currentTokenPos+=yyleng;
    globalParserState->tokenCount++;
    /* copy the bin value */ 
    {
        size_t n = strlen(yytext);
	if(CQL_lval.strValue)
                delete [] CQL_lval.strValue;
        CQL_lval.strValue = new char[n + 1];
        memcpy(CQL_lval.strValue, yytext, n);
        CQL_lval.strValue[n] = '\0';
    }
    return NEGATIVE_BINARY;
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 344 "CQL.l"
{
    sprintf(msg_,"LEX: %s [BINARY] ", yytext);
    printf__(msg_);
    globalParserState->currentTokenPos+=yyleng;
    globalParserState->tokenCount++;
    /* copy the bin value */
    {
        size_t n = strlen(yytext);
        if(CQL_lval.strValue)
                delete [] CQL_lval.strValue;
        CQL_lval.strValue = new char[n + 1];
        memcpy(CQL_lval.strValue, yytext, n);
        CQL_lval.strValue[n] = '\0';
    }
    return BINARY;
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 362 "CQL.l"
{

    sprintf(msg_,"LEX: %s [NEGATIVE_INTEGER] ", yytext);
    printf__(msg_);
    globalParserState->currentTokenPos+=yyleng;
    globalParserState->tokenCount++;
    size_t n = strlen(yytext);
    if(CQL_lval.strValue)
	    delete [] CQL_lval.strValue;
    CQL_lval.strValue = new char[n + 1];
    memcpy(CQL_lval.strValue, yytext, n);
    CQL_lval.strValue[n] = '\0';

    /*CQL_lval.intValue = strtol(yytext, (char**)0, 10);*/
    return NEGATIVE_INTEGER;
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 379 "CQL.l"
{
                                                                                                                                       
    sprintf(msg_,"LEX: %s [INTEGER] ", yytext);
    printf__(msg_);
    globalParserState->currentTokenPos+=yyleng;
    globalParserState->tokenCount++;
    size_t n = strlen(yytext);
    if(CQL_lval.strValue)
            delete [] CQL_lval.strValue;
    CQL_lval.strValue = new char[n + 1];
    memcpy(CQL_lval.strValue, yytext, n);
    CQL_lval.strValue[n] = '\0';
                                                                                                                                       
    /*CQL_lval.intValue = strtol(yytext, (char**)0, 10);*/
    return INTEGER;
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 397 "CQL.l"
{

    sprintf(msg_,"LEX: %s [INTEGER] ", yytext);
    printf__(msg_);
    globalParserState->currentTokenPos+=yyleng;
    globalParserState->tokenCount++;
    size_t n = strlen(yytext);
    if(CQL_lval.strValue)
	    delete [] CQL_lval.strValue;
    CQL_lval.strValue = new char[n + 1];
    memcpy(CQL_lval.strValue, yytext, n);
    CQL_lval.strValue[n] = '\0';

    return INTEGER;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 413 "CQL.l"
{

    sprintf(msg_,"LEX: %s [NEGATIVE_REAL] ", yytext);
    printf__(msg_);
    globalParserState->currentTokenPos+=yyleng;
    globalParserState->tokenCount++;
    size_t n = strlen(yytext);
    if(CQL_lval.strValue)
            delete [] CQL_lval.strValue;
    CQL_lval.strValue = new char[n + 1];
    memcpy(CQL_lval.strValue, yytext, n);
    CQL_lval.strValue[n] = '\0';

    /*CQL_lval.realValue = strtod((char*)yytext, (char**)0);*/
    return NEGATIVE_REAL;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 430 "CQL.l"
{
                                                                                                                                       
    sprintf(msg_,"LEX: %s [REAL] ", yytext);
    printf__(msg_);
    globalParserState->currentTokenPos+=yyleng;
    globalParserState->tokenCount++;
    size_t n = strlen(yytext);
    if(CQL_lval.strValue)
            delete [] CQL_lval.strValue;
    CQL_lval.strValue = new char[n + 1];
    memcpy(CQL_lval.strValue, yytext, n);
    CQL_lval.strValue[n] = '\0';
                                                                                                                                       
    /*CQL_lval.realValue = strtod((char*)yytext, (char**)0);*/
    return REAL;
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 447 "CQL.l"
{
	/* \'[^\'\n]*\' */
    /* ATTN-B: handle long literals by using yyinput(). */
    /* ATTN-B: Handle expansion of special characters */

    sprintf(msg_,"LEX: %s [STRING] ", yytext);
    printf__(msg_);
    globalParserState->currentTokenPos+=yyleng;
    globalParserState->tokenCount++;
    /* remove any escaped \ OR escaped ' */

    String _esc_doubleslash = "\\\\";
    String _esc_singlequote = "\\'";
    String s(yytext);

    Uint32 index = 1;
    while((index = s.find(_esc_doubleslash)) != PEG_NOT_FOUND || (index = s.find(_esc_singlequote)) != PEG_NOT_FOUND){
	if(index == s.size() - 2) // make sure we dont remove the slash from say 'abc\'
		break;
	s.remove(index,1);
    }
    CString cstr = s.getCString();
    const char* string = (const char*)cstr;

    /* Copy the string (but remove the surrounding quotes */

    {
	size_t n = strlen(string) - 2;
	if(CQL_lval.strValue)
		delete [] CQL_lval.strValue;
	CQL_lval.strValue = new char[n + 1];
	memcpy(CQL_lval.strValue, string + 1, n);
	CQL_lval.strValue[n] = '\0';
    }
    return STRING_LITERAL;
}
	YY_BREAK
case 35:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 484 "CQL.l"
{

    sprintf(msg_,"Unterminated string");
    printf__(msg_);
    globalParserState->currentTokenPos+=yyleng;
    globalParserState->tokenCount++;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 492 "CQL.l"
{
   sprintf(msg_,"LEX: [STAR] ");
   printf__(msg_);
   globalParserState->currentTokenPos+=yyleng;
   globalParserState->tokenCount++;
   return STAR;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 500 "CQL.l"
{
   sprintf(msg_,"LEX: [DIV] ");
   printf__(msg_);
   globalParserState->currentTokenPos+=yyleng;
   globalParserState->tokenCount++;
   return DIV;
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 508 "CQL.l"
{
   sprintf(msg_,"LEX: [PLUS] ");
   printf__(msg_);
   globalParserState->currentTokenPos+=yyleng;
   globalParserState->tokenCount++;
   return PLUS;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 516 "CQL.l"
{
   sprintf(msg_,"LEX: [MINUS] ");
   printf__(msg_);
   globalParserState->currentTokenPos+=yyleng;
   globalParserState->tokenCount++;
   return MINUS;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 524 "CQL.l"
{
   sprintf(msg_,"LEX: [COMMA] ");
   printf__(msg_);
   globalParserState->currentTokenPos+=yyleng;
   globalParserState->tokenCount++;
   return COMMA;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 532 "CQL.l"
{
    sprintf(msg_,"LEX: [DOTDOT] ");
    printf__(msg_);
    globalParserState->currentTokenPos+=yyleng;
    globalParserState->tokenCount++;
    return DOTDOT;
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 540 "CQL.l"
{
    sprintf(msg_,"LEX: [HASH] ");
    printf__(msg_);
    globalParserState->currentTokenPos+=yyleng;                                                                   
    globalParserState->tokenCount++;
    return HASH;
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 548 "CQL.l"
{
    sprintf(msg_,"LEX: [DOT] ");
    printf__(msg_);
    globalParserState->currentTokenPos+=yyleng;
    globalParserState->tokenCount++;
    return DOT;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 556 "CQL.l"
{
    sprintf(msg_,"LEX: [LBRKT] ");
    printf__(msg_);
    globalParserState->currentTokenPos+=yyleng;
    globalParserState->tokenCount++;
    return LBRKT;
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 564 "CQL.l"
{
    sprintf(msg_,"LEX: [RBRKT] ");
    printf__(msg_);
    globalParserState->currentTokenPos+=yyleng;
    globalParserState->tokenCount++;
    return RBRKT;
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 572 "CQL.l"
{
    sprintf(msg_,"LEX: [LPAR] ");
    printf__(msg_);
    globalParserState->currentTokenPos+=yyleng;
    globalParserState->tokenCount++;
    return LPAR;
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 580 "CQL.l"
{
    sprintf(msg_,"LEX: [RPAR] ");
    printf__(msg_);
    globalParserState->currentTokenPos+=yyleng;
    globalParserState->tokenCount++;
    return RPAR;
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 588 "CQL.l"
{
    sprintf(msg_,"LEX: %s [DBL_PIPE] ", yytext);
    printf__(msg_);
    globalParserState->currentTokenPos+=yyleng;
    globalParserState->tokenCount++;
    return DBL_PIPE;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 596 "CQL.l"
{
    sprintf(msg_,"LEX: %s [UNDERSCORE] ", yytext);
    printf__(msg_);
    globalParserState->currentTokenPos+=yyleng;
    globalParserState->tokenCount++;
    return UNDERSCORE;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 604 "CQL.l"
{ 
    sprintf(msg_,"LEX: %s [_EQ] ", yytext);
    printf__(msg_);
    globalParserState->currentTokenPos+=yyleng;
    globalParserState->tokenCount++;
    return _EQ; 
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 612 "CQL.l"
{ 

    sprintf(msg_,"LEX: %s [_NE] ", yytext);
    printf__(msg_);
    globalParserState->currentTokenPos+=yyleng;
    globalParserState->tokenCount++;
    return _NE; 
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 621 "CQL.l"
{ 

    sprintf(msg_,"LEX: %s [_LE] ", yytext);
    printf__(msg_);
    globalParserState->currentTokenPos+=yyleng;
    globalParserState->tokenCount++;
    return _LE; 
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 630 "CQL.l"
{ 

    sprintf(msg_,"LEX: %s [_LT] ", yytext);
    printf__(msg_);
    globalParserState->currentTokenPos+=yyleng;
    globalParserState->tokenCount++;
    return _LT; 
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 639 "CQL.l"
{ 

    sprintf(msg_,"LEX: %s [_GE] ", yytext);
    printf__(msg_);
    globalParserState->currentTokenPos+=yyleng;
    globalParserState->tokenCount++;
    return _GE; 
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 648 "CQL.l"
{ 

    sprintf(msg_,"LEX: %s [_GT] ", yytext);
    printf__(msg_);
    globalParserState->currentTokenPos+=yyleng;
    globalParserState->tokenCount++;
    return _GT; 
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 657 "CQL.l"
{

    sprintf(msg_,"LEX: %s [IDENTIFIER] ", yytext);
    printf__(msg_);
    globalParserState->currentTokenPos+=yyleng;
    globalParserState->tokenCount++;
    {
	size_t n = strlen(yytext);
	if(CQL_lval.strValue)
		delete [] CQL_lval.strValue;
	CQL_lval.strValue = new char[n + 1];
	memcpy(CQL_lval.strValue, yytext, n);
	CQL_lval.strValue[n] = '\0';
    }

    return IDENTIFIER;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 675 "CQL.l"
{

    /* Ignore blanks */
    globalParserState->currentTokenPos+=yyleng;
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 681 "CQL.l"
{
	globalParserState->currentTokenPos=0;
	return 0;
   }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 686 "CQL.l"
{
             return 0;
        }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 690 "CQL.l"
{
    CQL_lval.strValue = 0;
    sprintf(msg_,"LEX::UNEXPECTED_CHAR\n");
    printf__(msg_);

    return UNEXPECTED_CHAR;
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 698 "CQL.l"
ECHO;
	YY_BREAK
#line 1640 "lex.CQL_.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 171 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 171 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 170);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}
#endif /* YY_NO_INPUT */

#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 698 "CQL.l"

extern "C" int CQL_wrap()
{
    return 1;
}


