ROOT = ../../../../..
DIR = Pegasus/Server/tests/XmlIndicationDispatcher
include $(ROOT)/mak/config.mak
include ../libraries.mak

EXTRA_INCLUDES = $(SYS_INCLUDES)
 
LOCAL_DEFINES = -DPEGASUS_INTERNALONLY

PROGRAM = XmlIndicationDispatcher

SOURCES = XmlIndicationDispatcher.cpp

include $(ROOT)/mak/program.mak

tests:

poststarttests:
