ROOT = ../../../../..
DIR = Pegasus/Handler/tests/XmlIndicationDispatcher
include $(ROOT)/mak/config.mak
include ../libraries.mak

EXTRA_INCLUDES = $(SYS_INCLUDES)
 
PROGRAM = XmlIndicationDispatcher

SOURCES = XmlIndicationDispatcher.cpp

include $(ROOT)/mak/program.mak

tests:
	XmlIndicationDispatcher
