ROOT = ../../../../..
DIR = Pegasus/Common/tests/CGIQueryString
include $(ROOT)/mak/config.mak
include ../libraries.mak

PROGRAM = CGIQueryString
SOURCES = CGIQueryString.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)
