ROOT = ../../../../..

#inlcude $(ROOT)/mak/config.mak

DIRS = \
   createInstances \
   lookupInstanceProvider \
   lookupIndicationProvider \
   lookupMethodProvider


include $(ROOT)/mak/recurse.mak
