ROOT = ../../../../..

#inlcude $(ROOT)/mak/config.mak

DIRS = \
   createInstances \
   deleteInstances \
   modifyInstances \
   lookupInstanceProvider \
   lookupIndicationProvider \
   lookupMethodProvider

include $(ROOT)/mak/recurse.mak
