ROOT = ../../../../..

#inlcude $(ROOT)/mak/config.mak

DIRS = \
   createInstances \
   deleteInstances \
   modifyInstances \
   lookupInstanceProvider \
   lookupMethodProvider

#   lookupIndicationProvider \

include $(ROOT)/mak/recurse.mak
