
ROOT = ../../../..
include $(ROOT)/mak/config.mak
include $(ROOT)/test/config.mak

XMLSCRIPTS = EnumerateInstances51000 EnumerateInstances51001 EnumerateInstances51002 EnumerateInstances51003

clean:
	$(RM) $(XMLRESPONSES)


tests: $(XMLRESPONSES)
