ROOT = ../../../..

DIR = Providers/TestProviders/MCCA_TestAssocProvider

include $(ROOT)/mak/config.mak

LIBRARY = MCCATestAssocProvider

LIBRARIES = \
	 pegcommon \
	 pegprovider
	
SOURCES = \
   MCCA_TestAssocProviderMain.cpp \
   MCCA_TestAssocProvider.cpp

include $(ROOT)/mak/library.mak

tests:
