ROOT = ../../../../..
DIR = Pegasus/Common/tests/Socket
include $(ROOT)/mak/config.mak
include ../libraries.mak

LOCAL_DEFINES = -DPEGASUS_INTERNALONLY

PROGRAM = Socket
SOURCES = socket_test.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)

poststarttests:

