ROOT = ../../../../..
DIR = Pegasus/Repository/LoadClass
include $(ROOT)/mak/config.mak
include ../libraries.mak

LOCAL_DEFINES = -DPEGASUS_INTERNALONLY

PROGRAM = LoadClass
SOURCES = LoadClass.cpp

include $(ROOT)/mak/program.mak

tests:
