ROOT = ../../../../..
DIR = Pegasus/Common/tests/ValidateClass
include $(ROOT)/mak/config.mak
include ../libraries.mak

PROGRAM = TestValidateClass
SOURCES = ValidateClass.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)
