ROOT = ../../../../..
DIR = Pegasus/Common/tests/ValidateClass
include $(ROOT)/mak/config.mak
include ../libraries.mak

LOCAL_DEFINES = -DPEGASUS_INTERNALONLY

PROGRAM = TestValidateClass
SOURCES = ValidateClass.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)

poststarttests:

