ROOT = ../../../../..
DIR = Pegasus/Client/tests/ClientStatistics
include $(ROOT)/mak/config.mak
include ../libraries.mak

EXTRA_INCLUDES = $(SYS_INCLUDES) $(ACE_INCLUDES)

PROGRAM = ClientStatistics

SOURCES = ClientStatistics.cpp

include $(ROOT)/mak/program.mak

tests:


poststarttests:
	$(PROGRAM)
