ROOT = ../../../../..
DIR = Pegasus/Server/tests/SendMailIndicationDispatcher
include $(ROOT)/mak/config.mak
include ../libraries.mak

EXTRA_INCLUDES = $(SYS_INCLUDES)
 
LOCAL_DEFINES = -DPEGASUS_INTERNALONLY

PROGRAM = SendMailIndicationDispatcher

SOURCES = SendMailIndicationDispatcher.cpp

include $(ROOT)/mak/program.mak

tests:

poststarttests:
