ROOT = ../../../../..
DIR = Pegasus/Common/tests/WebClient
include $(ROOT)/mak/config.mak
include ../libraries.mak

LOCAL_DEFINES = -DPEGASUS_INTERNALONLY

PROGRAM = WebClient
SOURCES = WebClient.cpp

include $(ROOT)/mak/program.mak

tests:

poststarttests:

