ROOT = ../../../../..
DIR = Pegasus/Common/tests/Qualifier
include $(ROOT)/mak/config.mak
include ../libraries.mak

PROGRAM = Qualifier
SOURCES = Qualifier.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)
