
ROOT = ../../../..
include $(ROOT)/mak/config.mak
include $(ROOT)/test/config.mak

XMLSCRIPTS = BadAttributeName01 BadBooleanValue01 BadInstanceClassName01 BadMethodName01 BadQualDecl01 BadQualDeclType01 DuplicateProperty01 DuplicateQualifier01 MissingBooleanValue01 MissingCIMEndTag01 MissingClassName01 MissingClassNameStartTag01 MissingIParamvalueEndTag01 MissingIParamvalueStartTag01 MissingKeyValue01 MissingKeyValueEndTag01 MissingMessageEndTag01 MissingMethodCallEndTag01 MissingPropertyReferenceEndTag01 MissingReqEndTag01 MissingValueArray01 MissingXmlVersion01

include $(ROOT)/test/configend.mak
