/*
//%2006////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2000, 2001, 2002 BMC Software; Hewlett-Packard Development
// Company, L.P.; IBM Corp.; The Open Group; Tivoli Systems.
// Copyright (c) 2003 BMC Software; Hewlett-Packard Development Company, L.P.;
// IBM Corp.; EMC Corporation, The Open Group.
// Copyright (c) 2004 BMC Software; Hewlett-Packard Development Company, L.P.;
// IBM Corp.; EMC Corporation; VERITAS Software Corporation; The Open Group.
// Copyright (c) 2005 Hewlett-Packard Development Company, L.P.; IBM Corp.;
// EMC Corporation; VERITAS Software Corporation; The Open Group.
// Copyright (c) 2006 Hewlett-Packard Development Company, L.P.; IBM Corp.;
// EMC Corporation; Symantec Corporation; The Open Group.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to
// deal in the Software without restriction, including without limitation the
// rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// THE ABOVE COPYRIGHT NOTICE AND THIS PERMISSION NOTICE SHALL BE INCLUDED IN
// ALL COPIES OR SUBSTANTIAL PORTIONS OF THE SOFTWARE. THE SOFTWARE IS PROVIDED
// "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
// LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
// PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
// ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
// WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//
//%/////////////////////////////////////////////////////////////////////////////
*/

#ifndef _Executor_SessionKey_h
#define _Executor_SessionKey_h

#include "Defines.h"

#define EXECUTOR_SESSION_KEY_LENGTH 32

#define EXECUTOR_NULL_SESSION_KEY "FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF"

/* 
 * This structrue represents a session key. These keys are generated by the
 * executor and passed back to the client.
 */
typedef struct SessionKeyStruct
{
    char data[EXECUTOR_SESSION_KEY_LENGTH+1];
}
SessionKey;

EXECUTOR_LINKAGE
SessionKey NewSessionKey(
    int uid, 
    long data, 
    void (*destructor)(long),
    int authenticated);

EXECUTOR_LINKAGE
int DeleteSessionKey(const SessionKey* key);

EXECUTOR_LINKAGE
int GetSessionKeyUid(const SessionKey* key, int* uid);

EXECUTOR_LINKAGE
int GetSessionKeyUsername(
    const SessionKey* key, 
    char username[EXECUTOR_BUFFER_SIZE]);

EXECUTOR_LINKAGE
int GetSessionKeyData(const SessionKey* key, long* data);

EXECUTOR_LINKAGE
int DeleteSessionKeyData(const SessionKey* key);

EXECUTOR_LINKAGE
int SetSessionKeyAuthenticated(const SessionKey* key);

EXECUTOR_LINKAGE
int GetSessionKeyAuthenticated(const SessionKey* key, int* authenticated);

EXECUTOR_LINKAGE
int TestNullSessionKey(const SessionKey* key);

EXECUTOR_LINKAGE
int TestValidSessionKey(const SessionKey* key);

#endif /* _Executor_SessionKey_h */
