ROOT = ../../../..
include ../../libraries.mak

DIR = Providers/sample/AssociationProvider

include $(ROOT)/mak/config.mak

LIBRARY = SampleAssociationProvider

LIBRARIES = \
	 pegcommon \
	 pegprovider
	
SOURCES = \
   AssociationProviderMain.cpp \
   AssociationProvider.cpp

include $(ROOT)/mak/library.mak

tests:
