ROOT = ../../../../..

DIR = Pegasus/Common/tests/ObjectNormalizer

include $(ROOT)/mak/config.mak
include ../libraries.mak

PROGRAM = TestObjectNormalizer

SOURCES = \
	TestObjectNormalizer.cpp\
	LocalRepository.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)

poststarttests:

