ROOT = ../../../../..
DIR = Pegasus/Common/tests/Method
include $(ROOT)/mak/config.mak
include ../libraries.mak

PROGRAM = Method
SOURCES = Method.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)
