// ===================================================================
// Pragmas
// ===================================================================
#pragma locale ("en_US")



// ===================================================================
// PG_IndicationHandlerSNMPMapper
// ===================================================================
   [Version ("2.2.0"), Description (
     "PG_IndicationHandlerSNMP describes the destination for "
     "Indications to be delivered via SNMP Trap") ]

class PG_IndicationHandlerSNMPMapper : CIM_IndicationHandler
{
    [Required, Description (
      "The destination to which Traps are to be delivered. ") ]
    string TrapDestination;

    [Required, Description (
      "Defines SNMP version for which Traps are to be delivered. "
      "This should be one of the following: "
      "SNMPGeneric, SNMPv1, SNMPv2C, SNMPv2, SNMPv3 ") ]
    string SNMPVersion;

    string SNMPCommunityName;
};

