#pragma include ("PG_Events20.mof")
#pragma include ("PG_ProviderModule20.mof")
#pragma include ("eServer_Events20.mof")
#pragma include ("eServer_ProviderModule20.mof")
#pragma include ("eServer_Indication20R.mof")
