# Recurse the directories defined in DIRS
# This makefile simply recurses all of the toplevel provider directories

ROOT = ../..

include $(ROOT)/mak/config.mak

#Directories to recurse
DIRS = \
    generic \
    ManagedSystem \
    statistic \
    sample \
    TestProviders \
    IndicationConsumer

include $(ROOT)/mak/recurse.mak
