include $(PEGASUS_ROOT)/mak/config.mak

DIR = Providers/sample/ProcessIndicationProvider

LIBRARY = ProcessIndicationProvider

LIBRARIES = \
	pegcommon \
	pegprovider
	
SOURCES = \
	ProcessIndicationProviderMain.cpp \
	ProcessIndicationProvider.cpp

include $(PEGASUS_ROOT)/mak/library.mak
