#pragma locale ("en_US")

instance of PG_ProviderModule
{
   Name = "DNSProviderModule";
   Location = "DNSProvider";
   Vendor = "Pegasus Community";
   Version = "1.0.0";
   InterfaceType = "C++Default";
   InterfaceVersion = "2.1.0";
};

instance of PG_Provider
{
   ProviderModuleName = "DNSProviderModule";
   Name = "DNSProvider";
};

instance of PG_ProviderCapabilities
{
   ProviderModuleName = "DNSProviderModule";
   ProviderName = "DNSProvider";
   CapabilityID = "1";
   ClassName = "PG_DNSService";
   Namespaces = {"root/cimv2"};
   ProviderType = { 2 }; // Instance
   SupportedProperties = NULL; // All properties
   SupportedMethods = NULL;  // All methods
};
