//ATTN-SLC-P2-24-Apr-02: Needs license header like other MOFs? - BZ #54


instance of PG_ProviderModule 
{
   Name = "OperatingSystemModule";
   Vendor = "Pegasus Community";
   Version = "2.0.0";
   InterfaceType = "C++Default";
   InterfaceVersion = "2.0.0";
   Location = "OSProvider";
};

instance of PG_Provider 
{
   ProviderModuleName = "OperatingSystemModule";
   Name = "PG_OperatingSystemProvider";
};

instance of PG_ProviderCapabilities 
{
   ProviderModuleName = "OperatingSystemModule";
   ProviderName = "PG_OperatingSystemProvider";
   CapabilityID = "1";
   ClassName = "CIM_OperatingSystem";
   Namespaces = {"root/cimv2"};
// do instances, but won't do enum for this superclass,
// the CIMOM will invoke us for that, we just do Get
   ProviderType = { 2, 5 }; // Instance and Method
   SupportedProperties = NULL; // All properties
   SupportedMethods = NULL; // All methods
};

instance of PG_ProviderCapabilities 
{
   ProviderModuleName = "OperatingSystemModule";
   ProviderName = "PG_OperatingSystemProvider";
   CapabilityID = "2";
   ClassName = "PG_OperatingSystem";
   Namespaces = {"root/cimv2"};
   ProviderType = { 2, 5 }; // Instance and Method
   SupportedProperties = NULL; // All properties
   SupportedMethods = NULL; // All methods
};
