
ROOT = ../../../..
include $(ROOT)/mak/config.mak
include $(ROOT)/test/config.mak

XMLSCRIPTS = SetQualifier38000 SetQualifier38001

ifndef SECURITY_ENABLED
XMLSCRIPTS += \
          SetQualifier38002
endif

include $(ROOT)/test/configend.mak
