
ROOT = ../../../..
include $(ROOT)/mak/config.mak
include $(ROOT)/test/config.mak

XMLSCRIPTS = SetQualifier38000 SetQualifier38001 SetQualifier38002

clean:
	$(RM) $(XMLRESPONSES)


tests: $(XMLRESPONSES)
