ROOT = ../../../../..
DIR = Pegasus/Common/tests/TimeValue
include $(ROOT)/mak/config.mak
include ../libraries.mak

LOCAL_DEFINES = -DPEGASUS_INTERNALONLY

PROGRAM = TestTimeValue
SOURCES = TimeValue.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)

poststarttests:

