ROOT = ../../../../..
DIR = Pegasus/Common/tests/TimeValue
include $(ROOT)/mak/config.mak
include ../libraries.mak

PROGRAM = TimeValue
SOURCES = TimeValue.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)
