ROOT = ../../../../..
DIR = Pegasus/Client/tests/InvokeMethod
include $(ROOT)/mak/config.mak
include ../libraries.mak

EXTRA_INCLUDES = $(SYS_INCLUDES)

PROGRAM = InvokeMethod2

SOURCES = InvokeMethod2.cpp

include $(ROOT)/mak/program.mak

tests:

clean:

poststarttests: 
	$(PROGRAM)
