ROOT = ../../../../..
DIR = Pegasus/Common/tests/Thread
include $(ROOT)/mak/config.mak
include ../libraries.mak

PROGRAM = Thread
SOURCES = Thread.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)

poststarttests:

