ROOT = ../../../../..
DIR = Pegasus/Common/tests/Formatter
include $(ROOT)/mak/config.mak
include ../libraries.mak

LOCAL_DEFINES = -DPEGASUS_INTERNALONLY

PROGRAM = TestFormatter
SOURCES = Formatter.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)

poststarttests:
