ROOT = ../../../../..
DIR = Pegasus/Common/tests/Formatter
include $(ROOT)/mak/config.mak
include ../libraries.mak

PROGRAM = Formatter
SOURCES = Formatter.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)
