ROOT = ../../../../..
DIR = Pegasus/Common/tests/ThreadPool
include $(ROOT)/mak/config.mak
include ../libraries.mak

LOCAL_DEFINES = -DPEGASUS_INTERNALONLY

PROGRAM = ThreadPool
SOURCES = ThreadPool.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)

poststarttests:

