include $(PEGASUS_ROOT)/mak/config.mak

DIR = Providers/sample/SNMPIndicationProvider

LIBRARY = nsatrap

LIBRARIES = \
    pegprovider \
    pegclient \
    pegcommon
	
SOURCES = \
	SNMPIndicationProviderMain.cpp \
	SNMPIndicationProvider.cpp

include $(PEGASUS_ROOT)/mak/dynamic-library.mak
