include $(PEGASUS_ROOT)/mak/config.mak

DIR = Providers/sample/SNMPIndicationProvider

LIBRARY = nsatrap

LIBRARIES = \
	pegcommon \
	pegprovider
	
SOURCES = \
	SNMPIndicationProviderMain.cpp \
	SNMPIndicationProvider.cpp

include $(PEGASUS_ROOT)/mak/library.mak
