ROOT = ../..

include $(ROOT)/mak/config.mak
include $(ROOT)/test/config.mak

#Defines subdirectories to go to recursively

DIRS = cimv2

DIRSdefects = static

# This is a recurse make file

include $(ROOT)/mak/recurse.mak

#DO NOT DELETE THIS LINE
