//==============================================================================
//
// CAUTION: THIS FILE WAS GENERATED BY CIMMOFL; PLEASE DO NOT EDIT IT.
//
//==============================================================================

#ifndef _root_PG_InterOp_namespace_h
#define _root_PG_InterOp_namespace_h

#include <Pegasus/Repository/SchemaTypes.h>

PEGASUS_NAMESPACE_BEGIN

extern const SchemaNameSpace root_PG_InterOp_namespace;

PEGASUS_NAMESPACE_END

#endif /* _root_PG_InterOp_namespace_h */
