include $(PEGASUS_ROOT)/mak/config.mak

DIRS = \
    Lockable \
	SafeQueue \
	ProviderManager \
	ProviderManagerModule \
	ProviderManagerService \
	OperationResponseHandler

include $(PEGASUS_ROOT)/mak/recurse.mak
