// ===================================================================
// Title:       User-Security MOF Specification 2.8
// Filename:    CIM_User28.mof
// Version:     2.8
// Status:      Final
// Date:        Jan 26, 2004
// ===================================================================
// Copyright 2000-2004 Distributed Management Task Force, Inc. (DMTF).
// All rights reserved.
// DMTF is a not-for-profit association of industry members dedicated
// to promoting enterprise and systems management and interoperability.
// DMTF specifications and documents may be reproduced for uses
// consistent with this purpose by members and non-members,
// provided that correct attribution is given.
// As DMTF specifications may be revised from time to time,
// the particular version and release date should always be noted.
// 
// Implementation of certain elements of this standard or proposed
// standard may be subject to third party patent rights, including
// provisional patent rights (herein "patent rights"). DMTF makes
// no representations to users of the standard as to the existence
// of such rights, and is not responsible to recognize, disclose, or
// identify any or all such third party patent right, owners or
// claimants, nor for any incomplete or inaccurate identification or
// disclosure of such rights, owners or claimants. DMTF shall have no
// liability to any party, in any manner or circumstance, under any
// legal theory whatsoever, for failure to recognize, disclose, or
// identify any such third party patent rights, or for such party's
// reliance on the standard or incorporation thereof in its product,
// protocols or testing procedures. DMTF shall have no liability to
// any party implementing such standard, whether such implementation
// is foreseeable or not, nor to any patent owner or claimant, and shall
// have no liability or responsibility for costs or losses incurred if
// a standard is withdrawn or modified after publication, and shall be
// indemnified and held harmless by any party implementing the
// standard from any and all claims of infringement by a patent owner
// for such implementations.
// 
// For information about patents held by third-parties which have
// notified the DMTF that, in their opinion, such patent may relate to
// or impact implementations of DMTF standards, visit
// http://www.dmtf.org/about/policies/disclosures.php.
// ===================================================================
// Description: The User/Security Model extends the management
//              concepts related to Users and Security. This is
//              the primary include file for the basic segments of
//              the DMTF User Model.
// 
//              The includes are listed in an order that
//              avoids forward references. Required objects, defined
//              by other working groups, are omitted.
// ===================================================================

#pragma Locale ("en_US")


// ==================================================================
// Compile prerequisite for all includes:  Core MOF
// ==================================================================


// ===================================================================
// Organizations, Persons, etc.
// ===================================================================
#pragma include ("User28_Org.mof")

// ===================================================================
// Groups
// ===================================================================
#pragma include ("User28_Group.mof")

// ===================================================================
// Roles
// ===================================================================
#pragma include ("User28_Role.mof")

// ===================================================================
// Security Services
// ===================================================================
#pragma include ("User28_SecurityServices.mof")

// ===================================================================
// Generic Credentials
// ===================================================================
#pragma include ("User28_Credential.mof")

// ===================================================================
// Identity
// ===================================================================
#pragma include ("User28_Identity.mof")

// ===================================================================
// SecurityLevel
// ===================================================================
#pragma include ("User28_SecurityLevel.mof")

// ===================================================================
// Authentication Requirements
// ===================================================================
#pragma include ("User28_AuthenticationReqmt.mof")

// ===================================================================
// Kerberos Security Service and Credential
// ===================================================================
#pragma include ("User28_Kerberos.mof")

// ===================================================================
// Public Key Security Service and Credential
// ===================================================================
#pragma include ("User28_PublicKey.mof")

// ===================================================================
// Shared Secret Security Service and Credential
// ===================================================================
#pragma include ("User28_SharedSecret.mof")

// ===================================================================
// Users Access
// ===================================================================
#pragma include ("User28_UsersAccess.mof")

// ===================================================================
// Privileges
// ===================================================================
#pragma include ("User28_Privilege.mof")

// ===================================================================
// Account
// ===================================================================
#pragma include ("User28_Account.mof")

// ===================================================================
// Access Control
// ===================================================================
#pragma include ("User28_AccessControl.mof")

// ===================================================================
// Privilege Management Service
// ===================================================================
#pragma include ("User28_PrivilegeManagementService.mof")

// ===================================================================
// Storage Hardware IDs (subclass of Identity)
// ===================================================================
#pragma include ("User28_StorageHardwareID.mof")


// ===================================================================
// end of file
// ===================================================================
