# Recurse the directories defined in DIRS

ROOT = ../../..

include $(ROOT)/mak/config.mak

# removed _NamespaceProvider

DIRS = \
	UserManagerProvider \
	OperatingSystemProvider \
	ShutdownProvider

#	ConfigSettingProvider \
#	PG_RegistrationProvider \

include $(ROOT)/mak/recurse.mak
