# Recurse the directories defined in DIRS

ROOT = ../../..

include $(ROOT)/mak/config.mak

# removed _NamespaceProvider

DIRS = \
	OperatingSystemProvider \
	ShutdownProvider

include $(ROOT)/mak/recurse.mak
