ROOT = ../../../../..

include ../libraries.mak

DIR = Pegasus/Consumer/tests/DisplayConsumer

include $(ROOT)/mak/config.mak

LOCAL_DEFINES = -DPEGASUS_CONSUMER_INTERNAL -DPEGASUS_INTERNALONLY

SOURCES = DisplayConsumer.cpp

LIBRARY = DisplayConsumer
 
include $(ROOT)/mak/library.mak

tests:
