ROOT = ../../../..
include ../../libraries.mak

DIR = Providers/sample/MethodProvider

include $(ROOT)/mak/config.mak

LIBRARY = SampleMethodProvider

LIBRARIES = \
	 pegcommon \
	 pegprovider
	
SOURCES = \
   MethodProviderMain.cpp \
   MethodProvider.cpp

include $(ROOT)/mak/library.mak

tests:
