ROOT = ../../..

PEGASUS_ZOS_PROGRAM_OBJECT = yes

DIR = Clients/ToMofClient
include $(ROOT)/mak/config.mak
include ../libraries.mak

PROGRAM = ToMofClient
SOURCES = ToMofClient.cpp

include $(ROOT)/mak/program.mak

tests:

poststarttests:
