ROOT = ../../..

DIR = Pegasus/Clients/ToMofClient
include $(ROOT)/mak/config.mak
include ../libraries.mak

PROGRAM = ToMofClient
SOURCES = ToMofClient.cpp

include $(ROOT)/mak/program.mak

tests:

poststarttests:
