instance of PG_ProviderModule
{
   Name             = "JMPI_RT_ExecQuery1Module";
   Location         = "JMPI_RT_ExecQuery1.jar:org/pegasus/jmpi/tests/ExecQuery/JMPI_RT_ExecQuery1";
   Vendor           = "Pegasus Community";
   Version          = "2.0.0";
   InterfaceType    = "JMPI";
   InterfaceVersion = "1.0.0";
};

instance of PG_Provider
{
   ProviderModuleName = "JMPI_RT_ExecQuery1Module";
   Name               = "JMPI_RT_ExecQuery1";
};

instance of PG_ProviderCapabilities
{
   ProviderModuleName  = "JMPI_RT_ExecQuery1Module";
   ProviderName        = "JMPI_RT_ExecQuery1";
   CapabilityID        = "1";
   ClassName           = "JMPI_RT_ExecQuery1";
   Namespaces          = {"test/static"};
   // ValueMap {"2",        "3",           "4" ,          "5" ,     "6" ,                 "7"},
   // Values   {"Instance", "Association", "Indication" , "Method", "IndicationConsumer", "InstanceQuery"}]
   ProviderType        = { 2, 7 };
   SupportedProperties = NULL;     // All properties
   SupportedMethods    = NULL;     // All methods
};
