instance of PG_ProviderModule
{
   Name = "JMPI_TestPropertyTypesModule";
   Location = "JMPI_TestPropertyTypes.jar:org/pegasus/jmpi/tests/JMPI_TestPropertyTypes/JMPI_TestPropertyTypes";
   Vendor = "Pegasus Community";
   Version = "2.0.0";
   InterfaceType = "JMPI";
   InterfaceVersion = "1.0.0";
};

instance of PG_Provider
{
   ProviderModuleName = "JMPI_TestPropertyTypesModule";
   Name = "JMPI_TestPropertyTypes";
};

instance of PG_ProviderCapabilities 
{
   ProviderModuleName = "JMPI_TestPropertyTypesModule";
   ProviderName = "JMPI_TestPropertyTypes";
   CapabilityID = "1";
   ClassName = "JMPI_TestElement";
   Namespaces = {"test/static"};
   ProviderType = { 2 }; // Instance
   SupportedProperties = NULL; // All properties
   SupportedMethods = NULL; // All methods
};

instance of PG_ProviderCapabilities 
{
   ProviderModuleName = "JMPI_TestPropertyTypesModule";
   ProviderName = "JMPI_TestPropertyTypes";
   CapabilityID = "2";
   ClassName = "JMPI_TestPropertyTypes";
   Namespaces = {"test/static"};
   ProviderType = { 2, 5 }; // Instance and Method
   SupportedProperties = NULL; // All properties
   SupportedMethods = NULL; // All methods
};
