ROOT = $(PEGASUS_ROOT)

include $(ROOT)/mak/config.mak

DIRS = \
    EnumerateInstances \
    EnumerateInstanceNames \
    GetInstance \
    DeleteInstance \
    CreateInstance
    


include $(ROOT)/mak/recurse.mak
