ROOT = ../..

include $(ROOT)/mak/config.mak
include $(ROOT)/test/config.mak

DIRS = 	ExceptionsTest \
	CIMOMSample	\
	LargeDataProvider \
	MultithreadingTests	\
	TimingTests \
	XMLParserGen \
	LoadMOFs

include $(PEGASUS_ROOT)/mak/recurse.mak
