ROOT = ../../../../..

DIR = Pegasus/Tracer/tests/Tracer

include $(ROOT)/mak/config.mak

include ../libraries.mak

PROGRAM = Tracer

SOURCES = Tracer.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)
