ROOT=../../..

include $(ROOT)/mak/config.mak
include $(ROOT)/test/config.mak

DIRS = \
	Load\
	CreateInstance\
	GetInstance\
	EnumerateInstanceNames\
	EnumerateInstances\
	DeleteInstance\
#	ModifyClass\
#	DeleteClass
#	ModifyInstance\
	
include $(ROOT)/mak/recurse.mak

