ROOT=../../..

include $(ROOT)/mak/config.mak
include $(ROOT)/test/config.mak

DIRS = \
	Load\
	Headers\
	CreateInstance\
	GetInstance\
	EnumerateInstanceNames\
	EnumerateInstances\
	ModifyInstance\
	DeleteInstance\
        Property \
	ModifyClass\
	DeleteClass
	
include $(ROOT)/mak/recurse.mak

