ROOT = ../../../../..
DIR = Pegasus/Common/tests/QualifierDecl
include $(ROOT)/mak/config.mak
include ../libraries.mak

PROGRAM = TestQualifierDecl
SOURCES = QualifierDecl.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)

poststarttests:

