ROOT = ../../../../..
DIR = Pegasus/Common/tests/Object
include $(ROOT)/mak/config.mak
include ../libraries.mak

PROGRAM = TestObject
SOURCES = Object.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)

poststarttests:
