ROOT = ../../../..

include $(ROOT)/mak/config.mak

#   Inst \		Temp. removed - see bug 2727
#   LoadRepository  \	Temp. removed - see bug 2878

DIRS = \
    Repository \
    Repository2 \
    NameSpace \
    NameSpaceManager \
    AssocTable \
    EnumerateClassNames \
    InheritanceTree \
    QualifierDeclRep \
    ClassDeclRep \
    SharedNameSpace \
    SharedInheritanceTree \
    CompareRepositories \
    CompareXmlBin \
    LoadClass \
    CompareXmlCompressed

include ../../../../mak/recurse.mak
