ROOT = ../../../..

include $(ROOT)/mak/config.mak

DIRS = \
    Inst \
    Repository \
    Repository2 \
    NameSpace \
    NameSpaceManager \
    AssocTable \
    EnumerateClassNames \
    InheritanceTree \
    QualifierDeclRep \
    ClassDeclRep \
    SharedNameSpace \
    SharedInheritanceTree

include ../../../../mak/recurse.mak
