ROOT = ../../../..

include $(ROOT)/mak/config.mak

XDIRS = \
    TestClasses \

DIRS = \
    LoadClass \
    ClassDeclRep \
    Repository \
    QualifierDeclRep \
    NameSpace \
    EnumerateClassNames \
    Inst

include ../../../../mak/recurse.mak
