ROOT = ../../../..

DIR = Providers/TestProviders/MethodTestProvider

include $(ROOT)/mak/config.mak

LIBRARY = MethodTestProvider

LIBRARIES = \
    pegprovider \
    pegclient \
    pegcommon
	
SOURCES = \
    MethodTestProviderMain.cpp \
    MethodTestProvider.cpp

include $(ROOT)/mak/dynamic-library.mak
