include $(PEGASUS_ROOT)/mak/config.mak

DIR = Pegasus/Server/tests/ProviderModule

LIBRARIES = \
	pegcommon \
	pegprovider \
	pegprovidermanager

LOCAL_DEFINES = -DPEGASUS_INTERNALONLY

PROGRAM = TestProviderModule

SOURCES = ProviderModule.cpp

include $(PEGASUS_ROOT)/mak/program.mak

tests:
