ROOT = ../../..

DIR = Pegasus/Clients/CGIClient
include $(ROOT)/mak/config.mak
include ../libraries.mak

PROGRAM = providerreg
SOURCES = providerreg.cpp

include $(ROOT)/mak/program.mak

install:

tests:
