ROOT = ../../../../..
DIR = Pegasus/IndicationService/tests/CreateHandlers
include $(ROOT)/mak/config.mak
include ../libraries.mak

EXTRA_INCLUDES = $(SYS_INCLUDES)

LOCAL_DEFINES = -DPEGASUS_INTERNALONLY

PROGRAM = CreateHandlers

SOURCES = CreateHandlers.cpp

include $(ROOT)/mak/program.mak

tests:

poststarttests:
