ROOT = ../../../..

DIR = Pegasus/msg/Listener

include $(ROOT)/mak/config.mak

# ICU package name
MSG_PACKAGE = pegasusListener
 

# Destination directory for the compiled bundles
MSG_DIR = $(MSG_ROOT)/pegasus

# NOTE - your .txt files must be named with the package name before the '_'
MSG_SOURCES = \
   pegasusListener_en.txt 

# Keep the following in the order listed

include $(ROOT)/mak/message.mak

messages: $(MSG_BUNDLES)

# DO NOT DELETE
