ROOT = ../../../..

DIR = Providers/TestProviders/UserContextTestProvider

include $(ROOT)/mak/config.mak

LIBRARY = UserContextTestProvider

LIBRARIES = \
	pegprovider \
	pegcommon 

SOURCES = \
   UserContextTestProvider.cpp

include $(ROOT)/mak/library.mak

tests:
