ROOT = ../../../..

DIR = /Providers/TestProviders/UserContextTestProvider

include $(ROOT)/mak/config.mak

LIBRARY = UserContextTestProvider

LIBRARIES = \
	pegcommon \
	pegprovider

SOURCES = \
   UserContextTestProvider.cpp

include $(ROOT)/mak/library.mak

tests:
