include $(PEGASUS_ROOT)/mak/config.mak
                                                                                                                                       
DIRS = \
    QueryContext \
    CQLChainedIdentifier \
    RegularExpression

include $(PEGASUS_ROOT)/mak/recurse.mak
