include $(PEGASUS_ROOT)/mak/config.mak
                                                                                                                                       
DIRS = \
    QueryContext \
    CQLChainedIdentifier \
    RegularExpression \
    CQLValue \
    Queries

include $(PEGASUS_ROOT)/mak/recurse.mak
