include $(PEGASUS_ROOT)/mak/config.mak
                                                                                                                                       
DIRS = \
    QueryContext \
    CQLChainedIdentifier

include $(PEGASUS_ROOT)/mak/recurse.mak
