//%2006////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2000, 2001, 2002 BMC Software; Hewlett-Packard Development
// Company, L.P.; IBM Corp.; The Open Group; Tivoli Systems.
// Copyright (c) 2003 BMC Software; Hewlett-Packard Development Company, L.P.;
// IBM Corp.; EMC Corporation, The Open Group.
// Copyright (c) 2004 BMC Software; Hewlett-Packard Development Company, L.P.;
// IBM Corp.; EMC Corporation; VERITAS Software Corporation; The Open Group.
// Copyright (c) 2005 Hewlett-Packard Development Company, L.P.; IBM Corp.;
// EMC Corporation; VERITAS Software Corporation; The Open Group.
// Copyright (c) 2006 Hewlett-Packard Development Company, L.P.; IBM Corp.;
// EMC Corporation; Symantec Corporation; The Open Group.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to
// deal in the Software without restriction, including without limitation the
// rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// THE ABOVE COPYRIGHT NOTICE AND THIS PERMISSION NOTICE SHALL BE INCLUDED IN
// ALL COPIES OR SUBSTANTIAL PORTIONS OF THE SOFTWARE. THE SOFTWARE IS PROVIDED
// "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
// LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
// PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
// ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
// WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//
//==============================================================================

// globalization test class for localization and UTF testing
[Version ("2.7.0")]
class Test_LocalizedProviderClass
{
    [key, read]
    Uint8 Identifier;

    [read, write]
    string RoundTripString;

    [read, write]
    char16 RoundTripChar;

    [read]
    string ResourceBundleString;

    [read, write]
    string ContentLanguageString;

    string UTFMethod(
        [IN] string inStr,
        [IN] char16 inChar16,
        [OUT] string outStr,
        [OUT] char16 outChar16);

    uint16 generateIndication();

    uint8 getConsumerStatus();

    boolean setDefaultMessageLoading([IN] boolean newSetting);
};

// globalization test class for aggregation tests
[Version ("2.7.0")]
class Test_LocalizedProviderSubClass : Test_LocalizedProviderClass
{
    [read, write]
    string TestString;
};

// globalization test class for indication tests
[Indication, Version ("2.7.0")]
class LocalizedProvider_TestIndication : CIM_Indication
{
    string UnicodeStr;
    char16 UnicodeChar;
};

