// ===================================================================
// 	IBMKR_File
// ===================================================================

instance of PG_ProviderModule
{
   Description = "CMPI Test Indication provider";
   Name = "TestCMPIIndicationProviderModule";
  // The library name on disk
   Location = "cmpiTestIndicationProvider"; 
   Vendor = "SBLIM";
   Version = "2.0.0";
   InterfaceType = "CMPI";
   InterfaceVersion = "2.0.0";
};

instance of PG_Provider
{
   ProviderModuleName = "TestCMPIIndicationProviderModule";
   // The provider name as referenced in the code!
   Name = "TestCMPIIndicationProvider";	
};

instance of PG_ProviderCapabilities
{
   ProviderModuleName = "TestCMPIIndicationProviderModule";
   ProviderName = "TestCMPIIndicationProvider";
   CapabilityID = "CMPI Test Indication Provider";
   // Name of the CIM Class as defined in the mof.
   ClassName = "TestCMPI_Indication";
   Namespaces = { "test/TestProvider" };
   ProviderType = { 4 }; // Indication
   SupportedProperties = NULL; // All properties
   SupportedMethods = NULL; // All methods
};
