ROOT = $(PEGASUS_ROOT)

DIR = Clients/benchmarkTest/benchmarkDefinition

include $(ROOT)/mak/config.mak

LIBRARY = benchmarkDefinition

LIBRARIES = \
	pegcommon 

SOURCES = \
   benchmarkDefinition.cpp 

include $(ROOT)/mak/library.mak

tests:
