ROOT = ../..

include $(ROOT)/mak/config.mak

DIRS = \
    CGIClient \
    TestClient \
    cliutils \
    cimconfig \
    cimconfig/tests \
    cimuser \
    cimuser/tests \
    cimauth \
    wbemexec \
    wbemexec/tests \
    ToMofClient

include $(ROOT)/mak/recurse.mak
