ROOT = ../..

include $(ROOT)/mak/config.mak

DIRS = \
    CGIClient \
    TestClient \
    cliutils \
    cimconfig \
    cimuser \
    cimuser/tests \
    cimauth \
    wbemexec \
    ToMofClient

include $(ROOT)/mak/recurse.mak
