ROOT = ../../../../..
DIR = Pegasus/Common/tests/OptionManager
include $(ROOT)/mak/config.mak
include ../libraries.mak

PROGRAM = OptionManager
SOURCES = OptionManager.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)
