/*NOCHKSRC*/
//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 1.2.4
//
//==============================================================================

#ifndef _cimple_EmployeeLink_h
#define _cimple_EmployeeLink_h

#include <cimple/cimple.h>
#include "Employee.h"
#include "Employee.h"

CIMPLE_NAMESPACE_BEGIN

// EmployeeLink keys:

/*[930]*/
class EmployeeLink : public Instance
{
public:
    // EmployeeLink features:
    Employee* Parent;
    Employee* Child;

    CIMPLE_CLASS(EmployeeLink)
};

CIMPLE_NAMESPACE_END

#endif /* _cimple_EmployeeLink_h */
