// Generated by genprov 1.1.2
#ifndef _EmployeeLink_Provider_h
#define _EmployeeLink_Provider_h

#include <cimple/cimple.h>
#include "EmployeeLink.h"

CIMPLE_NAMESPACE_BEGIN

class EmployeeLink_Provider
{
public:

    typedef EmployeeLink Class;

    EmployeeLink_Provider();

    ~EmployeeLink_Provider();

    Load_Status load();

    Unload_Status unload();

    Get_Instance_Status get_instance(
        const EmployeeLink* model,
        EmployeeLink*& instance);

    Enum_Instances_Status enum_instances(
        const EmployeeLink* model,
        Enum_Instances_Handler<EmployeeLink>* handler);

    Create_Instance_Status create_instance(
        EmployeeLink* instance);

    Delete_Instance_Status delete_instance(
        const EmployeeLink* instance);

    Modify_Instance_Status modify_instance(
        const EmployeeLink* model,
        const EmployeeLink* instance);

    Enum_Associator_Names_Status enum_associator_names(
        const Instance* instance,
        const String& result_class,
        const String& role,
        const String& result_role,
        Enum_Associator_Names_Handler<Instance>* handler);

    Enum_Associators_Status enum_associators(
        const Instance* instance,
        const String& result_class,
        const String& role,
        const String& result_role,
        Enum_Associators_Handler<Instance>* handler);

    Enum_References_Status enum_references(
        const Instance* instance,
        const EmployeeLink* model,
        const String& role,
        Enum_References_Handler<EmployeeLink>* handler);

    /*@END@*/
};

CIMPLE_NAMESPACE_END

#endif /* _EmployeeLink_Provider_h */
