//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENMOD 1.1.2
//
//==============================================================================

#include <cimple/cimple.h>
#include "Employee_Provider.h"
#include "EmployeeLink_Provider.h"

using namespace cimple;

static int __cimple_Employee_Provider_proc(
    const Registration* registration,
    int operation,
    void* arg0,
    void* arg1,
    void* arg2,
    void* arg3,
    void* arg4,
    void* arg5,
    void* arg6,
    void* arg7)
{
    typedef Employee Class;
    typedef Employee_Provider Provider;

    if (operation != OPERATION_INVOKE_METHOD)
        return Instance_Provider_Proc_T<Provider>::proc(registration,
            operation, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);

    Provider* provider = (Provider*)arg0;
    const Class* self = (const Class*)arg1;
    const char* meth_name = ((Instance*)arg2)->meta_class->name;

    if (strcasecmp(meth_name, "SetOutOfOfficeState") == 0)
    {
        typedef Employee_SetOutOfOfficeState_method Method;
        Method* method = (Method*)arg2;
        return provider->SetOutOfOfficeState(
            self,
            method->OutOfOfficeState,
            method->PreviousOutOfOfficeState,
            method->return_value);
    }

    if (strcasecmp(meth_name, "GetEmployeeCount") == 0)
    {
        typedef Employee_GetEmployeeCount_method Method;
        Method* method = (Method*)arg2;
        return provider->GetEmployeeCount(
            method->return_value);
    }

    return -1;
}

static int __cimple_EmployeeLink_Provider_proc(
    const Registration* registration,
    int operation,
    void* arg0,
    void* arg1,
    void* arg2,
    void* arg3,
    void* arg4,
    void* arg5,
    void* arg6,
    void* arg7)
{
    typedef EmployeeLink Class;
    typedef EmployeeLink_Provider Provider;

    if (operation != OPERATION_INVOKE_METHOD)
        return Association_Provider_Proc_T<Provider>::proc(registration,
            operation, arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);

    Provider* provider = (Provider*)arg0;
    const Class* self = (const Class*)arg1;
    const char* meth_name = ((Instance*)arg2)->meta_class->name;

    return -1;
}

CIMPLE_MODULE(Static_Module);
CIMPLE_INSTANCE_PROVIDER(Employee_Provider);
CIMPLE_ASSOCIATION_PROVIDER(EmployeeLink_Provider);

#ifdef CIMPLE_PEGASUS_MODULE
  CIMPLE_PEGASUS_PROVIDER_ENTRY_POINT;
# define __CIMPLE_FOUND_ENTRY_POINT
#endif

#ifdef CIMPLE_CMPI_MODULE
  CIMPLE_CMPI_INSTANCE_PROVIDER(Employee_Provider);
  CIMPLE_CMPI_ASSOCIATION_PROVIDER(EmployeeLink_Provider);
# define __CIMPLE_FOUND_ENTRY_POINT
#endif

#ifdef CIMPLE_OPENWBEM_MODULE
  CIMPLE_OPENWBEM_PROVIDER(Static_Module);
# define __CIMPLE_FOUND_ENTRY_POINT
#endif

#ifndef __CIMPLE_FOUND_ENTRY_POINT
# error "No provider entry point found"
#endif
