//==============================================================================
//
// PLEASE DO NOT EDIT; THIS FILE WAS AUTOMATICALLY GENERATED BY GENCLASS 1.2.4
//
//==============================================================================

#ifndef _repository_h
#define _repository_h

#include <cimple/cimple.h>
#include "CIM_Indication.h"
#include "Alert.h"
#include "Employee.h"
#include "EmployeeLink.h"

CIMPLE_NAMESPACE_BEGIN

CIMPLE_NAMESPACE_END

#endif /* _repository_h */
