ROOT = ../../../../..
DIR = Pegasus/Client/tests/EnumInstances
include $(ROOT)/mak/config.mak
include ../libraries.mak

EXTRA_INCLUDES = $(SYS_INCLUDES)

PROGRAM = EnumInstances

SOURCES = EnumInstances.cpp

include $(ROOT)/mak/program.mak

tests:

poststarttests:	
	$(PROGRAM)
