ROOT = ../../../../../..

DIR = Pegasus/Security/Authentication/tests/LocalAuthFile

LOCAL_DEFINES = -DPEGASUS_COMMON_INTERNAL 

include $(ROOT)/mak/config.mak

include ../libraries.mak

PROGRAM = LocalAuthFile

SOURCES = LocalAuthFile.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)
