ROOT = ../../../../../..

DIR = Pegasus/Security/Authentication/tests/LocalAuthFile

include $(ROOT)/mak/config.mak

include ../libraries.mak

PROGRAM = TestLocalAuthFile

SOURCES = LocalAuthFile.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)
