ROOT = ../../../../..
DIR = Pegasus/Server/tests/ClientServer
include $(ROOT)/mak/config.mak
include ../libraries.mak

LIBRARIES += pegclient

EXTRA_INCLUDES = $(SYS_INCLUDES)

PROGRAM = ClientServer

SOURCES = ClientServer.cpp

include $(ROOT)/mak/program.mak

tests:
