include $(PEGASUS_ROOT)/mak/config.mak

DIR = Providers/sample/RT_Indication/RT_IndicationProvider

LIBRARY = RT_IndicationProvider

LIBRARIES = \
    pegqueryexpression \
    pegprovider \
    pegcql \
    pegwql \
    pegquerycommon \
    pegclient \
    pegcommon
	
SOURCES = \
	RT_IndicationProviderMain.cpp \
	RT_IndicationProvider.cpp

include $(PEGASUS_ROOT)/mak/dynamic-library.mak
install:
