ROOT = ../../../../..
DIR = Pegasus/Common/tests/Dir
include $(ROOT)/mak/config.mak
include ../libraries.mak

PROGRAM = TestDir
SOURCES = Dir.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)

poststarttests:
