ROOT = ../../../..

include ../libraries.mak

DIR = Pegasus/Handler/sendmailIndicationHandler

include $(ROOT)/mak/config.mak

LOCAL_DEFINES = -DPEGASUS_HANDLER_INTERNAL -DPEGASUS_INTERNALONLY

SOURCES = sendmailIndicationHandler.cpp

LIBRARY = sendmailIndicationHandler
 
include $(ROOT)/mak/library.mak

tests:
