ROOT = ../../../../..
DIR = Pegasus/Common/tests/QualifierList
include $(ROOT)/mak/config.mak
include ../libraries.mak

PROGRAM = TestQualifierList
SOURCES = QualifierList.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)
