ROOT = ../../../../..
DIR = Pegasus/Common/tests/HashTable
include $(ROOT)/mak/config.mak
include ../libraries.mak

PROGRAM = HashTable
SOURCES = HashTable.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)
