
ROOT = ../../../..
include $(ROOT)/mak/config.mak
include $(ROOT)/test/config.mak

XMLSCRIPTS = BadCIMMethodValue01 BadCIMMethodValue02 BadCIMObjectValue01 BadCIMObjectValue02 BadCIMObjectValue03 BadCIMObjectValue04 BadCIMOperationValue01 BadCIMProtocolVersionValue01 ExtraCIMBatchTag01 ExtraCIMBatchTag02 MissingCIMBatchTag01 MissingCIMMethodTag01 MissingCIMMethodTag02 MissingCIMObjectTag01 MissingCIMObjectTag02 MissingCIMOperationTag01 MissingCIMOperationTag02 UnsupportedCIMProtocolVersionValue01 UnsupportedCIMVersionValue01 UnsupportedDTDVersionValue01 UnsupportedHTTPMethod01 MissingCIMMethodValue01

include $(ROOT)/test/configend.mak
