
ROOT = ../../../..
include $(ROOT)/mak/config.mak
include $(ROOT)/test/config.mak

XMLSCRIPTS = DeleteInstance55000 DeleteInstance55001 DeleteInstance55002 DeleteInstance55003

clean:
	$(RM) $(XMLRESPONSES)


tests: $(XMLRESPONSES)

