
ROOT = ../../../..
include $(ROOT)/mak/config.mak
include $(ROOT)/test/config.mak

XMLSCRIPTS = DeleteInstance55000 DeleteInstance55001 DeleteInstance55002 DeleteInstance55003

include $(ROOT)/test/configend.mak
