ROOT = ../../../../../..
DIR = Pegasus/Common/tests/AnonymousPipe/Child
include $(ROOT)/mak/config.mak

LIBRARIES = \
    pegcommon

LOCAL_DEFINES = -DPEGASUS_INTERNALONLY

PROGRAM = TestChild

SOURCES = Child.cpp

include $(ROOT)/mak/program.mak

tests:

poststarttests:
install:
