ROOT = ../../../../..
DIR = Pegasus/Provider/tests/ProviderTable
include $(ROOT)/mak/config.mak
include ../libraries.mak

EXTRA_INCLUDES = $(SYS_INCLUDES)

PROGRAM = ProviderTable

SOURCES = ProviderTable.cpp

include $(ROOT)/mak/program.mak

tests:
	ProviderTable
