ROOT = ../../../../..
DIR = Pegasus/Common/tests/DateTimeTest
include $(ROOT)/mak/config.mak
include ../libraries.mak

PROGRAM = DateTimeTest
SOURCES = DateTimeTest.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)
