ROOT = ../../../../..
DIR = Pegasus/Common/tests/DateTime
include $(ROOT)/mak/config.mak
include ../libraries.mak

PROGRAM = TestDateTime
SOURCES = DateTime.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)

poststarttests:
