ROOT = ../../../../..
DIR = Pegasus/IndicationService/tests/CreateFilters
include $(ROOT)/mak/config.mak
include ../libraries.mak

EXTRA_INCLUDES = $(SYS_INCLUDES)

LOCAL_DEFINES = -DPEGASUS_INTERNALONLY

PROGRAM = CreateFilters

SOURCES = CreateFilters.cpp

include $(ROOT)/mak/program.mak

tests:

poststarttests:
