ROOT = ../../../..
include $(ROOT)/mak/config.mak
include $(ROOT)/test/config.mak

XMLSCRIPTS = \
    CreateModule01 CreateProvider01 \
    CreateModule02 CreateProvider02 \
    CreateCapability01 CreateCapability02 \
    CreateFilter01 CreateFilter02 CreateFilter03 CreateFilter04 \
    CreateFilter05 CreateFilter06 \
    CreateHandler01 CreateHandler02 CreateHandler03 \
    CreateSubscription01 CreateSubscription02 CreateSubscription03 \
    CreateSubscription04 CreateSubscription05 CreateSubscription06 \
    CreateSubscription07 CreateSubscription08 CreateSubscription09 \
    EnumerateFilters01 \
    EnumerateHandlers01 \
    EnumerateSubscriptions01 \
    ModifyFilter01 \
    ModifyHandler01 \
    ModifySubscription01 ModifySubscription02 \
    ModifySubscription03 ModifySubscription04 \
    DeleteFilter07 DeleteHandler04 \
    DeleteSubscription01 DeleteSubscription02 DeleteSubscription03 \
    DeleteSubscription04 DeleteSubscription05 DeleteSubscription06 \
    DeleteSubscription07 DeleteSubscription08 DeleteSubscription09 \
    DeleteFilter02 DeleteFilter03 DeleteFilter04 \
    DeleteFilter05 DeleteFilter06 \
    DeleteHandler01 DeleteHandler02 DeleteHandler03 \
    CreateHandler09 CreateSubscription14 EnumerateSubscriptions03 \
    DeleteHandler09 EnumerateSubscriptions04 \
    DeleteFilter01 \
    CreateFilter07 CreateFilter08 CreateFilter09 CreateFilter10 \
    CreateFilter11 \
    CreateHandler04 CreateHandler05 CreateHandler06 CreateHandler07 \
    CreateHandler08 \
    CreateSubscription10 CreateSubscription11 CreateSubscription12 \
    CreateSubscription13 \
    CreateFilter12 \
    DeleteCapability02 DeleteProvider02 DeleteModule02 \
    DeleteCapability01 DeleteProvider01 DeleteModule01
#   EnumerateFilters01 EnumerateFilters02 \
#   EnumerateHandlers01 EnumerateHandlers02 \
#   EnumerateSubscriptions01 EnumerateSubscriptions02 \
#   GetFilter01 GetFilter02 GetFilter03 GetFilter04 GetFilter05 GetFilter06 \
#   GetHandler01 GetHandler02 GetHandler03 \
#   GetSubscription01 GetSubscription02 GetSubscription03 \
#   GetSubscription04 GetSubscription05 GetSubscription06 \
#   GetSubscription07 GetSubscription08 GetSubscription09 \
#   CreateModule03 CreateProvider03 \
#   CreateCapability03 \
#   ModifyCapability01 ModifyCapability02 \
#   CreateFilter11 CreateFilter12 \
#   DeleteCapability03 DeleteProvider03 DeleteModule03

include $(ROOT)/test/configend.mak
