include $(PEGASUS_ROOT)/mak/config.mak

DIR = Providers/TestProviders/AlertIndicationProvider

LIBRARY = AlertIndicationProvider

LIBRARIES = \
    pegprovider \
    pegclient \
    pegconfig \
    pegcommon
	
SOURCES = \
	AlertIndicationProviderMain.cpp \
	AlertIndicationProvider.cpp

include $(PEGASUS_ROOT)/mak/dynamic-library.mak
