
ROOT = ../../../..
include $(ROOT)/mak/config.mak
include $(ROOT)/test/config.mak

XMLSCRIPTS = GetInstance52000 GetInstance52001 GetInstance52002 GetInstance52003 GetInstance52005 GetInstance52006

ifeq ($(OS),HPUX)
XMLSCRIPTS += GetInstance52004
endif

include $(ROOT)/test/configend.mak
