
ROOT = ../../../..
include $(ROOT)/mak/config.mak
include $(ROOT)/test/config.mak

XMLSCRIPTS = GetInstance52000 GetInstance52001 GetInstance52002 GetInstance52003 GetInstance52004 GetInstance52005

clean:
	$(RM) $(XMLRESPONSES)

tests: $(XMLRESPONSES)
