ROOT = ../../..
include $(ROOT)/mak/config.mak

LIBRARY = FilesAndDirectories

SOURCE_DIR = Providers/CMPI/FilesAndDirectories

LIBRARIES = \
  pegcommon \
  pegprovider

SOURCES = \
   CWS_PlainFile.c \
   CWS_FileUtils.c \
   CWS_Directory.c \
   CWS_DirectoryContainsFile.c \
   cwsutil.c

include $(ROOT)/mak/library.mak

tests:
