//%LICENSE////////////////////////////////////////////////////////////////
//
// Licensed to The Open Group (TOG) under one or more contributor license
// agreements.  Refer to the OpenPegasusNOTICE.txt file distributed with
// this work for additional information regarding copyright ownership.
// Each contributor licenses this file to you under the OpenPegasus Open
// Source License; you may not use this file except in compliance with the
// License.
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included
// in all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
// OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
// IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
// CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
// TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
// SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//
//////////////////////////////////////////////////////////////////////////
//
//%/////////////////////////////////////////////////////////////////////////////

#include "ConfigPropertyOwner.h"
#include "ConfigPropertyHelp.h"

PEGASUS_NAMESPACE_BEGIN
PEGASUS_USING_STD;

const String STRING_TRUE = "true";
const String STRING_FALSE = "false";

static const char CONFIG_PROP_HELP_NOT_AVAILABLE [] =
    "Help yet not available";
static const char  CONFIG_PROP_HELP_NOT_AVAILABLE_KEY [] =
    "Config.ConfigPropertyOwner.CONFIG_PROP_HELP_NOT_AVAILABLE";

const char  CONFIG_MSG_PATH [] =
    "pegasus/pegasusServer";

// Creates string of form:
//     Config.DefaultPropertyOwner.<propertyName>.DESCRIPTION
String _createKey(const char* propertyName)
{
    String rtn = "Config.ConfigPropertyHelp.";
    rtn.append(propertyName);
    rtn.append(".DESCRIPTION");
    return rtn;
}

String _DescriptionPrefix(const char* description)
{
    String rtn = "Description: ";
    rtn.append(description);
    return rtn;
}

// Temporary function used to output the full text of all messages in the
// configPropertyDescriptionList to a file in a form compatible with
// the message bundle format.  This is used ONLY as a way to generate
// input for the Message bundle rather than to try to manually keep
// the bundle and these files in sync.  Normally disabled and enabled only
// when the text in the table changes.
// To use. Enable this code and execute a single cimconfig -H. This will
// generate both the normal output and the text for the msg bundle. You
// can extract the msg bundle info from this.  Note that this is displayed
// at the client.
// Remove comment from following line to enable generation of info for
// message bundle to std out. Enter cimconfig -H traceComponents to create.
//#define PEGASUS_ENABLE_OUTPUT_OF_DESCRIPTION_INFO
#ifdef PEGASUS_ENABLE_OUTPUT_OF_DESCRIPTION_INFO

void _showCompleteHelpDescriptionTable()
{
    cout <<
    "        // ==========================================================\n"
    "        // Description Messages for ConfigPropertyHelp\n"
    "        //  These Messages do not have a number prefix\n"
    "        //  Generated by enabling ENABLE_OUTPUT_OF_DESCRIPTION_INFO\n"
    "        //  in source file Pegasus/Config/ConfigPropertyOwner.cpp\n"
    "        //  Text in single quotes should not be translated\n"
    "        // ==========================================================\n"
    << endl;

    for (Uint32 i = 0; i < configPropertyDescriptionListSize ; i++)
    {
        String dscrpt = _DescriptionPrefix(
                 configPropertyDescriptionList[i].Description);
        String fixed;
        for (Uint32 j = 0; j < dscrpt.size(); j++)
        {
            switch (dscrpt[j])
            {
                case '\n':
                    fixed.append("\\n\"\n            \"");
                    break;
                default:
                    fixed.append(dscrpt[j]);
            }
        }

        // Output data for the pegasusServer_en.txt file for this
        // key where key includes traceComponent name
        cout << "        " << _createKey(
                    configPropertyDescriptionList[i].name)
             << ":string {\""
             << fixed
             << "\"}"
             << endl << endl;
    }
    cout <<
        "        // END ConfigPropertyHelp Msgs======================" << endl;
}
#endif

// build up the standard propertyInfo containing info from the property
// defined by the provided ConfigProperty
void ConfigPropertyOwner::buildPropertyInfo(const String& name,
    const struct ConfigProperty * configProperty,
    Array<String>& propertyInfo) const
{
    propertyInfo.clear();
    // build propertyInfo String Array.
    propertyInfo.append(configProperty->propertyName);
    propertyInfo.append(configProperty->defaultValue);
    propertyInfo.append(configProperty->currentValue);
    propertyInfo.append(configProperty->plannedValue);
    if (configProperty->dynamic)
        {
            propertyInfo.append(STRING_TRUE);
        }
        else
        {
            propertyInfo.append(STRING_FALSE);
        }
    if (configProperty->externallyVisible)
        {
            propertyInfo.append(STRING_TRUE);
        }
        else
        {
            propertyInfo.append(STRING_FALSE);
        }

    propertyInfo.append(getPropertyHelp(name));
}

// This function provides the default behaviour for PropertyOwners which do
// not override getPropertyHelp() function. Attempts to get a Description
// text from the configPropertyDescriptionList (see ConfigPropertyHelp.cpp)
// for the string and return the data as String.
//
String ConfigPropertyOwner::getPropertyHelp(const String& name) const
{
// This conditional code enables output of the complete table as a part
// if the message bundle.  It should be enabled only for the special condition
// where a developer has modified the table of help info and wants to
// generate a new message bundle. This is only enabled in that single
// condition to generate a new message bundle. NOTE: To use this function
// export PEGASUS_ENABLE_OUTPUT_OF_DESCRIPTION_INFO then make clean; make
// the Config directory.  Then start the server and execute any single
// cimconfig -H command. The message bundle text for the help messages
//  will be output to stdout and  can be captured for insertion into the
// server message bundle.
#ifdef PEGASUS_ENABLE_OUTPUT_OF_DESCRIPTION_INFO
        _showCompleteHelpDescriptionTable();
#endif

    String localPropertyInfo;
    for (Uint32 i = 0; i < configPropertyDescriptionListSize ; i++)
    {
        // Return the complete message in propertyInfo if name found
        if (configPropertyDescriptionList[i].name == name)
        {
            MessageLoaderParms parms(
                    (const char *)_createKey(
                        configPropertyDescriptionList[i].name).getCString(),
                    _DescriptionPrefix(
                        configPropertyDescriptionList[i].Description));
            parms.msg_src_path = CONFIG_MSG_PATH;
            localPropertyInfo.append(MessageLoader::getMessage(parms));
            return localPropertyInfo;
        }
    }

    // Not found, return error.
    MessageLoaderParms parms(CONFIG_PROP_HELP_NOT_AVAILABLE_KEY,
        CONFIG_PROP_HELP_NOT_AVAILABLE);
    parms.msg_src_path = CONFIG_MSG_PATH;
    localPropertyInfo.append(MessageLoader::getMessage(parms));
    return localPropertyInfo;
}

// Returns empty String since this is the default behavior. May be overridden in
// subclasses to supply specific values for entries such as traceComponents,
// etc.  Property owners that do not require anything but the description
// string for help output should not override this function. Normally
// all help should be in the fixed help file (see getPropertyHelp above)
// and only information that might vary by system version or server compile
// addressed through PropertyHelpSupplement. This would allow a particular
// server configuration to, for example, list the selection options available.
String ConfigPropertyOwner::getPropertyHelpSupplement(const String& name) const
{
    return "";
}

PEGASUS_NAMESPACE_END
