# Wbemexec test associated w/GetQualifier
#

ROOT = ../../../..
include $(ROOT)/mak/config.mak
include $(ROOT)/test/config.mak

XMLSCRIPTS = GetQualifier37002

BROKERNXMLSCRIPTS = GetQualifier37000 

ifndef SECURITY_ENABLED
XMLSCRIPTS += \
          GetQualifier37001
endif

include $(ROOT)/test/configend.mak
