# Wbemexec test associated w/GetQualifier
#

ROOT = ../../../..
include $(ROOT)/mak/config.mak
include $(ROOT)/test/config.mak

XMLSCRIPTS = GetQualifier37000 GetQualifier37001

clean:
	$(RM) $(XMLRESPONSES)


tests: $(XMLRESPONSES)
