# Wbemexec test associated w/GetQualifier
#

ROOT = ../../../..
include $(ROOT)/mak/config.mak
include $(ROOT)/test/config.mak

XMLSCRIPTS = GetQualifier37001 GetQualifier37002

BROKERNXMLSCRIPTS = GetQualifier37000 

clean:
	$(RM) $(XMLRESPONSES)


tests: $(XMLRESPONSES)
