ROOT = ../../../../..
DIR = Pegasus/Common/tests/ClassDecl
include $(ROOT)/mak/config.mak
include ../libraries.mak

PROGRAM = TestClassDecl
SOURCES = ClassDecl.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)

poststarttests:
