ROOT = $(PEGASUS_ROOT)

include $(ROOT)/mak/config.mak
include $(ROOT)/test/config.mak

XMLSCRIPTS =  \
   EnumerateDirNames10000 \
   EnumerateDir10001 \
   GetDirInstance10002 \
   DeleteDirInstance10003 \
   AssocDirNames12001 \
   ReferenceDirNames12002 \
   PlainFileMethodCall11001

include $(ROOT)/test/configend.mak

poststarttests:

