ROOT = ../../../../..
DIR = Pegasus/Common/tests/InstanceDecl
include $(ROOT)/mak/config.mak
include ../libraries.mak

PROGRAM = InstanceDecl
SOURCES = InstanceDecl.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)
