#!/bin/bash

##==============================================================================
##
## vxexec
## 
## Usage:
##
##     vxexec -c command
##
## Synopsis:
##
##     This script executes a single command under vxsim.
##
## Examples:
##
##     vxexec -c TestString.vxe
##
##==============================================================================

copt=$1

if [ "$1" = "-c" ]
then
    shift
fi

if [ ! -d "$PEGASUS_ROOT" ]
then
    echo "PEGASUS_ROOT must refer to an actual directory"
    exit 1
fi

rm -rf vxexec.tmp
echo "################################################################################" >> vxexec.tmp
echo "##" >> vxexec.tmp
echo "## $*" >> vxexec.tmp
echo "##" >> vxexec.tmp
echo "################################################################################" >> vxexec.tmp
echo "$*" >> vxexec.tmp
echo "C reboot(1)" >> vxexec.tmp

VXWORKS=$PEGASUS_ROOT/vxworks/image/vxWorks

#vxsim -tmpdir /tmp -f $VXWORKS -exitOnError -s vxexec.tmp
vxsim -tmpdir /tmp -f $VXWORKS -s vxexec.tmp

rm -f vxexec.tmp
