ROOT = ../../../../..
DIR = Pegasus/Client/tests/Client
include $(ROOT)/mak/config.mak
include ../libraries.mak

EXTRA_INCLUDES = $(SYS_INCLUDES) $(ACE_INCLUDES)

PROGRAM = Client

SOURCES = Client.cpp

include $(ROOT)/mak/program.mak

tests:
