ROOT = ../../../../..
DIR = Pegasus/Common/tests/Base64
include $(ROOT)/mak/config.mak
include ../libraries.mak

PROGRAM = TestBase64
SOURCES = Base64.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)
