[Abstract, Version("2.6.0"), Description (
	"An abstract class for WBEM services such as the "
	"ObjectManager (CIM Server), Providers, Protocol adapters, "
	"or other pluggable components. A type of CIM_Service"
	"that provides associated capabilities and details about the "
	"communication capabilities, namespaces, etc. for a specific "
	"WBEMService.")]
class CIM_WBEMService : CIM_Service
{
};

[Version("2.7.0"), Description ( "A CIM_Provider is a type of CIM_WBEMService "
	"that instruments one or more aspects of the CIM Schema.  A"
	"CIM_Provider operates at the request of the "
	"CIM_ObjectManager to perform operations on CIM objects. ")]
class CIM_Provider : CIM_WBEMService
{
        [Key, Override("Name"), Description ("A human-readable name that"
         "uniquely identifies the provider within a system")]
    String Name;
        [Description ("An implementation specific string that "
         "identifies the location of the provider")]
    String Location;
};

[Version("2.7.0"), Description (
	"This class defines the capabilities of the associated"
	"provider.")]
class CIM_ProviderCapabilities {

        [Key, Description (
         "A identifying string to uniquely label an instance of "
         "Capabilities.") ]
     string InstanceID;

        [Required, Description (
         "The ClassName lists the class for which the associated "
         "Provider supplies instances, associations or indications "
         "information. The ClassInNamespace association provides "
         "namespace information for the listed class names. ")]
     string ClassName;

        [Description (
         "ProviderType enumerates the kind of provider"
         "capabilities defined for the associated Provider. "),
         ArrayType ("Indexed"),
         ValueMap {"1", "2", "3", "4"},
         Values {"Other", "Instance", "Association", "Indication" }]
    uint16 ProviderType[];

        [Description (
         "Type of provider capability when \"Other\" is included "
         "in ProviderType property array." ),
         ModelCorrespondence {"CIM_ProviderCapabilities.ProviderType"} ]
    string OtherProviderType ;

        [Description (
         "SupportedProperties lists the properties supported "
         "by this provider.  If this array is empty, the provider "
         "MUST support all of the properties defined in the class. "
         "If the provider does not support all of the properties, "
         "the properties supported MUST be included in the array. "
         "The array entry format is <PropertyName>"),
         ModelCorrespondence {"CIM_ProviderCapabilities.ClassName"} ]
    string SupportedProperties[];

        [Description (
         "SupportedMethods lists the methods supported by this "
         "provider. If this array is empty, the provider MUST "
         "support all the methods defined in the class. "
         "If the provider does not support all the methods, "
         "the methods supported MUST be included in the array."
         "The array entry format is <MethodName>"),
         ModelCorrespondence {"CIM_ProviderCapabilities.ClassName "} ]
    string SupportedMethods [];
};

[Association, Version("2.7.0"), Description (
	"ProviderElementCapabilities is an association describing "
	"the Capabilities that are supported by a Provider. ")]
class CIM_ProviderElementCapabilities {

        [key,
		Description ("The CIM Provider") ]
    CIM_Provider REF ManagedElement;

        [key,
		Description ("The CIM Provider Capabilities.") ]
    CIM_ProviderCapabilities REF Capabilities;
};
