
ROOT = ../../../..

include $(ROOT)/mak/config.mak
include $(ROOT)/test/config.mak

XMLSCRIPTS = AssociatorNames30000 AssociatorNames30001 AssociatorNames30002 AssociatorNames30003 AssociatorNames30004 AssociatorNames30005 AssociatorNames30006 AssociatorNames30007 AssociatorNames30008

include $(ROOT)/test/configend.mak

