
ROOT = ../../../..

include $(ROOT)/mak/config.mak
include $(ROOT)/test/config.mak

XMLSCRIPTS = AssociatorNames30000 

defects = AssociatorNames30001 AssociatorNames30002

clean:
	$(RM) $(XMLRESPONSES)


tests: $(XMLRESPONSES)


