
ROOT = ../../../..

include $(ROOT)/mak/config.mak
include $(ROOT)/test/config.mak

XMLSCRIPTS = AssociatorNames30000 

defects = AssociatorNames30001 AssociatorNames30002

include $(ROOT)/test/configend.mak

