include ../libraries.mak

DIR = Pegasus/Common/tests/DynamicLibrary

include $(PEGASUS_ROOT)/mak/config.mak

LOCAL_DEFINES = -DPEGASUS_INTERNALONLY

SOURCES = DynamicLibrary.cpp

PROGRAM = TestDynamicLibrary

include $(PEGASUS_ROOT)/mak/program.mak

tests:

poststarttests:
