# Wbemexec test associated w/CreateClass
#

ROOT = ../../../..
include $(ROOT)/mak/config.mak
include $(ROOT)/test/config.mak

XMLSCRIPTS = CreateClass34000 CreateClass34001 CreateClass34002 CreateClass34003 CreateClass34004 CreateClass34005 CreateClass34006 CreateClass34007 CreateClass34008 

clean:
	@ $(RM) $(XMLRESPONSES)


tests: $(XMLRESPONSES)	








