# Wbemexec test associated w/CreateClass
#

ROOT = ../../../..
include $(ROOT)/mak/config.mak
include $(ROOT)/test/config.mak

XMLSCRIPTS = CreateClass34000 CreateClass34001 CreateClass34002 CreateClass34004 CreateClass34005 CreateClass34006 CreateClass34007 CreateClass34008 

ifndef SECURITY_ENABLED
XMLSCRIPTS += \
              CreateClass34003             
endif

include $(ROOT)/test/configend.mak
