ROOT = ../../../../..
DIR = Pegasus/IndicationService/tests/CreateSubscriptions
include $(ROOT)/mak/config.mak
include ../libraries.mak

EXTRA_INCLUDES = $(SYS_INCLUDES)

LOCAL_DEFINES = -DPEGASUS_INTERNALONLY

PROGRAM = CreateSubscriptions

SOURCES = CreateSubscriptions.cpp

include $(ROOT)/mak/program.mak

tests:

poststarttests:
