ROOT = ../../../..

DIR = Providers/sample/PropertyProvider

include $(ROOT)/mak/config.mak

LIBRARY = SamplePropertyProvider

LIBRARIES = \
	 pegcommon \
	 pegprovider
	
SOURCES = \
   PropertyProviderMain.cpp \
   PropertyProvider.cpp

include $(ROOT)/mak/library.mak

tests:
