ROOT = ../../../..

DIR = Providers/TestProviders/PG_TestPropertyTypes

include $(ROOT)/mak/config.mak

LIBRARY = PG_TestPropertyTypes

LIBRARIES = \
	pegcommon \
	pegprovider

SOURCES = \
   PG_TestPropertyTypes.cpp

include $(ROOT)/mak/dynamic-library.mak

tests:
install:
