ROOT = ../../../..

DIR = Providers/TestProviders/PG_TestPropertyTypes

include $(ROOT)/mak/config.mak

LIBRARY = PG_TestPropertyTypes

LIBRARIES = \
    pegprovider \
    pegclient \
    pegconfig \
    pegcommon

SOURCES = \
   PG_TestPropertyTypes.cpp

include $(ROOT)/mak/dynamic-library.mak

tests:
install:
