include $(PEGASUS_ROOT)/mak/config.mak

DIRS = \
	InstanceProvider \
	MethodProvider \
	IndicationProvider \
	SNMPIndicationProvider \
	ProcessIndicationProvider \
	AlertIndicationProvider \
	RT_Indication \
	FamilyProvider \
	FamilyProvider/tests \
	LocalizedProvider \
	LocalizedProvider/msg

include $(PEGASUS_ROOT)/mak/recurse.mak
