ROOT=../../../../../../../..

include $(ROOT)/mak/config.mak
include $(ROOT)/test/config.mak

DIRS = \
	Load\
	CreateInstance \
	GetInstance\
	EnumerateInstanceNames\
	EnumerateInstances\
	ErrorXml\
	ModifyInstance\
	DeleteInstance \
	InvokeMethod


# Property

# These tests are not re-runnable
#	ModifyClass\
#	DeleteClass
#	Headers\

include $(ROOT)/mak/recurse.mak

