ROOT = ../../../..

DIR = Pegasus/Provider/CMPI

include $(ROOT)/mak/config.mak

LOCAL_DEFINES = -DPEGASUS_CMPI_PROVIDER_INTERNAL -DPEGASUS_INTERNALONLY

LIBRARY = cmpiCppImpl

SOURCES = \
    CmpiImpl.cpp

include $(ROOT)/mak/library.mak
include $(ROOT)/mak/install.mak
