ROOT = ../../../../..
DIR = Pegasus/Common/tests/String
include $(ROOT)/mak/config.mak
include ../libraries.mak

PROGRAM = TestString
SOURCES = String.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)
