ROOT = $(PEGASUS_ROOT)
DIR = Pegasus/Client/tests/slp
include $(ROOT)/mak/config.mak
include ../libraries.mak

EXTRA_INCLUDES = $(SYS_INCLUDES)

PROGRAM = TestSLPClient

SOURCES = slpclient.cpp

include $(ROOT)/mak/program.mak

tests:

poststarttests:
