include $(PEGASUS_ROOT)/mak/config.mak

DIR = Pegasus/Server/tests/Lockable

LIBRARIES = \
	pegcommon

LOCAL_DEFINES = -DPEGASUS_INTERNALONLY

PROGRAM = TestLockable

SOURCES = Lockable.cpp

include $(PEGASUS_ROOT)/mak/program.mak

tests:
