# Wbemexec test associated w/EnumerateClassNames
#

ROOT = ../../../..
include $(ROOT)/mak/config.mak
include $(ROOT)/test/config.mak

XMLSCRIPTS = EnumerateClassNames20001 EnumerateClassNames20002 EnumerateClassNames20003

clean:
	$(RM) $(XMLRESPONSES)


tests: $(XMLRESPONSES)
