include $(PEGASUS_ROOT)/mak/config.mak

DIR = Pegasus/Server/tests/ProviderFacade

LIBRARIES = \
	pegcommon \
	pegprovider \
	pegprovidermanager

PROGRAM = TestProviderFacade

SOURCES = ProviderFacade.cpp

include $(PEGASUS_ROOT)/mak/program.mak

tests:
