ROOT = ../../..
include $(ROOT)/mak/config.mak

LIBRARY = SampleInstanceProvider

SOURCE_DIR = Providers/DefaultC++/InstanceProvider

LIBRARIES = \
  pegcommon \
  pegprovider

SOURCES = \
        InstanceProviderMain.cpp \
        InstanceProvider.cpp

include $(ROOT)/mak/library.mak

tests:
