ROOT = ../../../../..
DIR = Pegasus/Repository/tests/InheritanceTree
include $(ROOT)/mak/config.mak
include ../libraries.mak

LOCAL_DEFINES = -DPEGASUS_INTERNALONLY

PROGRAM = InheritanceTree
SOURCES = InheritanceTree.cpp

include $(ROOT)/mak/program.mak

tests:
	InheritanceTree

poststarttests:

