//%/////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2000, 2001, 2002 BMC Software, Hewlett-Packard Company, IBM,
// The Open Group, Tivoli Systems
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to
// deal in the Software without restriction, including without limitation the
// rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// THE ABOVE COPYRIGHT NOTICE AND THIS PERMISSION NOTICE SHALL BE INCLUDED IN
// ALL COPIES OR SUBSTANTIAL PORTIONS OF THE SOFTWARE. THE SOFTWARE IS PROVIDED
// "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
// LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
// PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
// ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
// WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//
//==============================================================================
//
// Author: Mike Brasher (mbrasher@bmc.com)
//
// Modified By: Nag Boranna, Hewlett-Packard Company (nagaraja_boranna@hp.com)
//              Karl Schopmeyer (k.schopmeyer@opengroup.org)
//              Jenny Yu, Hewlett-Packard Company (jenny_yu@hp.com)
//              Carol Ann Krug Graves, Hewlett-Packard Company
//                (carolann_graves@hp.com)
//              Roger Kumpf, Hewlett-Packard Company (roger_kumpf@hp.com)
//
//%/////////////////////////////////////////////////////////////////////////////

#ifndef Pegasus_Exception_h
#define Pegasus_Exception_h

#include <Pegasus/Common/Config.h>
#include <Pegasus/Common/String.h>
#include <Pegasus/Common/CIMStatusCode.h>
#include <Pegasus/Common/Linkage.h>

PEGASUS_NAMESPACE_BEGIN

// ATTN this documentation is incomplete

/** Class Exception

<p>The <tt>Exception</tt> class is the parent class for all
exceptions that can be generated by any component of the
Pegasus infrastructure. It includes not only the CIM exceptions
that are defined by the DMTF, but also various exceptions that
may occur during the processing of functions called by clients
and providers.</p>
*/
class PEGASUS_COMMON_LINKAGE Exception
{
public:

    Exception(const String& message);

    virtual ~Exception();

    const String& getMessage() const;

protected:

    String _message;
};


// ATTN: P3  KS documentation Required
class PEGASUS_COMMON_LINKAGE IndexOutOfBoundsException : public Exception
{
public:
    IndexOutOfBoundsException();
};

// ATTN: P3  KS documentation Required
class PEGASUS_COMMON_LINKAGE AlreadyExistsException : public Exception
{
public:
    AlreadyExistsException(const String& message);
};

// ATTN: P3  KS documentation Required
class PEGASUS_COMMON_LINKAGE InvalidNameException : public Exception
{
public:
    InvalidNameException(const String& name);
};

// ATTN: P3  KS documentation Required
class PEGASUS_COMMON_LINKAGE InvalidNamespaceNameException : public Exception
{
public:
    InvalidNamespaceNameException(const String& name);
};

// ATTN: P3  KS documentation Required
class PEGASUS_COMMON_LINKAGE UninitializedHandleException : public Exception
{
public:
    UninitializedHandleException();
};

class PEGASUS_COMMON_LINKAGE UninitializedObjectException : public Exception
{
public:
    UninitializedObjectException();
};

// ATTN: P3  KS documentation Required
class PEGASUS_COMMON_LINKAGE ExpectedReferenceValueException : public Exception
{
public:
    ExpectedReferenceValueException();
};

// ATTN: P3  KS documentation Required
class PEGASUS_COMMON_LINKAGE MissingReferenceClassNameException : public Exception
{
public:
    MissingReferenceClassNameException();
};

// ATTN: P3  KS documentation Required
class PEGASUS_COMMON_LINKAGE TypeMismatchException : public Exception
{
public:
    TypeMismatchException();
};

// ATTN: P3  KS documentation Required
class PEGASUS_COMMON_LINKAGE CIMValueInvalidTypeException : public Exception
{
public:
    CIMValueInvalidTypeException();
};

// ATTN: P3  KS documentation Required
class PEGASUS_COMMON_LINKAGE DynamicCastFailedException : public Exception
{
public:
    DynamicCastFailedException();
};

class PEGASUS_COMMON_LINKAGE InvalidDateTimeFormatException : public Exception
{
public:
    InvalidDateTimeFormatException();
};

class PEGASUS_COMMON_LINKAGE IncompatibleTypesException : public Exception
{
public:
    IncompatibleTypesException();
};

class PEGASUS_COMMON_LINKAGE MalformedObjectNameException : public Exception
{
public:
    MalformedObjectNameException(const String& objectName);
};

class PEGASUS_COMMON_LINKAGE BindFailedException : public Exception
{
public:
    BindFailedException(const String& message);
};

class PEGASUS_COMMON_LINKAGE InvalidLocatorException : public Exception
{
public:
    InvalidLocatorException(const String& locator);
};

class PEGASUS_COMMON_LINKAGE CannotCreateSocketException : public Exception
{
public:
    CannotCreateSocketException();
};

class PEGASUS_COMMON_LINKAGE CannotConnectException : public Exception
{
public:
    CannotConnectException(const String& locator);
};

class PEGASUS_COMMON_LINKAGE UnexpectedFailureException : public Exception
{
public:
    UnexpectedFailureException();
};

class PEGASUS_COMMON_LINKAGE AlreadyConnectedException: public Exception
{
public:
    AlreadyConnectedException();
};

class PEGASUS_COMMON_LINKAGE NotConnectedException: public Exception
{
public:
    NotConnectedException();
};

class PEGASUS_COMMON_LINKAGE ConnectionTimeoutException: public Exception
{
public:
    ConnectionTimeoutException();
};

class PEGASUS_COMMON_LINKAGE SSLException: public Exception
{
public:
    SSLException(const String& message);
};


class CIMExceptionRep;

/** The CIMException defines the CIM exceptions that are formally defined in
    the CIM Operations over HTTP specification.
*/
class PEGASUS_COMMON_LINKAGE CIMException : public Exception
{
public:

    CIMException(
	CIMStatusCode code = CIM_ERR_SUCCESS,
	const String& message = String::EMPTY);

    CIMException(const CIMException & cimException);

    virtual ~CIMException();

    CIMException& operator=(const CIMException & cimException);

    CIMStatusCode getCode() const;

protected:

    CIMExceptionRep * _rep;
};


PEGASUS_NAMESPACE_END

#endif /* Pegasus_Exception_h */
