ROOT = ../../..

DIR = Pegasus/Common

include $(ROOT)/mak/config.mak

LOCAL_DEFINES = -DPEGASUS_COMMON_INTERNAL 

LIBRARY = pegcommon

SOURCES = \
    Array.cpp \
    CGIQueryString.cpp \
    Channel.cpp \
    Char16.cpp \
    Config.cpp \
    CIMClass.cpp \
    CIMClassRep.cpp \
    CIMDateTime.cpp \
    CIMFlavor.cpp \
    CIMInstance.cpp \
    CIMInstanceRep.cpp \
    CIMMethod.cpp \
    CIMMethodRep.cpp \
    CIMName.cpp \
    CIMOperations.cpp \
    CIMParameter.cpp \
    CIMParameterRep.cpp \
    CIMProperty.cpp \
    CIMPropertyRep.cpp \
    CIMQualifier.cpp \
    CIMQualifierDecl.cpp \
    CIMQualifierDeclRep.cpp \
    CIMQualifierList.cpp \
    CIMQualifierNames.cpp \
    CIMQualifierRep.cpp \
    CIMReference.cpp \
    CIMScope.cpp \
    CIMType.cpp \
    CIMValue.cpp \
    DeclContext.cpp \
    Destroyer.cpp \
    Dir.cpp \
    Exception.cpp \
    FileSystem.cpp \
    Formatter.cpp \
    HashTable.cpp \
    Indentor.cpp \
    Logger.cpp \
    Memory.cpp \
    OptionManager.cpp \
    Pair.cpp \
    Selector.cpp \
    Service.cpp \
    Sharable.cpp \
    Stack.cpp \
    Stopwatch.cpp \
    String.cpp \
    System.cpp \
    TCPChannel.cpp \
    TimeValue.cpp \
    Union.cpp \
    XmlParser.cpp \
    XmlReader.cpp \
    XmlWriter.cpp \

include $(ROOT)/mak/library.mak
