#//%2005////////////////////////////////////////////////////////////////////////
#//
#// Copyright (c) 2000, 2001, 2002 BMC Software; Hewlett-Packard Development
#// Company, L.P.; IBM Corp.; The Open Group; Tivoli Systems.
#// Copyright (c) 2003 BMC Software; Hewlett-Packard Development Company, L.P.;
#// IBM Corp.; EMC Corporation, The Open Group.
#// Copyright (c) 2004 BMC Software; Hewlett-Packard Development Company, L.P.;
#// IBM Corp.; EMC Corporation; VERITAS Software Corporation; The Open Group.
#// Copyright (c) 2005 Hewlett-Packard Development Company, L.P.; IBM Corp.;
#// EMC Corporation; VERITAS Software Corporation; The Open Group.
#//
#// Permission is hereby granted, free of charge, to any person obtaining a copy
#// of this software and associated documentation files (the "Software"), to
#// deal in the Software without restriction, including without limitation the
#// rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
#// sell copies of the Software, and to permit persons to whom the Software is
#// furnished to do so, subject to the following conditions:
#// 
#// THE ABOVE COPYRIGHT NOTICE AND THIS PERMISSION NOTICE SHALL BE INCLUDED IN
#// ALL COPIES OR SUBSTANTIAL PORTIONS OF THE SOFTWARE. THE SOFTWARE IS PROVIDED
#// "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
#// LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
#// PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
#// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
#// ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
#// WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#//
#//==============================================================================
##############################################################
# Requires GNU Bison 1.35 and bison.simple
##############################################################
export BISON_SIMPLE := bison.simple
CC=cl.exe
LINKER=link

ifdef DEBUG
CFLAGS=/nologo /Od /D "WIN32" /D "_DEBUG" /Gm /EHsc /RTC1 /MDd /W3 /c /Zi /TC
LDFLAGS=/nologo /dll /debug
else
CFLAGS=/nologo /O2 /D "WIN32" /EHsc /MD /W3 /c /TC
LDFLAGS=/nologo /dll
endif

LIBS=Ws2_32.lib
LEX=flex
YACC=bison

all: slp_client.dll

OBJECTS=slp_client.obj lslp-windows.obj l_attr.obj  y_attr.obj l_url.obj y_url.obj l_filter.obj y_filter.obj

##############################################################
# 1. slp_client.c
##############################################################
slp_client.obj : slp_client.c
	$(CC) $(CFLAGS) $<

##############################################################
# 2. lslp-windows.c
##############################################################
lslp-windows.obj : ../lslp-windows.c
	$(CC) $(CFLAGS) $<

##############################################################
# 3. bison -oy_attr.c -pattr -v -d attr.y
##############################################################
y_attr.c : attr.y 
	$(YACC) -o$@ -p$(basename $<) -v -d $<

##############################################################
# 4. y_attr.c
##############################################################
y_attr.obj : y_attr.c
	$(CC) $(CFLAGS) $<

##############################################################
# 5. flex -p -v -ol_attr.c -Pattr attr.l
##############################################################
l_attr.c : attr.l
	$(LEX) -p -v -o$@ -P$(basename $<) $<

##############################################################
# 6. l_attr.c
##############################################################
l_attr.obj : l_attr.c
	$(CC) $(CFLAGS) $<

##############################################################
# 7. bison -oy_url.c -purl -v -d url.y
##############################################################
y_url.c : url.y
	$(YACC) -o$@ -p$(basename $<) -v -d $<

##############################################################
# 8. y_url.c
##############################################################
y_url.obj : y_url.c
	$(CC) $(CFLAGS) $<

##############################################################
# 9. flex -p -v -ol_url.c -Pattr url.l
##############################################################
l_url.c : url.l
	$(LEX) -p -v -o$@ -P$(basename $<) $<

##############################################################
# 10. l_url.c
##############################################################
l_url.obj : l_url.c
	$(CC) $(CFLAGS) $<

##############################################################
# 11. bison -ol_filter.c -pfilter -v -d l_filter.y
##############################################################
y_filter.c : filter.y
	$(YACC) -o$@ -p$(basename $<) -v -d $<

##############################################################
# 12. l_filter.c
##############################################################
y_filter.obj : y_filter.c
	$(CC) $(CFLAGS) $<

##############################################################
# 13. flex -p -v -ol_filter.c -Pfilter filter.l
##############################################################
l_filter.c : filter.l
	$(LEX) -p -v -o$@ -P$(basename $<) $<

##############################################################
# 14. l_filter.c
##############################################################
l_filter.obj : l_filter.c
	$(CC) $(CFLAGS) $<

##############################################################
# 15. Link the library
##############################################################
slp_client.dll : $(OBJECTS)
	$(LINKER) $(LDFLAGS) -out:$@ $(OBJECTS) $(LIBS)

clean:
	$(RM) l_attr.c y_attr.c l_url.c y_url.c l_filter.c y_filter.c *.dll $(OBJECTS) *.pdb *.idb *.ilk *.exp *.lib

