ROOT = ../../../../../..
DIR = Pegasus/Common/tests/Service/InstallService
include $(ROOT)/mak/config.mak

EXTRA_INCLUDES = $(SYS_INCLUDES)

LOCAL_DEFINES = -DPEGASUS_INTERNALONLY

PROGRAM = TestInstallService

SOURCES = InstallService.cpp

include $(ROOT)/mak/program.mak

tests:
