ROOT = ../../..
include $(ROOT)/mak/config.mak

LIBRARY = SampleIndicationProvider

SOURCE_DIR = Providers/DefaultC++/IndicationProvider

LIBRARIES = \
  pegcommon \
  pegprovider

SOURCES = \
        IndicationProviderMain.cpp \
        IndicationProvider.cpp

include $(ROOT)/mak/library.mak

tests:
