ROOT = ../../../..

DIR = Providers/TestProviders/ClientProvider

include $(ROOT)/mak/config.mak

LIBRARY = TestClientProvider

LIBRARIES = \
	 pegcommon \
	 pegclient \
	 pegprovider
	
SOURCES = \
   ClientProviderMain.cpp \
   ClientProvider.cpp

include $(ROOT)/mak/library.mak

tests:
