#!/bin/sh
#%/////////////////////////////////////////////////////////////////////////////
#
# Copyright (c) 2000, 2001, 2002 BMC Software, Hewlett-Packard Company, IBM,
# The Open Group, Tivoli Systems
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# THE ABOVE COPYRIGHT NOTICE AND THIS PERMISSION NOTICE SHALL BE INCLUDED IN
# ALL COPIES OR SUBSTANTIAL PORTIONS OF THE SOFTWARE. THE SOFTWARE IS PROVIDED
# "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
# LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
# PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
# ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
#==============================================================================
#
# Author: Warren Otsuka (warren.otsuka@hp.com)
#
# Modified By:
#
#%/////////////////////////////////////////////////////////////////////////////


#
# WARNING:
# This script can be run in order to re-create the repository.
# It will REMOVE the entire contents of any existing repository
# first, so care should be used when running this.
#

#
# GET RID OF THE OLD REPOSITORY ...
# Actually, you need to do this by hand without cimserver
# running, and then start up cimserver again.
#

##### rm -rf /var/opt/wbem/repository

#
# CREATE CLEAN REPOSITORY ...
#

PG_SCHEMA_VER=20
CIM_SCHEMA_VER=25

MOF_PATH=/etc/opt/wbem/mof

#
# The following are for the InterOp Namespace
#

INTEROPNS=root/PG_InterOp

/opt/wbem/bin/cimmof -I$MOF_PATH -n$INTEROPNS $MOF_PATH/CIM_Core$CIM_SCHEMA_VER.mof
/opt/wbem/bin/cimmof -I$MOF_PATH -n$INTEROPNS $MOF_PATH/InterOpSchema.mof

#
# The following are for the Internal Namespace
#

INTERNALNS=root/PG_Internal

/opt/wbem/bin/cimmof -I$MOF_PATH -n$INTERNALNS $MOF_PATH/CIM_Qualifiers$CIM_SCHEMA_VER.mof
/opt/wbem/bin/cimmof -I$MOF_PATH -n$INTERNALNS $MOF_PATH/InternalSchema.mof

#
# The following are for the ManagedSystem Namespace
#

# ATTN:    MANAGEDSYSTEMNS=root/PG_ManagedSystem
MANAGEDSYSTEMNS=root/cimv2

/opt/wbem/bin/cimmof -I$MOF_PATH -n$MANAGEDSYSTEMNS $MOF_PATH/CIM_Schema$CIM_SCHEMA_VER.mof
/opt/wbem/bin/cimmof -I$MOF_PATH -n$MANAGEDSYSTEMNS $MOF_PATH/ManagedSystemSchema.mof
/opt/wbem/bin/cimmof -I$MOF_PATH -n$INTEROPNS $MOF_PATH/ManagedSystemSchemaR.mof
