ROOT = ../../../../..
DIR = Pegasus/Common/tests/Connector
include $(ROOT)/mak/config.mak
include ../libraries.mak

PROGRAM = Connector
SOURCES = Connector.cpp

include $(ROOT)/mak/program.mak

tests:
