
ROOT = ../../../..

include $(ROOT)/mak/config.mak
include $(ROOT)/test/config.mak

XMLSCRIPTS = EnumerateInstanceNames25000 EnumerateInstanceNames25001 EnumerateInstanceNames25002

include $(ROOT)/test/configend.mak
