ROOT = ../../../..

DIR = Providers/sample/InstanceProvider

include $(ROOT)/mak/config.mak

LIBRARY = SampleInstanceProvider

LIBRARIES = \
	pegcommon \
	pegprovider
	
SOURCES = \
	InstanceProviderMain.cpp \
	InstanceProvider.cpp

include $(ROOT)/mak/library.mak

tests:
