ROOT = ../../../..

DIR = Providers/sample/HelloWorldProvider

include $(ROOT)/mak/config.mak

LIBRARY = HelloWorldProvider

LIBRARIES = \
	 pegcommon \
	 pegprovider
	
SOURCES = \
   HelloWorldProviderMain.cpp \
   HelloWorldProvider.cpp

include $(ROOT)/mak/library.mak

tests:
