ROOT = ../../../..

include $(ROOT)/mak/config.mak

DIRS = \
    CreateFilters \
    CreateHandlers \
    CreateSubscriptions \
    IndicationProcess \
    DisableEnable \
    DisableEnable2 \
    ProcessIndication

include $(ROOT)/mak/recurse.mak
