ROOT = ../../../..

include $(ROOT)/mak/config.mak

DIRS = \
    CreateFilters \
    CreateHandlers \
    CreateSubscriptions \
    IndicationProcess \
    DisableEnable

include $(ROOT)/mak/recurse.mak
