ROOT = ../../../..

include $(ROOT)/mak/config.mak

DIRS = \
    IndicationProcess \
    DisableEnable \
    DisableEnable2 \
    ProcessIndication \
    Subscription

include $(ROOT)/mak/recurse.mak
