# Wbemexec test associated w/DeleteClass
#

ROOT = ../../../..
include $(ROOT)/mak/config.mak
include $(ROOT)/test/config.mak

XMLSCRIPTS = DeleteClass36000 DeleteClass36001 DeleteClass36003 DeleteClass36004 DeleteClass36007 DeleteClass36008 DeleteClass36009

ifndef SECURITY_ENABLED
XMLSCRIPT += \
            DeleteClass36002
endif

include $(ROOT)/test/configend.mak
