# Wbemexec test associated w/DeleteClass
#

ROOT = ../../../..
include $(ROOT)/mak/config.mak
include $(ROOT)/test/config.mak

XMLSCRIPTS = DeleteClass36000 DeleteClass36001 DeleteClass36002 DeleteClass36003 DeleteClass36004 DeleteClass36007 DeleteClass36008 DeleteClass36009

clean:
	$(RM) $(XMLRESPONSES)


tests: $(XMLRESPONSES)
