
ROOT = ../../../..

include $(ROOT)/mak/config.mak
include $(ROOT)/test/config.mak

XMLSCRIPTS = EnumerateClasses42000 EnumerateClasses42001 EnumerateClasses42002

include $(ROOT)/test/configend.mak
