ROOT = ../../../../..
DIR = Pegasus/Common/tests/ConfigTest
include $(ROOT)/mak/config.mak
include ../libraries.mak

PROGRAM = ConfigTest
SOURCES = ConfigTest.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)
