ROOT = ../../../../..
DIR = Pegasus/Common/tests/Config
include $(ROOT)/mak/config.mak
include ../libraries.mak

PROGRAM = TestConfig
SOURCES = Config.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)

poststarttests: 
