ROOT = ../../../../..
DIR = Pegasus/Client/tests/GetInstance
include $(ROOT)/mak/config.mak
include ../libraries.mak

EXTRA_INCLUDES = $(SYS_INCLUDES)

PROGRAM = GetInstance

SOURCES = GetInstance.cpp

include $(ROOT)/mak/program.mak

tests:

poststarttests:
