
ROOT = ../../../..

include $(ROOT)/mak/config.mak
include $(ROOT)/test/config.mak

XMLSCRIPTS = EnumerateQualifiers31001

BROKENXMLSCRIPTS = EnumerateQualifiers31000

clean:
	$(RM) $(XMLRESPONSES)


tests: $(XMLRESPONSES)
