
ROOT = ../../../..

include $(ROOT)/mak/config.mak
include $(ROOT)/test/config.mak

XMLSCRIPTS = EnumerateQualifiers31000 EnumerateQualifiers31001

clean:
	$(RM) $(XMLRESPONSES)


tests: $(XMLRESPONSES)
