include $(PEGASUS_ROOT)/mak/config.mak

DIR = Pegasus/Server/tests/ProviderManager

LIBRARIES = \
	pegcommon \
	pegprovider \
	pegprovidermanager

LOCAL_DEFINES = -DPEGASUS_INTERNALONLY

PROGRAM = TestProviderManager

SOURCES = ProviderManager.cpp

include $(PEGASUS_ROOT)/mak/program.mak

tests:
