ROOT = ../../../../..
DIR = Pegasus/Common/tests/DQueue
include $(ROOT)/mak/config.mak
include ../libraries.mak

PROGRAM = DQueue
SOURCES = DQueue.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)
