ROOT = ../../../../..
DIR = Pegasus/Client/tests/DeleteNamespace
include $(ROOT)/mak/config.mak
include ../libraries.mak

EXTRA_INCLUDES = $(SYS_INCLUDES)

PROGRAM = DeleteNamespace

SOURCES = DeleteNamespace.cpp

include $(ROOT)/mak/program.mak

tests:

clean:

poststarttests: 
	$(PROGRAM)
