ROOT = ../../../..

DIR = /Providers/TestProviders/InstanceProvider

include $(ROOT)/mak/config.mak

LIBRARY = TestInstanceProvider

LIBRARIES = \
	pegcommon \
	pegprovider

SOURCES = \
	TestInstanceProviderMain.cpp \
	TestInstanceProvider.cpp

include $(ROOT)/mak/library.mak

tests:

install:
