ROOT = ../../../../..
DIR = Pegasus/Common/tests/Assoc
include $(ROOT)/mak/config.mak
include ../libraries.mak

LOCAL_DEFINES = -DPEGASUS_INTERNALONLY

PROGRAM = TestAssoc
SOURCES = Assoc.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)
