ROOT = ../../../../..
DIR = Pegasus/Common/tests/AssocTest
include $(ROOT)/mak/config.mak
include ../libraries.mak

PROGRAM = AssocTest
SOURCES = AssocTest.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)
