ROOT = ../../../../..
DIR = Pegasus/ExportClient/tests/ExportServer
include $(ROOT)/mak/config.mak
include ../libraries.mak

PROGRAM = TestExportServer
SOURCES = ExportServer.cpp

include $(ROOT)/mak/program.mak

tests:

run:
	$(PROGRAM)
