ROOT = ../../../../..
DIR = Pegasus/ExportServer/tests/ExportServer
include $(ROOT)/mak/config.mak
include ../libraries.mak

LOCAL_DEFINES = -DPEGASUS_INTERNALONLY

PROGRAM = TestExportServer
SOURCES = ExportServer.cpp

include $(ROOT)/mak/program.mak

tests:

poststarttests:

run:
	$(PROGRAM)
