ROOT = ../../../../..
DIR = Pegasus/Common/tests/Stopwatch
include $(ROOT)/mak/config.mak
include ../libraries.mak

PROGRAM = Stopwatch
SOURCES = Stopwatch.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)
