ROOT = ../../../../..
DIR = Pegasus/Common/tests/Stopwatch
include $(ROOT)/mak/config.mak
include ../libraries.mak

LOCAL_DEFINES = -DPEGASUS_INTERNALONLY

PROGRAM = TestStopwatch
SOURCES = Stopwatch.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)

poststarttests:

