ROOT = ../../../../..
DIR = Pegasus/Common/tests/ToMof
include $(ROOT)/mak/config.mak
include ../libraries.mak

PROGRAM = TestToMof

SOURCES = tomof.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)

poststarttests:

