ROOT = ../../../../..
DIR = Pegasus/Common/tests/StatisticalData
include $(ROOT)/mak/config.mak
include ../libraries.mak

LOCAL_DEFINES = -DPEGASUS_INTERNALONLY

PROGRAM = StatisticalData

SOURCES = StatisticalData.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)

poststarttests:
install:

