# Wbemexec test associated w/GetClass
#

ROOT = ../../../..
include $(ROOT)/mak/config.mak
include $(ROOT)/test/config.mak

XMLSCRIPTS = \
	   GetClass00001 \
	   GetClass00010 \
	   GetClass00011 \
	   GetClass00012 \
	   GetClass00013 \
	   GetClass00014 \
	   GetClass00015 \
	   GetClass00017 \
	   GetClass00018

ifndef SECURITY_ENABLED
XMLSCRIPTS += \
           GetClass00016 
endif

include $(ROOT)/test/configend.mak
