# Wbemexec test associated w/GetClass
#

ROOT = ../../../..
include $(ROOT)/mak/config.mak
include $(ROOT)/test/config.mak

XMLSCRIPTS = \
	   GetClass00001 \
	   GetClass00010 \
	   GetClass00011 \
	   GetClass00012 \
	   GetClass00013 \
	   GetClass00014 \
	   GetClass00015 \
	   GetClass00016 \
	   GetClass00017


clean:
	$(RM) $(XMLRESPONSES)
	

tests: $(XMLRESPONSES)

