ROOT = ../../../../../..
DIR = Pegasus/Common/tests/Service/RemoveService
include $(ROOT)/mak/config.mak

EXTRA_INCLUDES = $(SYS_INCLUDES)

PROGRAM = RemoveService

SOURCES = RemoveService.cpp

include $(ROOT)/mak/program.mak

tests:
