ROOT = ../../../../../..
DIR = Pegasus/Common/tests/Service/RemoveService
include $(ROOT)/mak/config.mak

EXTRA_INCLUDES = $(SYS_INCLUDES)

LOCAL_DEFINES = -DPEGASUS_INTERNALONLY

PROGRAM = TestRemoveService

SOURCES = RemoveService.cpp

include $(ROOT)/mak/program.mak

tests:
