ROOT = ../../../../..
DIR = Pegasus/Common/tests/Flavor
include $(ROOT)/mak/config.mak
include ../libraries.mak

LOCAL_DEFINES = -DPEGASUS_INTERNALONLY

PROGRAM = TestFlavor

SOURCES = Flavor.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)

poststarttests:

