ROOT = ../../../../..
DIR = Pegasus/Client/tests/InvokeMethod
include $(ROOT)/mak/config.mak
include ../libraries.mak

EXTRA_INCLUDES = $(SYS_INCLUDES)

PROGRAM = InvokeMethod

SOURCES = InvokeMethod.cpp

include $(ROOT)/mak/program.mak

tests:

poststarttests:
