
ROOT = ../../../..
include $(ROOT)/mak/config.mak
include $(ROOT)/test/config.mak

XMLSCRIPTS = ModifyClass43000 ModifyClass43001 ModifyClass43002 ModifyClass43003 ModifyClass43004 ModifyClass43005

clean:
	$(RM) $(XMLRESPONSES)


tests: $(XMLRESPONSES)