#define yy_create_buffer cimmof__create_buffer
#define yy_delete_buffer cimmof__delete_buffer
#define yy_scan_buffer cimmof__scan_buffer
#define yy_scan_string cimmof__scan_string
#define yy_scan_bytes cimmof__scan_bytes
#define yy_flex_debug cimmof__flex_debug
#define yy_init_buffer cimmof__init_buffer
#define yy_flush_buffer cimmof__flush_buffer
#define yy_load_buffer_state cimmof__load_buffer_state
#define yy_switch_to_buffer cimmof__switch_to_buffer
#define yyin cimmof_in
#define yyleng cimmof_leng
#define yylex cimmof_lex
#define yyout cimmof_out
#define yyrestart cimmof_restart
#define yytext cimmof_text
#define yywrap cimmof_wrap

#line 20 "cimmof_lex.cpp"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /cvs/MSB/pegasus/src/Pegasus/Compiler/cimmof_lex.cpp,v 1.20 2004/07/29 18:35:42 dj.gorey Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 67
#define YY_END_OF_BUFFER 68
static yyconst short int yy_accept[273] =
    {   0,
        0,    0,   68,   66,    3,    1,   27,   66,   66,    9,
       10,   66,   20,   28,   66,   17,   17,   11,   12,   19,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,    7,    8,   65,
        5,    6,    0,   22,    0,    0,    0,   18,   18,   18,
       13,   23,    2,   17,    0,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   31,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
        0,   21,   14,   14,   16,   13,    2,    2,   15,   41,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,

       65,   65,   65,   65,   65,   65,   65,   42,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,    0,   13,
       13,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   24,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   25,   65,   65,    0,
       65,   65,   65,   63,   65,   65,   65,   26,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   33,   65,   65,   65,   57,   65,   65,   65,   65,
       65,   65,   53,    4,    0,   65,   65,   64,   65,   65,
       65,   43,   65,   65,   65,   39,   65,   65,   65,   61,

       62,   65,   65,   34,   58,   59,   60,   50,   65,   65,
       54,   55,   56,   29,   65,   51,   65,   65,   65,   49,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       52,   65,   65,   65,   30,   65,   37,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   40,   32,   38,   65,
       65,   65,   65,   65,   65,   36,   46,   47,   65,   35,
       65,   65,   65,   65,   65,   48,   65,   65,   65,   44,
       45,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    6,    7,    1,    1,    8,    9,
       10,   11,   12,   13,   12,   14,   15,   16,   17,   18,
       19,   20,   21,   22,   21,   23,   24,   25,   26,    1,
       27,    1,    1,    1,   28,   29,   30,   31,   32,   33,
       34,   35,   36,   37,   37,   38,   39,   40,   41,   42,
       43,   44,   45,   46,   47,   48,   37,   37,   49,   37,
       50,    1,   51,    1,   37,    1,   52,   29,   53,   31,

       32,   33,   34,   35,   36,   37,   37,   54,   39,   40,
       41,   42,   43,   44,   55,   46,   47,   48,   37,   56,
       49,   37,   57,    1,   58,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[59] =
    {   0,
        1,    1,    2,    1,    1,    1,    3,    1,    1,    1,
        1,    4,    1,    5,    1,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    1,    1,    1,    7,    7,    7,
        7,    7,    7,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    1,
        1,    7,    7,    3,    3,    8,    1,    1
    } ;

static yyconst short int yy_base[282] =
    {   0,
        0,    0,  395,  396,  396,  396,   56,  352,    0,  396,
      396,   46,  396,    0,   53,   51,   52,  396,  396,  396,
       27,  352,  357,   41,  351,   42,    0,  350,  357,  341,
      354,   43,  339,  353,   45,   32,  348,  396,  396,   43,
      396,  396,   80,  396,  339,  374,    0,   95,   72,  367,
      348,  396,  376,    0,    0,    0,  329,   29,  336,   51,
      330,   45,   71,   66,   74,   91,  329,   87,    0,  330,
      332,   77,  100,   96,  332,  327,   85,  104,  330,  317,
       82,  360,    0,  131,  396,  355,  363,  396,    0,    0,
      324,   89,  320,  331,  107,  333,   94,  313,  100,  324,

      313,  323,  104,  122,  315,  115,  119,  324,  309,  322,
      311,  306,  315,  303,  309,  316,  301,  291,  311,  332,
      331,  131,  310,  145,  295,  311,  125,  307,  297,  290,
      134,  137,  295,    0,  296,  302,  297,  148,  288,  287,
      291,  297,  158,  288,  298,  121,    0,  169,  271,  286,
      288,  143,  301,    0,  286,  140,  289,    0,  276,  288,
      144,  278,  286,  284,  271,  281,  295,  292,  279,  274,
      154,    0,  287,  290,  287,    0,  272,  155,  145,  283,
      286,  283,    0,    0,  162,  165,  262,    0,  262,  268,
      258,    0,  266,  251,  167,    0,  250,  249,  258,    0,

        0,  253,  168,    0,    0,    0,    0,    0,  162,  173,
        0,    0,    0,  396,  246,    0,  259,  249,  241,    0,
      252,  255,  254,  236,  252,  173,  237,  176,  236,  245,
        0,  232,  247,  237,    0,  233,    0,  232,  243,  242,
      157,  177,  232,  240,  227,  229,    0,    0,    0,  223,
      164,  224,  210,  195,  183,    0,    0,    0,  169,    0,
      180,  186,  186,  179,  182,    0,  180,  178,   74,    0,
        0,  396,  229,  237,  241,   86,  243,  249,  257,  260,
      264
    } ;

static yyconst short int yy_def[282] =
    {   0,
      272,    1,  272,  272,  272,  272,  273,  272,  274,  272,
      272,  275,  272,  276,  272,  277,  277,  272,  272,  272,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  272,  272,  278,
      272,  272,  273,  272,  272,  274,  276,  272,  275,  275,
      276,  272,  279,   17,  280,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      272,  274,   48,   48,  272,  281,  279,  272,  280,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,

      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  272,  281,
      281,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  272,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  272,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,

      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  272,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,    0,  272,  272,  272,  272,  272,  272,  272,  272,
      272
    } ;

static yyconst short int yy_nxt[455] =
    {   0,
        4,    5,    6,    5,    7,    8,    4,    9,   10,   11,
        4,   12,   13,   14,   15,   16,   17,   17,   17,   17,
       17,   17,   17,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   27,   28,   27,   27,   29,   30,
       31,   32,   33,   34,   35,   36,   37,   27,   27,   38,
       39,   21,   40,   27,   35,   27,   41,   42,   44,   47,
       44,   48,   49,   52,   47,   47,   57,   53,   61,   64,
       70,   58,   77,   91,   74,   78,   62,   60,   93,   65,
       75,   58,   44,   91,   44,   47,   71,   49,   49,   95,
       76,   51,   61,   64,   70,   65,   80,   74,   96,   95,

       85,   98,   93,   97,  106,  271,   55,  272,   47,  119,
       83,   83,   84,   84,   84,   84,   84,   50,   50,   97,
       99,  100,   96,   85,  103,   98,  123,  107,  106,  114,
      110,  115,  108,  119,  126,  101,  111,  130,  128,  114,
      103,  134,  123,   99,  109,  101,   84,   84,  128,  135,
      116,  107,  137,  130,  109,  115,  138,  134,  126,  272,
      151,  153,  157,  161,  162,  179,  167,  154,  137,  168,
      187,  194,  138,  135,  173,  179,  174,  190,  157,  175,
      176,  204,  210,  151,  209,  180,  161,  181,  162,  214,
      182,  183,  215,  190,  187,  194,  222,  227,  210,  228,

      229,  251,  239,  241,  252,  204,  263,  209,  258,  270,
      269,  251,  268,  214,  267,  228,  215,  266,  258,  222,
      227,  265,  263,  264,  229,  239,  262,  241,  252,   43,
       43,   43,   43,   43,   43,   43,   43,   46,  261,   46,
       46,   46,   46,   46,   46,   50,   50,   54,   54,  260,
       54,   56,  259,  257,   56,   56,   56,   87,   87,   87,
       87,   87,   87,   87,   87,   89,   89,  121,  256,  121,
      255,  254,  253,  250,  249,  248,  247,  246,  245,  244,
      243,  242,  240,  238,  237,  236,  235,  234,  233,  232,
      231,  230,  226,  225,  224,  223,  221,  220,  219,  218,

      217,  216,  213,  212,  211,  208,  207,  206,  205,  203,
      202,  201,  200,  199,  198,  197,  196,  195,  193,  192,
      191,  189,  188,  186,  185,  184,  178,  177,  172,  171,
      170,  169,  166,  165,  164,  163,  160,  159,  158,  156,
      155,  152,  272,  272,  150,  149,  148,  147,  146,  145,
      144,  143,  142,  141,  140,  139,  136,  133,  132,  131,
      129,  127,  125,  124,  122,   88,  120,   82,  118,  117,
      113,  112,  105,  104,  102,   94,   92,   90,   88,   86,
       47,   82,   81,   79,   73,   72,   69,   68,   67,   66,
       63,   60,   59,   45,  272,    3,  272,  272,  272,  272,

      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272
    } ;

static yyconst short int yy_chk[455] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    7,   12,
        7,   12,   12,   15,   16,   17,   21,   15,   24,   26,
       32,   21,   36,   58,   35,   36,   24,   40,   60,   26,
       35,   21,   43,   58,   43,   49,   32,   49,   49,   62,
       35,  276,   24,   26,   32,   26,   40,   35,   63,   62,

       49,   65,   60,   64,   72,  269,   16,   17,   48,   81,
       48,   48,   48,   48,   48,   48,   48,   48,   48,   64,
       66,   66,   63,   48,   68,   65,   92,   73,   72,   77,
       74,   78,   73,   81,   95,   66,   74,   99,   97,   77,
       68,  103,   92,   66,   73,   66,   84,   84,   97,  104,
       78,   73,  106,   99,   73,   78,  107,  103,   95,   84,
      122,  124,  127,  131,  132,  146,  138,  124,  106,  138,
      152,  161,  107,  104,  143,  146,  143,  156,  127,  143,
      143,  171,  179,  122,  178,  148,  131,  148,  132,  185,
      148,  148,  186,  156,  152,  161,  195,  203,  179,  209,

      210,  241,  226,  228,  242,  171,  259,  178,  251,  268,
      267,  241,  265,  185,  264,  209,  186,  263,  251,  195,
      203,  262,  259,  261,  210,  226,  255,  228,  242,  273,
      273,  273,  273,  273,  273,  273,  273,  274,  254,  274,
      274,  274,  274,  274,  274,  275,  275,  277,  277,  253,
      277,  278,  252,  250,  278,  278,  278,  279,  279,  279,
      279,  279,  279,  279,  279,  280,  280,  281,  246,  281,
      245,  244,  243,  240,  239,  238,  236,  234,  233,  232,
      230,  229,  227,  225,  224,  223,  222,  221,  219,  218,
      217,  215,  202,  199,  198,  197,  194,  193,  191,  190,

      189,  187,  182,  181,  180,  177,  175,  174,  173,  170,
      169,  168,  167,  166,  165,  164,  163,  162,  160,  159,
      157,  155,  153,  151,  150,  149,  145,  144,  142,  141,
      140,  139,  137,  136,  135,  133,  130,  129,  128,  126,
      125,  123,  121,  120,  119,  118,  117,  116,  115,  114,
      113,  112,  111,  110,  109,  108,  105,  102,  101,  100,
       98,   96,   94,   93,   91,   87,   86,   82,   80,   79,
       76,   75,   71,   70,   67,   61,   59,   57,   53,   51,
       50,   46,   45,   37,   34,   33,   31,   30,   29,   28,
       25,   23,   22,    8,    3,  272,  272,  272,  272,  272,

      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "cimmof.l"
#define INITIAL 0
#define YY_NEVER_INTERACTIVE 1
#line 3 "cimmof.l"

#include "cimmofParser.h"
#include "memobjs.h"
#include "cimmof_tab.h"

/*--- change history (recent) ---------------------------------------------

      7/29/2004, Ed Boden, bug 1330; support for slash-asterick comments.

-------------------------------------------------------------------------*/


/* ATTN-DME-DEFERRED-20020516 - MOF COMPILER ALIASING DISABLED           */
/* To enable aliasing add the following two lines                        */
/* $[_$0-9a-zA-Z]+                     { return(TOK_ALIAS_IDENTIFIER); } */
/* [Aa][Ss]                            { return(TOK_AS); }               */

/*---------------------------------------------------------------*/
/* These routines wrap certain flex functions, keeping down the  */
/* number of external dependencies                               */
/*---------------------------------------------------------------*/
int get_yy_buf_size_wrapper() { return YY_BUF_SIZE; }

void * get_cimmof__current_buffer_wrapper() { 
  return (void *)YY_CURRENT_BUFFER; 
}

void * create_cimmof_buffer_wrapper(const FILE *f, int size) {
  return (void *)yy_create_buffer((FILE *)f, size);
}

int switch_to_buffer_wrapper(void *buffstate, Boolean closeCurrent) {
  if (closeCurrent)
  {
     if (yyin != NULL)
     {
        fflush(yyin);
        fclose(yyin);
        yyin = NULL;
     }
     yy_delete_buffer(YY_CURRENT_BUFFER);
  }
  yy_switch_to_buffer((YY_BUFFER_STATE)buffstate);
  return 0;
}



#line 624 "cimmof_lex.cpp"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 54 "cimmof.l"



#line 779 "cimmof_lex.cpp"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 273 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 396 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 57 "cimmof.l"
{ 
                                cimmofParser::Instance()->increment_lineno(); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 59 "cimmof.l"
{
                                cimmofParser::Instance()->increment_lineno(); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 61 "cimmof.l"
{ /* skip white space */ }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 62 "cimmof.l"
{ return(TOK_CLASS); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 63 "cimmof.l"
{ return(TOK_LEFTCURLYBRACE); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 64 "cimmof.l"
{ return(TOK_RIGHTCURLYBRACE); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 65 "cimmof.l"
{ return(TOK_LEFTSQUAREBRACKET); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 66 "cimmof.l"
{ return(TOK_RIGHTSQUAREBRACKET); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 67 "cimmof.l"
{ return(TOK_LEFTPAREN); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 68 "cimmof.l"
{ return(TOK_RIGHTPAREN); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 69 "cimmof.l"
{ return(TOK_COLON); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 70 "cimmof.l"
{ return(TOK_SEMICOLON); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 71 "cimmof.l"
{ 
                                      cimmof_lval.strval = new String(yytext);
                                      return(TOK_REAL_VALUE); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 74 "cimmof.l"
{ cimmof_lval.strval = new String(yytext);
                                     return(TOK_OCTAL_VALUE); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 76 "cimmof.l"
{ cimmof_lval.strval = new String(yytext);
                                     return(TOK_HEX_VALUE); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 78 "cimmof.l"
{ cimmof_lval.strval = new String(yytext);
                                     return(TOK_BINARY_VALUE); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 80 "cimmof.l"
{ cimmof_lval.strval = new String(yytext);
                                     return(TOK_POSITIVE_DECIMAL_VALUE); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 82 "cimmof.l"
{ cimmof_lval.strval = new String(yytext);
                                     return(TOK_SIGNED_DECIMAL_VALUE); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 84 "cimmof.l"
{ return(TOK_EQUAL); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 85 "cimmof.l"
{ return(TOK_COMMA); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 86 "cimmof.l"
{ cimmof_lval.strval = new String(yytext);
                                      return(TOK_CHAR_VALUE); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 88 "cimmof.l"
{ cimmof_lval.strval = new String(yytext);
                                      return(TOK_STRING_VALUE); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 90 "cimmof.l"
{ /* rational for this over approaches that use
                                         reg exp's to go through the comment is that
                                         this approach will not overflow flex's buffer, 
                                         even for very long comments.
                                      */
                                      int c1=0, c2=yyinput();
                                      for (;;) {
                                          if (c2==EOF) break;
                                          if (c1=='*' && c2=='/') break;
                                          c1=c2;
                                          c2=yyinput();
                                          }                               
                                      }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 103 "cimmof.l"
{ return(TOK_NULL_VALUE); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 104 "cimmof.l"
{ return(TOK_TRUE); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 105 "cimmof.l"
{ return(TOK_FALSE); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 106 "cimmof.l"
{ return(TOK_DQUOTE); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 107 "cimmof.l"
{ return(TOK_PERIOD); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 108 "cimmof.l"
{ return(TOK_PRAGMA); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 109 "cimmof.l"
{
                                      return(TOK_INSTANCE); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 111 "cimmof.l"
{
                                      return(TOK_OF); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 113 "cimmof.l"
{return(TOK_QUALIFIER); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 114 "cimmof.l"
{ return(TOK_SCOPE); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 115 "cimmof.l"
{ return(TOK_SCHEMA); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 116 "cimmof.l"
{
                                      return(TOK_ASSOCIATION); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 118 "cimmof.l"
{
                                      return(TOK_INDICATION); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 120 "cimmof.l"
{ return(TOK_PROPERTY); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 121 "cimmof.l"
{ return(TOK_REFERENCE); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 122 "cimmof.l"
{ return(TOK_METHOD); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 123 "cimmof.l"
{return(TOK_PARAMETER); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 124 "cimmof.l"
{ return(TOK_ANY); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 125 "cimmof.l"
{ return(TOK_REF); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 126 "cimmof.l"
{ return(TOK_FLAVOR); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 127 "cimmof.l"
{
                                      return(TOK_ENABLEOVERRIDE); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 129 "cimmof.l"
{
                                      return(TOK_DISABLEOVERRIDE); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 131 "cimmof.l"
{
                                      return(TOK_RESTRICTED); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 133 "cimmof.l"
{return(TOK_TOSUBCLASS); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 134 "cimmof.l"
{
                                      return(TOK_TRANSLATABLE); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 136 "cimmof.l"
{ return(TOK_INCLUDE); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 137 "cimmof.l"
{ return(TOK_DT_STR); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 138 "cimmof.l"
{ return(TOK_DT_BOOL); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 139 "cimmof.l"
{ return(TOK_DT_DATETIME); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 140 "cimmof.l"
{ return(TOK_DT_UINT8); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 141 "cimmof.l"
{ return(TOK_DT_UINT16); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 142 "cimmof.l"
{ return(TOK_DT_UINT32); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 143 "cimmof.l"
{ return(TOK_DT_UINT64); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 144 "cimmof.l"
{ return(TOK_DT_SINT8); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 145 "cimmof.l"
{ return(TOK_DT_SINT16); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 146 "cimmof.l"
{ return(TOK_DT_SINT32); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 147 "cimmof.l"
{ return(TOK_DT_SINT64); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 148 "cimmof.l"
{ return(TOK_DT_REAL32); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 149 "cimmof.l"
{ return(TOK_DT_REAL64); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 150 "cimmof.l"
{ return(TOK_DT_CHAR8); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 151 "cimmof.l"
{ return(TOK_DT_CHAR16); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 152 "cimmof.l"
{ cimmof_lval.strval = new String(yytext);
                                      return(TOK_SIMPLE_IDENTIFIER); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 154 "cimmof.l"
{ cimmof_lval.strval = new String(yytext);
                                      return(TOK_UNEXPECTED_CHAR); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 157 "cimmof.l"
ECHO;
	YY_BREAK
#line 1230 "cimmof_lex.cpp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 273 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 273 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 272);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}
#endif /* YY_NO_INPUT */

#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 157 "cimmof.l"


void cimmof_yy_less(int n) {
  yyless(n);
}
