#define yy_create_buffer cimmof__create_buffer
#define yy_delete_buffer cimmof__delete_buffer
#define yy_scan_buffer cimmof__scan_buffer
#define yy_scan_string cimmof__scan_string
#define yy_scan_bytes cimmof__scan_bytes
#define yy_flex_debug cimmof__flex_debug
#define yy_init_buffer cimmof__init_buffer
#define yy_flush_buffer cimmof__flush_buffer
#define yy_load_buffer_state cimmof__load_buffer_state
#define yy_switch_to_buffer cimmof__switch_to_buffer
#define yyin cimmof_in
#define yyleng cimmof_leng
#define yylex cimmof_lex
#define yyout cimmof_out
#define yyrestart cimmof_restart
#define yytext cimmof_text
#define yylineno cimmof_lineno
#define yywrap cimmof_wrap

#line 21 "cimmof_lex.cpp"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /cvs/MSB/pegasus/src/Pegasus/Compiler/cimmof_lex.cpp,v 1.25 2005/06/24 20:11:05 kumpf Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 83
#define YY_END_OF_BUFFER 84
static yyconst short int yy_acclist[413] =
    {   0,
       84,   82,   83,    3,   82,   83,    1,   83,   22,   82,
       83,   82,   83,   82,   83,   82,   83,    9,   82,   83,
       10,   82,   83,   82,   83,   20,   82,   83,   42,   82,
       83,   82,   83,   17,   82,   83,   17,   82,   83,   11,
       82,   83,   12,   82,   83,   19,   82,   83,   81,   82,
       83,   81,   82,   83,   81,   82,   83,   81,   82,   83,
       81,   82,   83,   81,   82,   83,   81,   82,   83,   81,
       82,   83,   81,   82,   83,   81,   82,   83,   81,   82,
       83,   81,   82,   83,   81,   82,   83,   81,   82,   83,
       81,   82,   83,   81,   82,   83,   81,   82,   83,    7,

       82,   83,    8,   82,   83,   81,   82,   83,    5,   82,
       83,    6,   82,   83,   35,   83,   24,   83,   23,   83,
       83,   37,   83,   83,   36,   37,   83,   64,   18,   18,
       18,   13,   38,    2,   17,   81,   81,   65,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   81,   45,
       81,   81,   81,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   35,   34,   31,   34,   30,   34,   33,   34,
       32,   34,   25,   34,   26,   34,   27,   34,   28,   34,
       29,   34,   36,   21,   14,   18,   14,   18,   16,   13,
        2,    2,   15,   55,   81,   81,   81,   81,   81,   81,

       81,   81,   81,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   56,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   81,   36,   13,   13,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   81,   39,
       81,   81,   81,   81,   81,   81,   81,   81,   81,   81,
       81,   81,   81,   40,   81,   81,   81,   36,   81,   81,
       81,   79,   81,   81,   81,   81,   41,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   81,   81,
       81,   47,   81,   81,   81,   81,   73,   81,   81,   81,
       81,   81,   81,   81,   69,   81,    4,   81,   81,   81,

       80,   81,   81,   81,   81,   57,   81,   81,   81,   81,
       53,   81,   81,   81,   81,   77,   81,   78,   81,   81,
       81,   48,   81,   74,   81,   75,   81,   76,   81,   66,
       81,   81,   81,   70,   81,   71,   81,   72,   81,   43,
       81,   67,   81,   81,   81,   81,   63,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   81,   68,   81,
       81,   81,   81,   44,   81,   81,   51,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   54,   81,   46,
       81,   52,   81,   81,   81,   81,   81,   81,   81,   50,
       81,   60,   81,   61,   81,   81,   49,   81,   81,   81,

       81,   81,   81,   62,   81,   81,   81,   81,   58,   81,
       59,   81
    } ;

static yyconst short int yy_accept[299] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    4,    7,
        9,   12,   14,   16,   18,   21,   24,   26,   29,   32,
       34,   37,   40,   43,   46,   49,   52,   55,   58,   61,
       64,   67,   70,   73,   76,   79,   82,   85,   88,   91,
       94,   97,  100,  103,  106,  109,  112,  115,  117,  119,
      121,  122,  124,  125,  128,  128,  129,  129,  129,  130,
      131,  132,  133,  134,  135,  136,  136,  137,  138,  140,
      141,  142,  143,  144,  145,  146,  147,  148,  149,  150,
      152,  153,  154,  155,  156,  157,  158,  159,  160,  161,
      162,  163,  164,  165,  167,  169,  171,  173,  175,  177,

      179,  181,  183,  184,  184,  185,  187,  189,  190,  191,
      192,  193,  194,  196,  197,  198,  199,  200,  201,  202,
      203,  204,  205,  206,  207,  208,  209,  210,  211,  212,
      213,  215,  216,  217,  218,  219,  220,  221,  222,  223,
      224,  225,  226,  226,  227,  228,  229,  230,  231,  232,
      233,  234,  235,  236,  237,  238,  239,  240,  242,  243,
      244,  245,  246,  247,  248,  249,  250,  251,  252,  253,
      254,  256,  257,  258,  259,  259,  260,  261,  262,  264,
      265,  266,  267,  269,  270,  271,  272,  273,  274,  275,
      276,  277,  278,  279,  280,  281,  282,  284,  285,  286,

      287,  289,  290,  291,  292,  293,  294,  295,  297,  299,
      299,  300,  301,  303,  304,  305,  306,  308,  309,  310,
      311,  313,  314,  315,  316,  318,  320,  321,  322,  324,
      326,  328,  330,  332,  333,  334,  336,  338,  340,  341,
      342,  344,  345,  346,  347,  349,  350,  351,  352,  353,
      354,  355,  356,  357,  358,  359,  361,  362,  363,  364,
      366,  367,  369,  370,  371,  372,  373,  374,  375,  376,
      377,  378,  380,  382,  384,  385,  386,  387,  388,  389,
      390,  392,  394,  396,  397,  399,  400,  401,  402,  403,
      404,  406,  407,  408,  409,  411,  413,  413

    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    6,    7,    1,    1,    8,    9,
       10,   11,   12,   13,   12,   14,   15,   16,   17,   18,
       19,   20,   21,   22,   21,   23,   24,   25,   26,    1,
       27,    1,    1,    1,   28,   29,   30,   31,   32,   33,
       34,   35,   36,   37,   37,   38,   39,   40,   41,   42,
       43,   44,   45,   46,   47,   48,   37,   49,   50,   37,
       51,   52,   53,    1,   37,    1,   54,   55,   56,   31,

       32,   57,   34,   35,   36,   37,   37,   58,   39,   59,
       41,   42,   43,   60,   61,   62,   47,   48,   37,   63,
       50,   37,   64,    1,   65,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[66] =
    {   0,
        1,    1,    2,    1,    3,    1,    4,    1,    1,    1,
        1,    5,    1,    6,    1,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    1,    1,    1,    8,    8,    8,
        8,    9,    8,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        1,    3,    1,    8,    8,    8,    8,    4,    4,    4,
        4,    4,   10,    1,    1
    } ;

static yyconst short int yy_base[314] =
    {   0,
        0,    0,   63,   64,  114,  169,  591,  592,  592,  592,
      592,  548,    0,    0,  592,  592,   56,  592,   58,   72,
       57,   76,  592,  592,  592,   44,  548,  553,   57,   48,
       64,    0,   51,  555,  539,   62,   69,  538,  552,  118,
       65,  547,  592,  592,   63,  592,  592,    0,  592,  592,
      222,  592,  592,    0,   52,    0,  574,  139,  272,  165,
      567,  548,  592,  576,    0,    0,    0,  528,   63,  536,
       72,  103,  105,   73,   56,  113,  173,  149,  115,    0,
      152,  535,  123,  186,  143,  169,  161,  161,  185,  176,
      521,    0,  592,  592,  592,  592,  592,  592,  592,  592,

      592,  592,    0,  179,  566,    0,  220,  592,  561,  569,
      592,    0,    0,  530,  200,  197,  538,  214,  215,  200,
      521,  208,  532,  202,  532,  214,  222,  524,  215,  222,
      533,  205,  532,  521,  216,  526,  514,  243,  528,  241,
      498,    0,  524,  288,  297,  267,  525,  242,  276,  269,
      287,  524,  514,  507,  270,  300,  512,    0,  513,  519,
      514,  310,  286,  287,  510,  516,  317,  293,  306,  292,
        0,  340,  486,  592,  507,  509,  313,  522,    0,  507,
      306,  510,    0,  298,  510,  315,  309,  509,  507,  306,
       71,  520,  517,  504,  499,  320,    0,  508,  493,  469,

        0,  454,  321,  317,  460,  463,  458,    0,    0,  328,
      332,  325,    0,  438,  432,  417,    0,  425,  325,  340,
        0,  326,  327,  398,    0,    0,  336,  348,    0,    0,
        0,    0,    0,  341,  352,    0,    0,    0,  592,  335,
        0,  400,  390,  379,    0,  389,  392,  391,  370,  267,
      353,  339,  362,  345,  233,    0,  215,  224,  214,    0,
      348,    0,  350,  222,  185,  353,  365,  174,  178,  358,
      363,    0,    0,    0,  177,  360,  371,  371,  368,  369,
        0,    0,    0,  377,    0,  373,  147,  144,  139,  121,
        0,  109,   67,   54,    0,    0,  592,  435,  445,  452,

      462,  467,  469,  476,  486,  496,  500,  503,  512,  516,
      519,  524,  525
    } ;

static yyconst short int yy_def[314] =
    {   0,
      297,    1,  298,  298,  299,  299,  297,  297,  297,  297,
      297,  297,  300,  301,  297,  297,  302,  297,  297,  297,
      303,  303,  297,  297,  297,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  297,  297,  304,  297,  297,  305,  297,  297,
      306,  297,  297,  307,  297,  300,  301,  297,  297,  302,
      302,  308,  297,  309,   22,  310,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  305,  297,  297,  297,  297,  297,  297,  297,  297,

      297,  297,  311,  297,  301,   59,   59,  297,  312,  309,
      297,  310,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  313,  297,  297,  297,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  297,  297,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,

      304,  304,  304,  304,  304,  304,  304,  304,  304,  297,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  297,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  304,  304,    0,  297,  297,  297,

      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297
    } ;

static yyconst short int yy_nxt[658] =
    {   0,
        8,    9,   10,    9,   11,   12,   13,   14,   15,   16,
        8,   17,   18,   19,   20,   21,   22,   22,   22,   22,
       22,   22,   22,   22,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   32,   33,   32,   32,   34,   35,
       36,   37,   38,   39,   40,   41,   42,   32,   32,   32,
       43,    8,   44,   26,   27,   45,   31,   32,   35,   39,
       40,   41,   32,   46,   47,   49,   49,   50,   50,   58,
       58,   59,   60,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   63,   68,   72,  296,   64,   74,   69,   58,
       77,   75,   73,  120,   80,  104,   81,   71,  295,  116,

      119,   76,   68,  224,   69,   88,   74,  114,   89,   77,
       72,  104,   82,  120,   51,   51,   53,   75,   80,   66,
       91,   76,   81,  114,   89,  116,  119,  224,   82,   54,
       54,   54,   54,   54,   54,   54,   54,   54,  297,  294,
      121,   54,   54,   54,   54,   54,   54,   85,  117,  118,
      129,  293,  126,   86,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   87,  117,  118,  121,   54,   54,   54,
       54,   53,  126,   85,  292,  291,  129,  133,   58,   87,
       60,   60,  290,  134,   54,   54,   54,   54,   54,   54,
       54,   54,   54,  108,  125,  127,   54,   54,   54,   54,

       54,   54,  122,  123,  136,  137,  143,  282,  135,  279,
      125,  127,  138,  130,  278,  140,  275,  124,  131,  108,
      136,  137,   54,   54,   54,   54,   94,  135,  122,   95,
      132,  139,  143,  124,  140,  107,  107,  147,  138,  130,
      148,  150,  131,  151,  152,  154,  132,  156,  297,  159,
      164,  158,  161,  274,  271,  270,  148,  147,  178,  162,
      152,  167,  269,  156,  179,  154,  164,  150,  268,  151,
       96,  158,  161,   97,  297,  159,   98,  167,   99,  162,
      100,  101,  170,  102,   96,   58,  172,  106,  106,  107,
      107,  107,  107,  107,   61,   61,  176,  181,  263,  186,

      108,  170,  172,  145,  145,  145,  145,  145,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  180,  176,  181,  182,  186,  108,  187,  192,  194,
      195,  193,  202,  198,  203,  199,  204,  180,  200,  201,
      212,  217,  219,  215,  182,  194,  195,  229,  220,  223,
      234,  202,  204,  187,  235,  239,  205,  217,  206,  240,
      203,  207,  208,  215,  241,  223,  212,  220,  219,  247,
      246,  248,  249,  229,  235,  251,  234,  252,  253,  254,
      255,  239,  264,  241,  265,  240,  246,  248,  249,  266,
      267,  272,  277,  273,  251,  247,  255,  276,  253,  284,

      265,  280,  281,  252,  283,  254,  267,  272,  264,  273,
      285,  286,  287,  276,  288,  266,  289,  280,  277,  262,
      283,  281,  261,  260,  259,  284,  258,  286,  287,  285,
      257,  256,  289,  250,  288,   48,   48,   48,   48,   48,
       48,   48,   48,   48,   48,   52,   52,   52,   52,   52,
       52,   52,   52,   52,   52,   56,  245,  244,   56,   56,
       56,   56,   57,  243,   57,   57,   57,   57,   57,   57,
       57,   57,   61,   61,   65,   65,  242,  238,   65,   67,
      237,  236,   67,   67,   67,   67,   92,  233,  232,   92,
       92,   92,   92,   92,   92,   92,   93,   93,   93,   93,

       93,   93,   93,   93,   93,   93,  103,  103,  103,   62,
      231,   62,  110,  110,  110,  110,  110,  110,  110,  110,
      110,  110,  112,  112,  112,  142,  142,  142,  145,  230,
      145,  174,  174,  174,  228,  227,  226,  225,  222,  221,
      218,  216,  214,  213,  211,  210,  209,  197,  196,  191,
      190,  189,  188,  185,  184,  183,  177,  175,  173,  171,
      169,  168,  166,  165,  163,  160,  157,  155,  153,  149,
      146,  111,  144,  105,  141,  128,  115,  113,  111,  109,
       58,  105,   90,   84,   83,   79,   78,   71,   70,   55,
      297,    7,  297,  297,  297,  297,  297,  297,  297,  297,

      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297
    } ;

static yyconst short int yy_chk[658] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    4,    3,    4,   17,
       21,   17,   17,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   20,   26,   29,  294,   20,   30,   26,   22,
       33,   31,   29,   75,   36,   55,   37,   45,  293,   71,

       74,   31,   26,  191,   26,   41,   30,   69,   41,   33,
       29,   55,   37,   75,    3,    4,    5,   31,   36,   21,
       45,   31,   37,   69,   41,   71,   74,  191,   37,    5,
        5,    5,    5,    5,    5,    5,    5,    5,   22,  292,
       76,    5,    5,    5,    5,    5,    5,   40,   72,   73,
       83,  290,   79,   40,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   40,   72,   73,   76,    5,    5,    5,
        5,    6,   79,   40,  289,  288,   83,   85,   60,   40,
       60,   60,  287,   85,    6,    6,    6,    6,    6,    6,
        6,    6,    6,   60,   78,   81,    6,    6,    6,    6,

        6,    6,   77,   77,   87,   88,  104,  275,   86,  269,
       78,   81,   89,   84,  268,   90,  265,   77,   84,   60,
       87,   88,    6,    6,    6,    6,   51,   86,   77,   51,
       84,   89,  104,   77,   90,  107,  107,  115,   89,   84,
      116,  118,   84,  119,  120,  122,   84,  124,  107,  127,
      132,  126,  129,  264,  259,  258,  116,  115,  148,  130,
      120,  135,  257,  124,  148,  122,  132,  118,  255,  119,
       51,  126,  129,   51,  107,  127,   51,  135,   51,  130,
       51,   51,  138,   51,   51,   59,  140,   59,   59,   59,
       59,   59,   59,   59,   59,   59,  146,  150,  250,  155,

       59,  138,  140,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  145,  145,  145,  145,  145,  145,  145,  145,
      145,  149,  146,  150,  151,  155,   59,  156,  162,  163,
      164,  162,  168,  167,  169,  167,  170,  149,  167,  167,
      177,  184,  186,  181,  151,  163,  164,  196,  187,  190,
      203,  168,  170,  156,  204,  210,  172,  184,  172,  211,
      169,  172,  172,  181,  212,  190,  177,  187,  186,  220,
      219,  222,  223,  196,  204,  227,  203,  228,  234,  235,
      240,  210,  251,  212,  252,  211,  219,  222,  223,  253,
      254,  261,  267,  263,  227,  220,  240,  266,  234,  277,

      252,  270,  271,  228,  276,  235,  254,  261,  251,  263,
      278,  279,  280,  266,  284,  253,  286,  270,  267,  249,
      276,  271,  248,  247,  246,  277,  244,  279,  280,  278,
      243,  242,  286,  224,  284,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  299,  299,  299,  299,  299,
      299,  299,  299,  299,  299,  300,  218,  216,  300,  300,
      300,  300,  301,  215,  301,  301,  301,  301,  301,  301,
      301,  301,  302,  302,  303,  303,  214,  207,  303,  304,
      206,  205,  304,  304,  304,  304,  305,  202,  200,  305,
      305,  305,  305,  305,  305,  305,  306,  306,  306,  306,

      306,  306,  306,  306,  306,  306,  307,  307,  307,  308,
      199,  308,  309,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  310,  310,  310,  311,  311,  311,  312,  198,
      312,  313,  313,  313,  195,  194,  193,  192,  189,  188,
      185,  182,  180,  178,  176,  175,  173,  166,  165,  161,
      160,  159,  157,  154,  153,  152,  147,  143,  141,  139,
      137,  136,  134,  133,  131,  128,  125,  123,  121,  117,
      114,  110,  109,  105,   91,   82,   70,   68,   64,   62,
       61,   57,   42,   39,   38,   35,   34,   28,   27,   12,
        7,  297,  297,  297,  297,  297,  297,  297,  297,  297,

      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297,  297,  297,  297,
      297,  297,  297,  297,  297,  297,  297
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "cimmof.l"
#define INITIAL 0
/*
//%2005////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2000, 2001, 2002 BMC Software; Hewlett-Packard Development
// Company, L.P.; IBM Corp.; The Open Group; Tivoli Systems.
// Copyright (c) 2003 BMC Software; Hewlett-Packard Development Company, L.P.;
// IBM Corp.; EMC Corporation, The Open Group.
// Copyright (c) 2004 BMC Software; Hewlett-Packard Development Company, L.P.;
// IBM Corp.; EMC Corporation; VERITAS Software Corporation; The Open Group.
// Copyright (c) 2005 Hewlett-Packard Development Company, L.P.; IBM Corp.;
// EMC Corporation; VERITAS Software Corporation; The Open Group.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to
// deal in the Software without restriction, including without limitation the
// rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// THE ABOVE COPYRIGHT NOTICE AND THIS PERMISSION NOTICE SHALL BE INCLUDED IN
// ALL COPIES OR SUBSTANTIAL PORTIONS OF THE SOFTWARE. THE SOFTWARE IS PROVIDED
// "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
// LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
// PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
// HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
// ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
// WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//
//=============================================================================*/
#define YY_NEVER_INTERACTIVE 1
#define YY_STACK_USED 1
#line 35 "cimmof.l"

#include "cimmofParser.h"
#include "memobjs.h"
#include "cimmof_tab.h"

/*                                                                       */
/*  7/27/2004: bug 1330, support for slash* comments, E Boden, IBM       */
/*  8/14/2004: bug 544,  support for string escape characters, E Boden   */
/*                                                                       */
/*                                                                       */
/*                                                                       */


/*---------------------------------------------------------------*/
/* These routines wrap certain flex functions, keeping down the  */
/* number of external dependencies                               */
/*---------------------------------------------------------------*/
int get_yy_buf_size_wrapper() { return YY_BUF_SIZE; }

void * get_cimmof__current_buffer_wrapper() { 
  return (void *)YY_CURRENT_BUFFER; 
}

void * create_cimmof_buffer_wrapper(const FILE *f, int size) {
  return (void *)yy_create_buffer((FILE *)f, size);
}

int switch_to_buffer_wrapper(void *buffstate, Boolean closeCurrent) {
  if (closeCurrent)
  {
     if (yyin != NULL)
     {
        fflush(yyin);
        fclose(yyin);
        yyin = NULL;
     }
     yy_delete_buffer(YY_CURRENT_BUFFER);
  }
  yy_switch_to_buffer((YY_BUFFER_STATE)buffstate);
  return 0;
}

char  strbuf[1024], *strbuf_p, slashx[2];


#define myStr 1
#define myHex 2

#line 768 "cimmof_lex.cpp"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 84 "cimmof.l"



#line 923 "cimmof_lex.cpp"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 298 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 592 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 87 "cimmof.l"
{ 
                                      cimmofParser::Instance()->increment_lineno(); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 89 "cimmof.l"
{
                                      cimmofParser::Instance()->increment_lineno(); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 91 "cimmof.l"
{ /* skip white space */ }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 92 "cimmof.l"
{ return(TOK_CLASS); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 93 "cimmof.l"
{ return(TOK_LEFTCURLYBRACE); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 94 "cimmof.l"
{ return(TOK_RIGHTCURLYBRACE); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 95 "cimmof.l"
{ return(TOK_LEFTSQUAREBRACKET); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 96 "cimmof.l"
{ return(TOK_RIGHTSQUAREBRACKET); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 97 "cimmof.l"
{ return(TOK_LEFTPAREN); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 98 "cimmof.l"
{ return(TOK_RIGHTPAREN); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 99 "cimmof.l"
{ return(TOK_COLON); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 100 "cimmof.l"
{ return(TOK_SEMICOLON); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 101 "cimmof.l"
{ 
                                      cimmof_lval.strval = new String(yytext);
                                      return(TOK_REAL_VALUE); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 104 "cimmof.l"
{ cimmof_lval.strval = new String(yytext);
                                     return(TOK_OCTAL_VALUE); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 106 "cimmof.l"
{ cimmof_lval.strval = new String(yytext);
                                     return(TOK_HEX_VALUE); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 108 "cimmof.l"
{ cimmof_lval.strval = new String(yytext);
                                     return(TOK_BINARY_VALUE); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 110 "cimmof.l"
{ cimmof_lval.strval = new String(yytext);
                                     return(TOK_POSITIVE_DECIMAL_VALUE); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 112 "cimmof.l"
{ cimmof_lval.strval = new String(yytext);
                                     return(TOK_SIGNED_DECIMAL_VALUE); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 114 "cimmof.l"
{ return(TOK_EQUAL); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 115 "cimmof.l"
{ return(TOK_COMMA); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 116 "cimmof.l"
{ cimmof_lval.strval = new String(yytext);
                                      return(TOK_CHAR_VALUE); }
	YY_BREAK
/*--- bugzilla 544 fix; handle string escapes --- 
                                    
                                       an impl. decision: invalid escape sequences 
                                       are simply ignored, and left in the string.

                                       an impl. decision: yyleng is set to the len
                                       of resulting string, not the len of the matched
                                       token(s), since they are different, with escapes.
                                       (but note; cimmof.y does not use yyleng!)

                                       an impl. req't: strings are returned to parser
                                       with [no kidding!] enclosing "s.  
                                    */                                               
case 22:
YY_RULE_SETUP
#line 133 "cimmof.l"
{ BEGIN(myStr); strbuf_p = strbuf; 
                                      /**strbuf_p++ = '"';*/ }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 135 "cimmof.l"
{ BEGIN(INITIAL);  
                                      /**strbuf_p++ = '"';*/  *strbuf_p = '\0';
                                      cimmof_leng = strbuf_p - strbuf;
                                      cimmof_lval.strval = new String(strbuf);
                                      return TOK_STRING_VALUE; }
	YY_BREAK
case YY_STATE_EOF(myStr):
#line 140 "cimmof.l"
case 24:
YY_RULE_SETUP
#line 141 "cimmof.l"
{ BEGIN(INITIAL); 
                                      /**strbuf_p++ = '"';*/  *strbuf_p = '\0';
                                      cimmof_leng = strbuf_p - strbuf;
                                      cimmof_lval.strval = new String(strbuf);
                                      return TOK_UNEXPECTED_CHAR; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 146 "cimmof.l"
{ /* backspace */        *strbuf_p++ = '\b'; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 147 "cimmof.l"
{ /* form feed */        *strbuf_p++ = '\f'; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 148 "cimmof.l"
{ /* line feed */        *strbuf_p++ = '\n'; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 149 "cimmof.l"
{ /* carriage return */  *strbuf_p++ = '\r'; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 150 "cimmof.l"
{ /* horizontal tab */   *strbuf_p++ = '\t'; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 151 "cimmof.l"
{ /* single quote */     *strbuf_p++ = '\''; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 152 "cimmof.l"
{ /* double quote */     *strbuf_p++ = '"';  }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 153 "cimmof.l"
{ /* backslash */        *strbuf_p++ = '\\'; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 154 "cimmof.l"
{ yy_push_state(myHex);
                                      memcpy(slashx,yytext,2);
                                      }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 157 "cimmof.l"
{ *strbuf_p++ = '\\';
                                      *strbuf_p++ = yytext[1]; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 159 "cimmof.l"
{ char *t = yytext;
                                      while( *t ) *strbuf_p++ = *t++;
                                      *strbuf_p = '\0'; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 162 "cimmof.l"
{ /* get escaped hex digits */
                                      char  hexfmt[4];   unsigned int n;
                                      sprintf( hexfmt, "%%%dx", yyleng );
                                      sscanf(yytext, hexfmt, &n);
                                      if (n>255) {
                                          memcpy(strbuf_p,slashx,2);
                                          strbuf_p += 2;
                                          char *t = yytext;
                                          while( *t ) *strbuf_p++ = *t++;
                                          }
                                      else *strbuf_p++ = (char)n;
                                      yy_pop_state();     
                                      }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 175 "cimmof.l"
{ memcpy(strbuf_p,slashx,2);
                                      strbuf_p += 2;
                                      *strbuf_p++ = *yytext;
                                      yy_pop_state();
                                      }
	YY_BREAK
/* --- end of bugzilla 544 fix --- */
case 38:
YY_RULE_SETUP
#line 184 "cimmof.l"
{   int c1=0, c2=yyinput();
                                        for(;;) {
                                            if (c2==EOF) break;
                                            if (c1=='*' && c2=='/') break;
                                            c1=c2;
                                            c2=yyinput();
                                            }
                                        }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(myHex):
#line 192 "cimmof.l"
{ yyterminate(); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 193 "cimmof.l"
{ return(TOK_NULL_VALUE); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 194 "cimmof.l"
{ return(TOK_TRUE); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 195 "cimmof.l"
{ return(TOK_FALSE); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 196 "cimmof.l"
{ return(TOK_PERIOD); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 197 "cimmof.l"
{ return(TOK_PRAGMA); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 198 "cimmof.l"
{
                                      return(TOK_INSTANCE); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 200 "cimmof.l"
{
                                      return(TOK_OF); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 202 "cimmof.l"
{return(TOK_QUALIFIER); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 203 "cimmof.l"
{ return(TOK_SCOPE); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 204 "cimmof.l"
{ return(TOK_SCHEMA); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 205 "cimmof.l"
{
                                      return(TOK_ASSOCIATION); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 207 "cimmof.l"
{
                                      return(TOK_INDICATION); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 209 "cimmof.l"
{ return(TOK_PROPERTY); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 210 "cimmof.l"
{ return(TOK_REFERENCE); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 211 "cimmof.l"
{ return(TOK_METHOD); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 212 "cimmof.l"
{return(TOK_PARAMETER); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 213 "cimmof.l"
{ return(TOK_ANY); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 214 "cimmof.l"
{ return(TOK_REF); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 215 "cimmof.l"
{ return(TOK_FLAVOR); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 216 "cimmof.l"
{
                                      return(TOK_ENABLEOVERRIDE); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 218 "cimmof.l"
{
                                      return(TOK_DISABLEOVERRIDE); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 220 "cimmof.l"
{
                                      return(TOK_RESTRICTED); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 222 "cimmof.l"
{return(TOK_TOSUBCLASS); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 223 "cimmof.l"
{
                                      return(TOK_TRANSLATABLE); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 225 "cimmof.l"
{ return(TOK_INCLUDE); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 226 "cimmof.l"
{ cimmof_lval.strval = new String(yytext);
                                      return TOK_ALIAS_IDENTIFIER; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 228 "cimmof.l"
{ return TOK_AS; }              
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 229 "cimmof.l"
{ return(TOK_DT_STR); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 230 "cimmof.l"
{ return(TOK_DT_BOOL); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 231 "cimmof.l"
{ return(TOK_DT_DATETIME); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 232 "cimmof.l"
{ return(TOK_DT_UINT8); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 233 "cimmof.l"
{ return(TOK_DT_UINT16); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 234 "cimmof.l"
{ return(TOK_DT_UINT32); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 235 "cimmof.l"
{ return(TOK_DT_UINT64); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 236 "cimmof.l"
{ return(TOK_DT_SINT8); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 237 "cimmof.l"
{ return(TOK_DT_SINT16); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 238 "cimmof.l"
{ return(TOK_DT_SINT32); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 239 "cimmof.l"
{ return(TOK_DT_SINT64); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 240 "cimmof.l"
{ return(TOK_DT_REAL32); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 241 "cimmof.l"
{ return(TOK_DT_REAL64); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 242 "cimmof.l"
{ return(TOK_DT_CHAR8); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 243 "cimmof.l"
{ return(TOK_DT_CHAR16); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 244 "cimmof.l"
{ cimmof_lval.strval = new String(yytext);
                                      return(TOK_SIMPLE_IDENTIFIER); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 246 "cimmof.l"
{ cimmof_lval.strval = new String(yytext);
                                      return(TOK_UNEXPECTED_CHAR); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 249 "cimmof.l"
ECHO;
	YY_BREAK
#line 1508 "cimmof_lex.cpp"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 298 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 298 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 297);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}
#endif /* YY_NO_INPUT */

#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 249 "cimmof.l"


void cimmof_yy_less(int n) { yyless(n); }
