ROOT = ../../../../..
include ../libraries.mak

DIR = Pegasus/Server/tests/MyProvider

include $(ROOT)/mak/config.mak

LOCAL_DEFINES = -DPEGASUS_INTERNALONLY

SOURCES = MyProvider.cpp

LIBRARY = MyProvider
 
include $(ROOT)/mak/library.mak

tests:
