ROOT = ../../../../..
include ../libraries.mak

DIR = Pegasus/Provider/tests/MyProvider

include $(ROOT)/mak/config.mak

SOURCES = MyProvider.cpp

LIBRARY = MyProvider

include $(ROOT)/mak/library.mak

tests:
