ROOT = ../../../..

DIR = Clients/benchmarkTest/benchmarkProvider

include $(ROOT)/mak/config.mak

LIBRARY = benchmarkProviderModule

LIBRARIES = \
	pegcommon \
	pegprovider \
        benchmarkDefinition	

SOURCES = \
   benchmarkProvider.cpp \
   benchmarkProviderMain.cpp 

include $(ROOT)/mak/library.mak

