ROOT = ../../../../..
DIR = Pegasus/Common/tests/ConnectorAcceptor
include $(ROOT)/mak/config.mak
include ../libraries.mak

PROGRAM = TestConnectorAcceptor
SOURCES = ConnectorAcceptor.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)
