ROOT = ../../../..
include ../../libraries.mak

DIR = Providers/sample/QueryProvider

include $(ROOT)/mak/config.mak

LIBRARY = SampleQueryProvider

LIBRARIES = \
	 pegcommon \
	 pegprovider
	
SOURCES = \
   QueryProviderMain.cpp \
   QueryProvider.cpp

include $(ROOT)/mak/library.mak

tests:
