ROOT = ../../..

DIR = Clients/TestClient
include $(ROOT)/mak/config.mak
include ../libraries.mak

PROGRAM = TestClient
SOURCES = TestClient.cpp


include $(ROOT)/mak/program.mak

tests:

poststarttests:
