ROOT = ../../../../..
DIR = Pegasus/Repository/tests/CompareRepositories

include $(ROOT)/mak/config.mak
include ../libraries.mak

LOCAL_DEFINES = -DPEGASUS_INTERNALONLY
LOCAL_CLEAN_TARGET=local-clean

PROGRAM = CompareRepositories
SOURCES = CompareRepositories.cpp

include $(ROOT)/mak/program.mak

.PHONY: FORCE local-clean tests poststarttests

FORCE: 

local-clean:

tests:

poststarttests:

