instance of PG_ProviderModule
{
   Name = "LinuxDiskDriveProviderModule";
   Location = "LinuxDiskDriveProvider";
   Vendor = "Pegasus Community";
   Version = "2.0.0";
   InterfaceType = "C++Default";
   InterfaceVersion = "2.0.0";
};

instance of PG_Provider
{
   ProviderModuleName = "LinuxDiskDriveProviderModule";
   Name = "LinuxDiskDriveProvider";
};

instance of PG_ProviderCapabilities
{
   ProviderModuleName = "LinuxDiskDriveProviderModule";
   ProviderName = "LinuxDiskDriveProvider";
   CapabilityID = "1";
   ClassName = "Linux_DiskDrive";
   Namespaces[] = {"root/cimv2"};
   ProviderType[] = { 2 }; // Instance
   SupportedProperties[] = NULL; // All properties
   SupportedMethods[] = NULL; // All methods
};
