instance of CIM_Provider {
SystemCreationClassName = "CIM_ComputerSystem";
SystemName = "";
CreationClassName = "CIM_Provider";
Name = "LinuxDiskDriveProvider";
Location = "LinuxDiskDriveProvider";
};

instance of CIM_ProviderCapabilities {
InstanceID = "PGLinux_DiskDriveProvider_1";
Name = "PGLinux_DiskDriveProvider";
ClassName = "Linux_DiskDrive";
//ProviderType = { 2 }; // Instance
OtherProviderType = "";
//SupportedProperties = {}; // All properties 
//SupportedMethods = {}; // All methods
};

instance of CIM_ProviderElementCapabilities {
        ManagedElement = "CIM_Provider.CreationClassName=\"CIM_Provider\",Name=\"LinuxDiskDriveProvider\",SystemCreationClassName=\"CIM_ComputerSystem\",SystemName=\"\"";
        Capabilities = "CIM_ProviderCapabilities.InstanceID=\"PGLinux_DiskDriveProvider_1\"";
};

