instance of CIM_Provider  {
SystemCreationClassName = "CIM_ComputerSystem";
SystemName = "";
CreationClassName = "CIM_Provider";
Name = "LinuxNetworkAdapterProvider";
Location = "LinuxNetworkAdapterProvider";
};

instance of CIM_ProviderCapabilities  {
InstanceID = "PGLinux_NetworkAdapterProvider_1";
Name = "PGLinux_NetworkAdpaterProvider";
ClassName = "Linux_NetworkAdapter";
//ProviderType = { 2 }; // Instance
OtherProviderType = "";
//SupportedProperties = {}; // All properties 
//SupportedMethods = {}; // All methods
};

instance of CIM_ProviderCapabilities  {
InstanceID = "PGLinux_NetworkAdapterProvider_2";
Name = "PGLinux_NetworkAdpaterProvider";
ClassName = "Linux_EthernetAdapter";
//ProviderType = { 2 }; // Instance
OtherProviderType = "";
//SupportedProperties = {}; // All properties 
//SupportedMethods = {}; // All methods
};

instance of CIM_ProviderElementCapabilities {
        ManagedElement = "CIM_Provider.CreationClassName=\"CIM_Provider\",Name=\"LinuxNetworkAdapterProvider\",SystemCreationClassName=\"CIM_ComputerSystem\",SystemName=\"\"";
        Capabilities = "CIM_ProviderCapabilities.InstanceID=\"PGLinux_NetworkAdapterProvider_1\"";
};

instance of CIM_ProviderElementCapabilities {
        ManagedElement = "CIM_Provider.CreationClassName=\"CIM_Provider\",Name=\"LinuxNetworkAdapterProvider\",SystemCreationClassName=\"CIM_ComputerSystem\",SystemName=\"\"";
        Capabilities = "CIM_ProviderCapabilities.InstanceID=\"PGLinux_NetworkAdapterProvider_2\"";
};

