instance of PG_ProviderModule
{
   Name = "LinuxOperatingSystemProviderModule";
   Location = "LinuxOperatingSystemProvider";
   Vendor = "Pegasus Community";
   Version = "2.0.0";
   InterfaceType = "C++Default";
   InterfaceVersion = "2.0.0";
};

instance of PG_Provider
{
   ProviderModuleName = "LinuxOperatingSystemProviderModule";
   Name = "LinuxOperatingSystemProvider";
};

instance of PG_ProviderCapabilities
{
   ProviderModuleName = "LinuxOperatingSystemProviderModule";
   ProviderName = "LinuxOperatingSystemProvider";
   CapabilityID = "1";
   ClassName = "Linux_OperatingSystem";
   Namespaces = {"root/cimv2"};
   ProviderType = { 2 }; // Instance
   SupportedProperties = NULL; // All properties
   SupportedMethods = NULL; // All methods
};
