instance of CIM_Provider {
SystemCreationClassName = "CIM_ComputerSystem";
SystemName = "";
CreationClassName = "CIM_Provider";
Name = "LinuxSoftwareElementProvider";
Location = "LinuxSofwareElementProvider";
};

instance of CIM_ProviderCapabilities {
InstanceID = "PGLinux_SoftwareElementProvider_1";
Name = "PGLinux_SoftwareElementProvider";
ClassName = "Linux_Debian_SoftwareElement";
//ProviderType = { 2 }; // Instance
OtherProviderType = "";
//SupportedProperties = {}; // All properties 
//SupportedMethods = {}; // All methods
};

instance of CIM_ProviderElementCapabilities {
        ManagedElement = "CIM_Provider.CreationClassName=\"CIM_Provider\",Name=\"LinuxSoftwareElementProvider\",SystemCreationClassName=\"CIM_ComputerSystem\",SystemName=\"\"";
        Capabilities = "CIM_ProviderCapabilities.InstanceID=\"PGLinux_SoftwareElementProvider_1\"";
};

