ROOT = ../../../../..
include ../libraries.mak

DIR = Pegasus/Common/tests/DynLib

include $(ROOT)/mak/config.mak

LOCAL_DEFINES = -DPEGASUS_INTERNALONLY

SOURCES = DynLib.cpp

LIBRARY = DynLib

include $(ROOT)/mak/library.mak

tests:

poststarttests:
