ROOT = ../../../../..
DIR = Pegasus/Common/tests/async_callback
include $(ROOT)/mak/config.mak
include ../libraries.mak

LOCAL_DEFINES = -DPEGASUS_INTERNALONLY

PROGRAM = async_callback
SOURCES = async_callback.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)

poststarttests:

