include $(PEGASUS_ROOT)/mak/config.mak

DIR = Unsupported/LifecycleIndicationProvider

LIBRARY = SampleLifecycleIndicationProvider

LIBRARIES = \
	pegcommon \
	pegprovider
	
SOURCES = \
	LifecycleIndicationProviderMain.cpp \
	LifecycleIndicationProvider.cpp

include $(PEGASUS_ROOT)/mak/library.mak
