include $(PEGASUS_ROOT)/mak/config.mak

DIR = Providers/sample/AlertIndicationProvider

LIBRARY = AlertIndicationProvider

LIBRARIES = \
	pegcommon \
	pegprovider
	
SOURCES = \
	AlertIndicationProviderMain.cpp \
	AlertIndicationProvider.cpp

include $(PEGASUS_ROOT)/mak/library.mak
