##
## Copy this file to <pegasus_root>/configure.mak
##
export PEGASUS_PLATFORM=LINUX_X86_64_GNU
export PEGASUS_HOME=$(PEGASUS_ROOT)/$(PEGASUS_PLATFORM)
export PEGASUS_DISABLE_PROV_USERCTXT=1
export PEGASUS_DEFAULT_ENABLE_OOP=false
export PEGASUS_DEBUG=1
