##
## Copy this file to <pegasus_root>/configure.mak
##
export PEGASUS_PLATFORM=SOLARIS_SPARC_GNU
export PEGASUS_HOME=$(PEGASUS_ROOT)/$(PEGASUS_PLATFORM)
export PEGASUS_DISABLE_PROV_USERCTXT=1
export PEGASUS_DEFAULT_ENABLE_OOP=false
