
all:
	$(MAKE) -f jmpi.mak
	$(MAKE) -C org/pegasus/jmpi
	$(MAKE) -C org/pegasus/jmpi/tests/JMPI_TestPropertyTypes

clean:
	$(MAKE) -f jmpi.mak clean
	$(MAKE) -C org/pegasus/jmpi clean
	$(MAKE) -C org/pegasus/jmpi/tests/JMPI_TestPropertyTypes clean

messages:
