include $(PEGASUS_ROOT)/mak/config.mak

DIR = Pegasus/Server/tests/SafeQueue

LIBRARIES = \
	pegcommon \
	pegprovider \
	pegprovidermanager

LOCAL_DEFINES = -DPEGASUS_INTERNALONLY

PROGRAM = TestSafeQueue

SOURCES = SafeQueue.cpp

include $(PEGASUS_ROOT)/mak/program.mak

tests:
