ROOT = ../../..

include ../libraries.mak

DIR = TestProviders/PG_TestPropertyTypes

include $(ROOT)/mak/config.mak

LIBRARY = PG_TestPropertyTypes

LIBRARIES = \
    pegcommon \
    pegprovider 
	
SOURCES = \
   PG_TestPropertyTypes.cpp

include $(ROOT)/mak/library.mak

tests:
