ROOT = ../../../../..
DIR = Pegasus/Common/tests/Acceptor
include $(ROOT)/mak/config.mak
include ../libraries.mak

PROGRAM = TestAcceptor
SOURCES = Acceptor.cpp

include $(ROOT)/mak/program.mak

tests:
