ROOT = ../../../../..
DIR = Pegasus/Common/tests/Acceptor
include $(ROOT)/mak/config.mak
include ../libraries.mak

PROGRAM = Acceptor
SOURCES = Acceptor.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)
