ROOT=../../../../..

include $(ROOT)/mak/config.mak

DIRS = \
    LocalAuthFile \
    LocalAuthenticationHandler \
    BasicAuthenticationHandler \
    AuthenticationManager 

include $(ROOT)/mak/recurse.mak
