include $(PEGASUS_ROOT)/mak/config.mak

DIR = Pegasus/Server/tests/ProviderManagerService

LIBRARIES = \
	pegcommon \
	pegprovider \
	pegprovidermanager

PROGRAM = TestProviderManagerService

SOURCES = ProviderManagerService.cpp

include $(PEGASUS_ROOT)/mak/program.mak

tests:
