ROOT = ../../..
include $(ROOT)/mak/config.mak

LIBRARY = SampleMethodProvider

SOURCE_DIR = Providers/DefaultC++/MethodProvider

LIBRARIES = \
  pegcommon \
  pegprovider

SOURCES = \
        MethodProviderMain.cpp \
        MethodProvider.cpp

include $(ROOT)/mak/library.mak

tests:
