ROOT = ../../../../..
DIR = Pegasus/Common/tests/Value
include $(ROOT)/mak/config.mak
include ../libraries.mak

LOCAL_DEFINES = -DPEGASUS_INTERNALONLY

PROGRAM = TestValue

SOURCES = Value.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)

poststarttests:

