ROOT = ../../../../..
DIR = Pegasus/Common/tests/Value
include $(ROOT)/mak/config.mak
include ../libraries.mak

PROGRAM = TestValue

SOURCES = Value.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)
