ROOT = ../../../../..
DIR = Pegasus/Common/tests/Reference
include $(ROOT)/mak/config.mak
include ../libraries.mak

PROGRAM = Reference
SOURCES = Reference.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)
