ROOT = ../../../../..
DIR = Pegasus/Common/tests/Property
include $(ROOT)/mak/config.mak
include ../libraries.mak

PROGRAM = Property
SOURCES = Property.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)
