ROOT = ../../../../..
DIR = Pegasus/Common/tests/Property
include $(ROOT)/mak/config.mak
include ../libraries.mak

LOCAL_DEFINES = -DPEGASUS_INTERNALONLY

PROGRAM = TestProperty
SOURCES = Property.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)

poststarttests:

