
ROOT = ../../../../../../../../..
include $(ROOT)/mak/config.mak
#include $(ROOT)/test/config.mak
include ../config.mak

XMLSCRIPTS = MethodCall1000

#ifndef SECURITY_ENABLED
#XMLSCRIPTS += \
#              DeleteInstance55002
#endif

include $(ROOT)/test/configend.mak
