include $(PEGASUS_ROOT)/mak/config.mak

DIR = Providers/sample/IndicationProvider

LIBRARY = SampleIndicationProvider

LIBRARIES = \
    pegprovider \
    pegclient \
    pegconfig \
    pegcommon
	
SOURCES = \
	IndicationProviderMain.cpp \
	IndicationProvider.cpp

include $(PEGASUS_ROOT)/mak/dynamic-library.mak
install:
