include $(PEGASUS_ROOT)/mak/config.mak

DIR = Providers/sample/IndicationProvider

LIBRARY = SampleIndicationProvider

LIBRARIES = \
	pegcommon \
	pegprovider
	
SOURCES = \
	IndicationProviderMain.cpp \
	IndicationProvider.cpp

include $(PEGASUS_ROOT)/mak/library.mak
