ROOT = ../../../../..
DIR = Pegasus/Config/tests/ConfigManager
include $(ROOT)/mak/config.mak
include ../libraries.mak

PROGRAM = TestConfigManager
SOURCES = ConfigManager.cpp

include $(ROOT)/mak/program.mak

tests:
	$(PROGRAM)
