
ROOT = ../../../..

include $(ROOT)/mak/config.mak
include $(ROOT)/test/config.mak

XMLSCRIPTS = Associators33000 Associators33001 Associators33002 Associators33003 Associators33004 Associators33005 Associators33006 Associators33007

include $(ROOT)/test/configend.mak

