ROOT=../../../../..
LIBRARIES=$(LIB_DIR)/$(LIB_PREFIX)pegcommon$(LIB_SUFFIX)
ifeq ($(PEGASUS_PLATFORM),ZOS_ZSERIES_IBM)
DYNAMIC_LIBRARIES=$(LIB_DIR)/$(LIB_PREFIX)pegcommon.x
else
DYNAMIC_LIBRARIES=-lpegcommon
endif
