ROOT=../../../..

include $(ROOT)/mak/config.mak

DIRS = \
    TimeValue \
    Dir \
    StrToInstName \
    ValidateClass \
    XmlParser \
    XmlDump \
    XmlPrint \
    Compare \
    String \
    FileSystem \
    Abstract \
    Array \
    DateTime \
    InstanceDecl \
    Method \
    Parameter \
    Property \
    Qualifier \
    QualifierDecl \
    QualifierList \
    String \
    Value \
    CGIQueryString \
    ClassDecl

XDIRS = \
    ValidateClass \
    Resolve \

include $(ROOT)/mak/recurse.mak
